services:
  server:
    build:
        context: "."
        dockerfile: Dockerfile
    container_name: "trx-node"
    environment:
      MAPTOOL_HOSTNAME: ${TRX_MAPTOOL_HOSTNAME}
      MAPTOOL_PORT: ${TRX_MAPTOOL_PORT}
      MAPTOOL_TOKEN: ${TRX_MAPTOOL_TOKEN}
    devices:
      - "/dev/ttyS3:/dev/ttyS0"
