// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/apponly.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { ChannelSettings } from "./channel";
import { Config_LoRaConfig } from "./config";

/**
 * This is the most compact possible representation for a set of channels.
 * It includes only one PRIMARY channel (which must be first) and
 * any SECONDARY channels.
 * No DISABLED channels are included.
 * This abstraction is used only on the the 'app side' of the world (ie python, javascript and android etc) to show a group of Channels as a (long) URL
 */
export interface ChannelSet {
  /** Channel list with settings */
  settings: ChannelSettings[];
  /** LoRa config */
  loraConfig: Config_LoRaConfig | undefined;
}

function createBaseChannelSet(): ChannelSet {
  return { settings: [], loraConfig: undefined };
}

export const ChannelSet = {
  encode(message: ChannelSet, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.settings) {
      ChannelSettings.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.loraConfig !== undefined) {
      Config_LoRaConfig.encode(message.loraConfig, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ChannelSet {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.settings.push(ChannelSettings.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.loraConfig = Config_LoRaConfig.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelSet {
    return {
      settings: globalThis.Array.isArray(object?.settings)
        ? object.settings.map((e: any) => ChannelSettings.fromJSON(e))
        : [],
      loraConfig: isSet(object.loraConfig) ? Config_LoRaConfig.fromJSON(object.loraConfig) : undefined,
    };
  },

  toJSON(message: ChannelSet): unknown {
    const obj: any = {};
    if (message.settings?.length) {
      obj.settings = message.settings.map((e) => ChannelSettings.toJSON(e));
    }
    if (message.loraConfig !== undefined) {
      obj.loraConfig = Config_LoRaConfig.toJSON(message.loraConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelSet>, I>>(base?: I): ChannelSet {
    return ChannelSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelSet>, I>>(object: I): ChannelSet {
    const message = createBaseChannelSet();
    message.settings = object.settings?.map((e) => ChannelSettings.fromPartial(e)) || [];
    message.loraConfig = (object.loraConfig !== undefined && object.loraConfig !== null)
      ? Config_LoRaConfig.fromPartial(object.loraConfig)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
