// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/cannedmessages.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/** Canned message module configuration. */
export interface CannedMessageModuleConfig {
  /** Predefined messages for canned message module separated by '|' characters. */
  messages: string;
}

function createBaseCannedMessageModuleConfig(): CannedMessageModuleConfig {
  return { messages: "" };
}

export const CannedMessageModuleConfig = {
  encode(message: CannedMessageModuleConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messages !== "") {
      writer.uint32(10).string(message.messages);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CannedMessageModuleConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCannedMessageModuleConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.messages = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CannedMessageModuleConfig {
    return { messages: isSet(object.messages) ? globalThis.String(object.messages) : "" };
  },

  toJSON(message: CannedMessageModuleConfig): unknown {
    const obj: any = {};
    if (message.messages !== "") {
      obj.messages = message.messages;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CannedMessageModuleConfig>, I>>(base?: I): CannedMessageModuleConfig {
    return CannedMessageModuleConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CannedMessageModuleConfig>, I>>(object: I): CannedMessageModuleConfig {
    const message = createBaseCannedMessageModuleConfig();
    message.messages = object.messages ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
