// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/channel.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/**
 * This information can be encoded as a QRcode/url so that other users can configure
 * their radio to join the same channel.
 * A note about how channel names are shown to users: channelname-X
 * poundsymbol is a prefix used to indicate this is a channel name (idea from @professr).
 * Where X is a letter from A-Z (base 26) representing a hash of the PSK for this
 * channel - so that if the user changes anything about the channel (which does
 * force a new PSK) this letter will also change. Thus preventing user confusion if
 * two friends try to type in a channel name of "BobsChan" and then can't talk
 * because their PSKs will be different.
 * The PSK is hashed into this letter by "0x41 + [xor all bytes of the psk ] modulo 26"
 * This also allows the option of someday if people have the PSK off (zero), the
 * users COULD type in a channel name and be able to talk.
 * FIXME: Add description of multi-channel support and how primary vs secondary channels are used.
 * FIXME: explain how apps use channels for security.
 * explain how remote settings and remote gpio are managed as an example
 */
export interface ChannelSettings {
  /**
   * Deprecated in favor of LoraConfig.channel_num
   *
   * @deprecated
   */
  channelNum: number;
  /**
   * A simple pre-shared key for now for crypto.
   * Must be either 0 bytes (no crypto), 16 bytes (AES128), or 32 bytes (AES256).
   * A special shorthand is used for 1 byte long psks.
   * These psks should be treated as only minimally secure,
   * because they are listed in this source code.
   * Those bytes are mapped using the following scheme:
   * `0` = No crypto
   * `1` = The special "default" channel key: {0xd4, 0xf1, 0xbb, 0x3a, 0x20, 0x29, 0x07, 0x59, 0xf0, 0xbc, 0xff, 0xab, 0xcf, 0x4e, 0x69, 0x01}
   * `2` through 10 = The default channel key, except with 1 through 9 added to the last byte.
   * Shown to user as simple1 through 10
   */
  psk: Uint8Array;
  /**
   * A SHORT name that will be packed into the URL.
   * Less than 12 bytes.
   * Something for end users to call the channel
   * If this is the empty string it is assumed that this channel
   * is the special (minimally secure) "Default"channel.
   * In user interfaces it should be rendered as a local language translation of "X".
   * For channel_num hashing empty string will be treated as "X".
   * Where "X" is selected based on the English words listed above for ModemPreset
   */
  name: string;
  /**
   * Used to construct a globally unique channel ID.
   * The full globally unique ID will be: "name.id" where ID is shown as base36.
   * Assuming that the number of meshtastic users is below 20K (true for a long time)
   * the chance of this 64 bit random number colliding with anyone else is super low.
   * And the penalty for collision is low as well, it just means that anyone trying to decrypt channel messages might need to
   * try multiple candidate channels.
   * Any time a non wire compatible change is made to a channel, this field should be regenerated.
   * There are a small number of 'special' globally known (and fairly) insecure standard channels.
   * Those channels do not have a numeric id included in the settings, but instead it is pulled from
   * a table of well known IDs.
   * (see Well Known Channels FIXME)
   */
  id: number;
  /** If true, messages on the mesh will be sent to the *public* internet by any gateway ndoe */
  uplinkEnabled: boolean;
  /** If true, messages seen on the internet will be forwarded to the local mesh. */
  downlinkEnabled: boolean;
  /** Per-channel module settings. */
  moduleSettings: ModuleSettings | undefined;
}

/** This message is specifically for modules to store per-channel configuration data. */
export interface ModuleSettings {
  /** Bits of precision for the location sent in position packets. */
  positionPrecision: number;
  /**
   * Controls whether or not the client / device should mute the current channel
   * Useful for noisy public channels you don't necessarily want to disable
   */
  isMuted: boolean;
}

/** A pair of a channel number, mode and the (sharable) settings for that channel */
export interface Channel {
  /**
   * The index of this channel in the channel table (from 0 to MAX_NUM_CHANNELS-1)
   * (Someday - not currently implemented) An index of -1 could be used to mean "set by name",
   * in which case the target node will find and set the channel by settings.name.
   */
  index: number;
  /** The new settings, or NULL to disable that channel */
  settings:
    | ChannelSettings
    | undefined;
  /** TODO: REPLACE */
  role: Channel_Role;
}

/**
 * How this channel is being used (or not).
 * Note: this field is an enum to give us options for the future.
 * In particular, someday we might make a 'SCANNING' option.
 * SCANNING channels could have different frequencies and the radio would
 * occasionally check that freq to see if anything is being transmitted.
 * For devices that have multiple physical radios attached, we could keep multiple PRIMARY/SCANNING channels active at once to allow
 * cross band routing as needed.
 * If a device has only a single radio (the common case) only one channel can be PRIMARY at a time
 * (but any number of SECONDARY channels can't be sent received on that common frequency)
 */
export enum Channel_Role {
  /** DISABLED - This channel is not in use right now */
  DISABLED = 0,
  /** PRIMARY - This channel is used to set the frequency for the radio - all other enabled channels must be SECONDARY */
  PRIMARY = 1,
  /**
   * SECONDARY - Secondary channels are only used for encryption/decryption/authentication purposes.
   * Their radio settings (freq etc) are ignored, only psk is used.
   */
  SECONDARY = 2,
  UNRECOGNIZED = -1,
}

export function channel_RoleFromJSON(object: any): Channel_Role {
  switch (object) {
    case 0:
    case "DISABLED":
      return Channel_Role.DISABLED;
    case 1:
    case "PRIMARY":
      return Channel_Role.PRIMARY;
    case 2:
    case "SECONDARY":
      return Channel_Role.SECONDARY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Channel_Role.UNRECOGNIZED;
  }
}

export function channel_RoleToJSON(object: Channel_Role): string {
  switch (object) {
    case Channel_Role.DISABLED:
      return "DISABLED";
    case Channel_Role.PRIMARY:
      return "PRIMARY";
    case Channel_Role.SECONDARY:
      return "SECONDARY";
    case Channel_Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseChannelSettings(): ChannelSettings {
  return {
    channelNum: 0,
    psk: new Uint8Array(0),
    name: "",
    id: 0,
    uplinkEnabled: false,
    downlinkEnabled: false,
    moduleSettings: undefined,
  };
}

export const ChannelSettings = {
  encode(message: ChannelSettings, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.channelNum !== 0) {
      writer.uint32(8).uint32(message.channelNum);
    }
    if (message.psk.length !== 0) {
      writer.uint32(18).bytes(message.psk);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.id !== 0) {
      writer.uint32(37).fixed32(message.id);
    }
    if (message.uplinkEnabled !== false) {
      writer.uint32(40).bool(message.uplinkEnabled);
    }
    if (message.downlinkEnabled !== false) {
      writer.uint32(48).bool(message.downlinkEnabled);
    }
    if (message.moduleSettings !== undefined) {
      ModuleSettings.encode(message.moduleSettings, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ChannelSettings {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.channelNum = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.psk = reader.bytes();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.id = reader.fixed32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.uplinkEnabled = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.downlinkEnabled = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.moduleSettings = ModuleSettings.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelSettings {
    return {
      channelNum: isSet(object.channelNum) ? globalThis.Number(object.channelNum) : 0,
      psk: isSet(object.psk) ? bytesFromBase64(object.psk) : new Uint8Array(0),
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      uplinkEnabled: isSet(object.uplinkEnabled) ? globalThis.Boolean(object.uplinkEnabled) : false,
      downlinkEnabled: isSet(object.downlinkEnabled) ? globalThis.Boolean(object.downlinkEnabled) : false,
      moduleSettings: isSet(object.moduleSettings) ? ModuleSettings.fromJSON(object.moduleSettings) : undefined,
    };
  },

  toJSON(message: ChannelSettings): unknown {
    const obj: any = {};
    if (message.channelNum !== 0) {
      obj.channelNum = Math.round(message.channelNum);
    }
    if (message.psk.length !== 0) {
      obj.psk = base64FromBytes(message.psk);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.uplinkEnabled !== false) {
      obj.uplinkEnabled = message.uplinkEnabled;
    }
    if (message.downlinkEnabled !== false) {
      obj.downlinkEnabled = message.downlinkEnabled;
    }
    if (message.moduleSettings !== undefined) {
      obj.moduleSettings = ModuleSettings.toJSON(message.moduleSettings);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelSettings>, I>>(base?: I): ChannelSettings {
    return ChannelSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelSettings>, I>>(object: I): ChannelSettings {
    const message = createBaseChannelSettings();
    message.channelNum = object.channelNum ?? 0;
    message.psk = object.psk ?? new Uint8Array(0);
    message.name = object.name ?? "";
    message.id = object.id ?? 0;
    message.uplinkEnabled = object.uplinkEnabled ?? false;
    message.downlinkEnabled = object.downlinkEnabled ?? false;
    message.moduleSettings = (object.moduleSettings !== undefined && object.moduleSettings !== null)
      ? ModuleSettings.fromPartial(object.moduleSettings)
      : undefined;
    return message;
  },
};

function createBaseModuleSettings(): ModuleSettings {
  return { positionPrecision: 0, isMuted: false };
}

export const ModuleSettings = {
  encode(message: ModuleSettings, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.positionPrecision !== 0) {
      writer.uint32(8).uint32(message.positionPrecision);
    }
    if (message.isMuted !== false) {
      writer.uint32(16).bool(message.isMuted);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ModuleSettings {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModuleSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.positionPrecision = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.isMuted = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModuleSettings {
    return {
      positionPrecision: isSet(object.positionPrecision) ? globalThis.Number(object.positionPrecision) : 0,
      isMuted: isSet(object.isMuted) ? globalThis.Boolean(object.isMuted) : false,
    };
  },

  toJSON(message: ModuleSettings): unknown {
    const obj: any = {};
    if (message.positionPrecision !== 0) {
      obj.positionPrecision = Math.round(message.positionPrecision);
    }
    if (message.isMuted !== false) {
      obj.isMuted = message.isMuted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModuleSettings>, I>>(base?: I): ModuleSettings {
    return ModuleSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModuleSettings>, I>>(object: I): ModuleSettings {
    const message = createBaseModuleSettings();
    message.positionPrecision = object.positionPrecision ?? 0;
    message.isMuted = object.isMuted ?? false;
    return message;
  },
};

function createBaseChannel(): Channel {
  return { index: 0, settings: undefined, role: 0 };
}

export const Channel = {
  encode(message: Channel, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).int32(message.index);
    }
    if (message.settings !== undefined) {
      ChannelSettings.encode(message.settings, writer.uint32(18).fork()).ldelim();
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Channel {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.settings = ChannelSettings.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Channel {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      settings: isSet(object.settings) ? ChannelSettings.fromJSON(object.settings) : undefined,
      role: isSet(object.role) ? channel_RoleFromJSON(object.role) : 0,
    };
  },

  toJSON(message: Channel): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.settings !== undefined) {
      obj.settings = ChannelSettings.toJSON(message.settings);
    }
    if (message.role !== 0) {
      obj.role = channel_RoleToJSON(message.role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Channel>, I>>(base?: I): Channel {
    return Channel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Channel>, I>>(object: I): Channel {
    const message = createBaseChannel();
    message.index = object.index ?? 0;
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? ChannelSettings.fromPartial(object.settings)
      : undefined;
    message.role = object.role ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
