// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/clientonly.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { LocalConfig, LocalModuleConfig } from "./localonly";
import { Position } from "./mesh";

/**
 * This abstraction is used to contain any configuration for provisioning a node on any client.
 * It is useful for importing and exporting configurations.
 */
export interface DeviceProfile {
  /** Long name for the node */
  longName?:
    | string
    | undefined;
  /** Short name of the node */
  shortName?:
    | string
    | undefined;
  /** The url of the channels from our node */
  channelUrl?:
    | string
    | undefined;
  /** The Config of the node */
  config?:
    | LocalConfig
    | undefined;
  /** The ModuleConfig of the node */
  moduleConfig?:
    | LocalModuleConfig
    | undefined;
  /** Fixed position data */
  fixedPosition?:
    | Position
    | undefined;
  /** Ringtone for ExternalNotification */
  ringtone?:
    | string
    | undefined;
  /** Predefined messages for CannedMessage */
  cannedMessages?: string | undefined;
}

function createBaseDeviceProfile(): DeviceProfile {
  return {
    longName: undefined,
    shortName: undefined,
    channelUrl: undefined,
    config: undefined,
    moduleConfig: undefined,
    fixedPosition: undefined,
    ringtone: undefined,
    cannedMessages: undefined,
  };
}

export const DeviceProfile = {
  encode(message: DeviceProfile, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.longName !== undefined) {
      writer.uint32(10).string(message.longName);
    }
    if (message.shortName !== undefined) {
      writer.uint32(18).string(message.shortName);
    }
    if (message.channelUrl !== undefined) {
      writer.uint32(26).string(message.channelUrl);
    }
    if (message.config !== undefined) {
      LocalConfig.encode(message.config, writer.uint32(34).fork()).ldelim();
    }
    if (message.moduleConfig !== undefined) {
      LocalModuleConfig.encode(message.moduleConfig, writer.uint32(42).fork()).ldelim();
    }
    if (message.fixedPosition !== undefined) {
      Position.encode(message.fixedPosition, writer.uint32(50).fork()).ldelim();
    }
    if (message.ringtone !== undefined) {
      writer.uint32(58).string(message.ringtone);
    }
    if (message.cannedMessages !== undefined) {
      writer.uint32(66).string(message.cannedMessages);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeviceProfile {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.longName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.shortName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.channelUrl = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.config = LocalConfig.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.moduleConfig = LocalModuleConfig.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.fixedPosition = Position.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.ringtone = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.cannedMessages = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceProfile {
    return {
      longName: isSet(object.longName) ? globalThis.String(object.longName) : undefined,
      shortName: isSet(object.shortName) ? globalThis.String(object.shortName) : undefined,
      channelUrl: isSet(object.channelUrl) ? globalThis.String(object.channelUrl) : undefined,
      config: isSet(object.config) ? LocalConfig.fromJSON(object.config) : undefined,
      moduleConfig: isSet(object.moduleConfig) ? LocalModuleConfig.fromJSON(object.moduleConfig) : undefined,
      fixedPosition: isSet(object.fixedPosition) ? Position.fromJSON(object.fixedPosition) : undefined,
      ringtone: isSet(object.ringtone) ? globalThis.String(object.ringtone) : undefined,
      cannedMessages: isSet(object.cannedMessages) ? globalThis.String(object.cannedMessages) : undefined,
    };
  },

  toJSON(message: DeviceProfile): unknown {
    const obj: any = {};
    if (message.longName !== undefined) {
      obj.longName = message.longName;
    }
    if (message.shortName !== undefined) {
      obj.shortName = message.shortName;
    }
    if (message.channelUrl !== undefined) {
      obj.channelUrl = message.channelUrl;
    }
    if (message.config !== undefined) {
      obj.config = LocalConfig.toJSON(message.config);
    }
    if (message.moduleConfig !== undefined) {
      obj.moduleConfig = LocalModuleConfig.toJSON(message.moduleConfig);
    }
    if (message.fixedPosition !== undefined) {
      obj.fixedPosition = Position.toJSON(message.fixedPosition);
    }
    if (message.ringtone !== undefined) {
      obj.ringtone = message.ringtone;
    }
    if (message.cannedMessages !== undefined) {
      obj.cannedMessages = message.cannedMessages;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceProfile>, I>>(base?: I): DeviceProfile {
    return DeviceProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceProfile>, I>>(object: I): DeviceProfile {
    const message = createBaseDeviceProfile();
    message.longName = object.longName ?? undefined;
    message.shortName = object.shortName ?? undefined;
    message.channelUrl = object.channelUrl ?? undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? LocalConfig.fromPartial(object.config)
      : undefined;
    message.moduleConfig = (object.moduleConfig !== undefined && object.moduleConfig !== null)
      ? LocalModuleConfig.fromPartial(object.moduleConfig)
      : undefined;
    message.fixedPosition = (object.fixedPosition !== undefined && object.fixedPosition !== null)
      ? Position.fromPartial(object.fixedPosition)
      : undefined;
    message.ringtone = object.ringtone ?? undefined;
    message.cannedMessages = object.cannedMessages ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
