// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/connection_status.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export interface DeviceConnectionStatus {
  /** WiFi Status */
  wifi?:
    | WifiConnectionStatus
    | undefined;
  /** WiFi Status */
  ethernet?:
    | EthernetConnectionStatus
    | undefined;
  /** Bluetooth Status */
  bluetooth?:
    | BluetoothConnectionStatus
    | undefined;
  /** Serial Status */
  serial?: SerialConnectionStatus | undefined;
}

/** WiFi connection status */
export interface WifiConnectionStatus {
  /** Connection status */
  status:
    | NetworkConnectionStatus
    | undefined;
  /** WiFi access point SSID */
  ssid: string;
  /** RSSI of wireless connection */
  rssi: number;
}

/** Ethernet connection status */
export interface EthernetConnectionStatus {
  /** Connection status */
  status: NetworkConnectionStatus | undefined;
}

/** Ethernet or WiFi connection status */
export interface NetworkConnectionStatus {
  /** IP address of device */
  ipAddress: number;
  /** Whether the device has an active connection or not */
  isConnected: boolean;
  /** Whether the device has an active connection to an MQTT broker or not */
  isMqttConnected: boolean;
  /** Whether the device is actively remote syslogging or not */
  isSyslogConnected: boolean;
}

/** Bluetooth connection status */
export interface BluetoothConnectionStatus {
  /** The pairing PIN for bluetooth */
  pin: number;
  /** RSSI of bluetooth connection */
  rssi: number;
  /** Whether the device has an active connection or not */
  isConnected: boolean;
}

/** Serial connection status */
export interface SerialConnectionStatus {
  /** Serial baud rate */
  baud: number;
  /** Whether the device has an active connection or not */
  isConnected: boolean;
}

function createBaseDeviceConnectionStatus(): DeviceConnectionStatus {
  return { wifi: undefined, ethernet: undefined, bluetooth: undefined, serial: undefined };
}

export const DeviceConnectionStatus = {
  encode(message: DeviceConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.wifi !== undefined) {
      WifiConnectionStatus.encode(message.wifi, writer.uint32(10).fork()).ldelim();
    }
    if (message.ethernet !== undefined) {
      EthernetConnectionStatus.encode(message.ethernet, writer.uint32(18).fork()).ldelim();
    }
    if (message.bluetooth !== undefined) {
      BluetoothConnectionStatus.encode(message.bluetooth, writer.uint32(26).fork()).ldelim();
    }
    if (message.serial !== undefined) {
      SerialConnectionStatus.encode(message.serial, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeviceConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.wifi = WifiConnectionStatus.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ethernet = EthernetConnectionStatus.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bluetooth = BluetoothConnectionStatus.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.serial = SerialConnectionStatus.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceConnectionStatus {
    return {
      wifi: isSet(object.wifi) ? WifiConnectionStatus.fromJSON(object.wifi) : undefined,
      ethernet: isSet(object.ethernet) ? EthernetConnectionStatus.fromJSON(object.ethernet) : undefined,
      bluetooth: isSet(object.bluetooth) ? BluetoothConnectionStatus.fromJSON(object.bluetooth) : undefined,
      serial: isSet(object.serial) ? SerialConnectionStatus.fromJSON(object.serial) : undefined,
    };
  },

  toJSON(message: DeviceConnectionStatus): unknown {
    const obj: any = {};
    if (message.wifi !== undefined) {
      obj.wifi = WifiConnectionStatus.toJSON(message.wifi);
    }
    if (message.ethernet !== undefined) {
      obj.ethernet = EthernetConnectionStatus.toJSON(message.ethernet);
    }
    if (message.bluetooth !== undefined) {
      obj.bluetooth = BluetoothConnectionStatus.toJSON(message.bluetooth);
    }
    if (message.serial !== undefined) {
      obj.serial = SerialConnectionStatus.toJSON(message.serial);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceConnectionStatus>, I>>(base?: I): DeviceConnectionStatus {
    return DeviceConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceConnectionStatus>, I>>(object: I): DeviceConnectionStatus {
    const message = createBaseDeviceConnectionStatus();
    message.wifi = (object.wifi !== undefined && object.wifi !== null)
      ? WifiConnectionStatus.fromPartial(object.wifi)
      : undefined;
    message.ethernet = (object.ethernet !== undefined && object.ethernet !== null)
      ? EthernetConnectionStatus.fromPartial(object.ethernet)
      : undefined;
    message.bluetooth = (object.bluetooth !== undefined && object.bluetooth !== null)
      ? BluetoothConnectionStatus.fromPartial(object.bluetooth)
      : undefined;
    message.serial = (object.serial !== undefined && object.serial !== null)
      ? SerialConnectionStatus.fromPartial(object.serial)
      : undefined;
    return message;
  },
};

function createBaseWifiConnectionStatus(): WifiConnectionStatus {
  return { status: undefined, ssid: "", rssi: 0 };
}

export const WifiConnectionStatus = {
  encode(message: WifiConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.status !== undefined) {
      NetworkConnectionStatus.encode(message.status, writer.uint32(10).fork()).ldelim();
    }
    if (message.ssid !== "") {
      writer.uint32(18).string(message.ssid);
    }
    if (message.rssi !== 0) {
      writer.uint32(24).int32(message.rssi);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WifiConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.status = NetworkConnectionStatus.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ssid = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.rssi = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiConnectionStatus {
    return {
      status: isSet(object.status) ? NetworkConnectionStatus.fromJSON(object.status) : undefined,
      ssid: isSet(object.ssid) ? globalThis.String(object.ssid) : "",
      rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0,
    };
  },

  toJSON(message: WifiConnectionStatus): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = NetworkConnectionStatus.toJSON(message.status);
    }
    if (message.ssid !== "") {
      obj.ssid = message.ssid;
    }
    if (message.rssi !== 0) {
      obj.rssi = Math.round(message.rssi);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiConnectionStatus>, I>>(base?: I): WifiConnectionStatus {
    return WifiConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiConnectionStatus>, I>>(object: I): WifiConnectionStatus {
    const message = createBaseWifiConnectionStatus();
    message.status = (object.status !== undefined && object.status !== null)
      ? NetworkConnectionStatus.fromPartial(object.status)
      : undefined;
    message.ssid = object.ssid ?? "";
    message.rssi = object.rssi ?? 0;
    return message;
  },
};

function createBaseEthernetConnectionStatus(): EthernetConnectionStatus {
  return { status: undefined };
}

export const EthernetConnectionStatus = {
  encode(message: EthernetConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.status !== undefined) {
      NetworkConnectionStatus.encode(message.status, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EthernetConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEthernetConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.status = NetworkConnectionStatus.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EthernetConnectionStatus {
    return { status: isSet(object.status) ? NetworkConnectionStatus.fromJSON(object.status) : undefined };
  },

  toJSON(message: EthernetConnectionStatus): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = NetworkConnectionStatus.toJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EthernetConnectionStatus>, I>>(base?: I): EthernetConnectionStatus {
    return EthernetConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EthernetConnectionStatus>, I>>(object: I): EthernetConnectionStatus {
    const message = createBaseEthernetConnectionStatus();
    message.status = (object.status !== undefined && object.status !== null)
      ? NetworkConnectionStatus.fromPartial(object.status)
      : undefined;
    return message;
  },
};

function createBaseNetworkConnectionStatus(): NetworkConnectionStatus {
  return { ipAddress: 0, isConnected: false, isMqttConnected: false, isSyslogConnected: false };
}

export const NetworkConnectionStatus = {
  encode(message: NetworkConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ipAddress !== 0) {
      writer.uint32(13).fixed32(message.ipAddress);
    }
    if (message.isConnected !== false) {
      writer.uint32(16).bool(message.isConnected);
    }
    if (message.isMqttConnected !== false) {
      writer.uint32(24).bool(message.isMqttConnected);
    }
    if (message.isSyslogConnected !== false) {
      writer.uint32(32).bool(message.isSyslogConnected);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NetworkConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.ipAddress = reader.fixed32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.isConnected = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isMqttConnected = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.isSyslogConnected = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkConnectionStatus {
    return {
      ipAddress: isSet(object.ipAddress) ? globalThis.Number(object.ipAddress) : 0,
      isConnected: isSet(object.isConnected) ? globalThis.Boolean(object.isConnected) : false,
      isMqttConnected: isSet(object.isMqttConnected) ? globalThis.Boolean(object.isMqttConnected) : false,
      isSyslogConnected: isSet(object.isSyslogConnected) ? globalThis.Boolean(object.isSyslogConnected) : false,
    };
  },

  toJSON(message: NetworkConnectionStatus): unknown {
    const obj: any = {};
    if (message.ipAddress !== 0) {
      obj.ipAddress = Math.round(message.ipAddress);
    }
    if (message.isConnected !== false) {
      obj.isConnected = message.isConnected;
    }
    if (message.isMqttConnected !== false) {
      obj.isMqttConnected = message.isMqttConnected;
    }
    if (message.isSyslogConnected !== false) {
      obj.isSyslogConnected = message.isSyslogConnected;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkConnectionStatus>, I>>(base?: I): NetworkConnectionStatus {
    return NetworkConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkConnectionStatus>, I>>(object: I): NetworkConnectionStatus {
    const message = createBaseNetworkConnectionStatus();
    message.ipAddress = object.ipAddress ?? 0;
    message.isConnected = object.isConnected ?? false;
    message.isMqttConnected = object.isMqttConnected ?? false;
    message.isSyslogConnected = object.isSyslogConnected ?? false;
    return message;
  },
};

function createBaseBluetoothConnectionStatus(): BluetoothConnectionStatus {
  return { pin: 0, rssi: 0, isConnected: false };
}

export const BluetoothConnectionStatus = {
  encode(message: BluetoothConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pin !== 0) {
      writer.uint32(8).uint32(message.pin);
    }
    if (message.rssi !== 0) {
      writer.uint32(16).int32(message.rssi);
    }
    if (message.isConnected !== false) {
      writer.uint32(24).bool(message.isConnected);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BluetoothConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBluetoothConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.pin = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.rssi = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isConnected = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BluetoothConnectionStatus {
    return {
      pin: isSet(object.pin) ? globalThis.Number(object.pin) : 0,
      rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0,
      isConnected: isSet(object.isConnected) ? globalThis.Boolean(object.isConnected) : false,
    };
  },

  toJSON(message: BluetoothConnectionStatus): unknown {
    const obj: any = {};
    if (message.pin !== 0) {
      obj.pin = Math.round(message.pin);
    }
    if (message.rssi !== 0) {
      obj.rssi = Math.round(message.rssi);
    }
    if (message.isConnected !== false) {
      obj.isConnected = message.isConnected;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BluetoothConnectionStatus>, I>>(base?: I): BluetoothConnectionStatus {
    return BluetoothConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BluetoothConnectionStatus>, I>>(object: I): BluetoothConnectionStatus {
    const message = createBaseBluetoothConnectionStatus();
    message.pin = object.pin ?? 0;
    message.rssi = object.rssi ?? 0;
    message.isConnected = object.isConnected ?? false;
    return message;
  },
};

function createBaseSerialConnectionStatus(): SerialConnectionStatus {
  return { baud: 0, isConnected: false };
}

export const SerialConnectionStatus = {
  encode(message: SerialConnectionStatus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.baud !== 0) {
      writer.uint32(8).uint32(message.baud);
    }
    if (message.isConnected !== false) {
      writer.uint32(16).bool(message.isConnected);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SerialConnectionStatus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSerialConnectionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.baud = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.isConnected = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SerialConnectionStatus {
    return {
      baud: isSet(object.baud) ? globalThis.Number(object.baud) : 0,
      isConnected: isSet(object.isConnected) ? globalThis.Boolean(object.isConnected) : false,
    };
  },

  toJSON(message: SerialConnectionStatus): unknown {
    const obj: any = {};
    if (message.baud !== 0) {
      obj.baud = Math.round(message.baud);
    }
    if (message.isConnected !== false) {
      obj.isConnected = message.isConnected;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SerialConnectionStatus>, I>>(base?: I): SerialConnectionStatus {
    return SerialConnectionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SerialConnectionStatus>, I>>(object: I): SerialConnectionStatus {
    const message = createBaseSerialConnectionStatus();
    message.baud = object.baud ?? 0;
    message.isConnected = object.isConnected ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
