// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/device_ui.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export enum CompassMode {
  /** DYNAMIC - Compass with dynamic ring and heading */
  DYNAMIC = 0,
  /** FIXED_RING - Compass with fixed ring and heading */
  FIXED_RING = 1,
  /** FREEZE_HEADING - Compass with heading and freeze option */
  FREEZE_HEADING = 2,
  UNRECOGNIZED = -1,
}

export function compassModeFromJSON(object: any): CompassMode {
  switch (object) {
    case 0:
    case "DYNAMIC":
      return CompassMode.DYNAMIC;
    case 1:
    case "FIXED_RING":
      return CompassMode.FIXED_RING;
    case 2:
    case "FREEZE_HEADING":
      return CompassMode.FREEZE_HEADING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CompassMode.UNRECOGNIZED;
  }
}

export function compassModeToJSON(object: CompassMode): string {
  switch (object) {
    case CompassMode.DYNAMIC:
      return "DYNAMIC";
    case CompassMode.FIXED_RING:
      return "FIXED_RING";
    case CompassMode.FREEZE_HEADING:
      return "FREEZE_HEADING";
    case CompassMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Theme {
  /** DARK - Dark */
  DARK = 0,
  /** LIGHT - Light */
  LIGHT = 1,
  /** RED - Red */
  RED = 2,
  UNRECOGNIZED = -1,
}

export function themeFromJSON(object: any): Theme {
  switch (object) {
    case 0:
    case "DARK":
      return Theme.DARK;
    case 1:
    case "LIGHT":
      return Theme.LIGHT;
    case 2:
    case "RED":
      return Theme.RED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Theme.UNRECOGNIZED;
  }
}

export function themeToJSON(object: Theme): string {
  switch (object) {
    case Theme.DARK:
      return "DARK";
    case Theme.LIGHT:
      return "LIGHT";
    case Theme.RED:
      return "RED";
    case Theme.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Localization */
export enum Language {
  /** ENGLISH - English */
  ENGLISH = 0,
  /** FRENCH - French */
  FRENCH = 1,
  /** GERMAN - German */
  GERMAN = 2,
  /** ITALIAN - Italian */
  ITALIAN = 3,
  /** PORTUGUESE - Portuguese */
  PORTUGUESE = 4,
  /** SPANISH - Spanish */
  SPANISH = 5,
  /** SWEDISH - Swedish */
  SWEDISH = 6,
  /** FINNISH - Finnish */
  FINNISH = 7,
  /** POLISH - Polish */
  POLISH = 8,
  /** TURKISH - Turkish */
  TURKISH = 9,
  /** SERBIAN - Serbian */
  SERBIAN = 10,
  /** RUSSIAN - Russian */
  RUSSIAN = 11,
  /** DUTCH - Dutch */
  DUTCH = 12,
  /** GREEK - Greek */
  GREEK = 13,
  /** NORWEGIAN - Norwegian */
  NORWEGIAN = 14,
  /** SLOVENIAN - Slovenian */
  SLOVENIAN = 15,
  /** UKRAINIAN - Ukrainian */
  UKRAINIAN = 16,
  /** BULGARIAN - Bulgarian */
  BULGARIAN = 17,
  /** CZECH - Czech */
  CZECH = 18,
  /** DANISH - Danish */
  DANISH = 19,
  /** SIMPLIFIED_CHINESE - Simplified Chinese (experimental) */
  SIMPLIFIED_CHINESE = 30,
  /** TRADITIONAL_CHINESE - Traditional Chinese (experimental) */
  TRADITIONAL_CHINESE = 31,
  UNRECOGNIZED = -1,
}

export function languageFromJSON(object: any): Language {
  switch (object) {
    case 0:
    case "ENGLISH":
      return Language.ENGLISH;
    case 1:
    case "FRENCH":
      return Language.FRENCH;
    case 2:
    case "GERMAN":
      return Language.GERMAN;
    case 3:
    case "ITALIAN":
      return Language.ITALIAN;
    case 4:
    case "PORTUGUESE":
      return Language.PORTUGUESE;
    case 5:
    case "SPANISH":
      return Language.SPANISH;
    case 6:
    case "SWEDISH":
      return Language.SWEDISH;
    case 7:
    case "FINNISH":
      return Language.FINNISH;
    case 8:
    case "POLISH":
      return Language.POLISH;
    case 9:
    case "TURKISH":
      return Language.TURKISH;
    case 10:
    case "SERBIAN":
      return Language.SERBIAN;
    case 11:
    case "RUSSIAN":
      return Language.RUSSIAN;
    case 12:
    case "DUTCH":
      return Language.DUTCH;
    case 13:
    case "GREEK":
      return Language.GREEK;
    case 14:
    case "NORWEGIAN":
      return Language.NORWEGIAN;
    case 15:
    case "SLOVENIAN":
      return Language.SLOVENIAN;
    case 16:
    case "UKRAINIAN":
      return Language.UKRAINIAN;
    case 17:
    case "BULGARIAN":
      return Language.BULGARIAN;
    case 18:
    case "CZECH":
      return Language.CZECH;
    case 19:
    case "DANISH":
      return Language.DANISH;
    case 30:
    case "SIMPLIFIED_CHINESE":
      return Language.SIMPLIFIED_CHINESE;
    case 31:
    case "TRADITIONAL_CHINESE":
      return Language.TRADITIONAL_CHINESE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Language.UNRECOGNIZED;
  }
}

export function languageToJSON(object: Language): string {
  switch (object) {
    case Language.ENGLISH:
      return "ENGLISH";
    case Language.FRENCH:
      return "FRENCH";
    case Language.GERMAN:
      return "GERMAN";
    case Language.ITALIAN:
      return "ITALIAN";
    case Language.PORTUGUESE:
      return "PORTUGUESE";
    case Language.SPANISH:
      return "SPANISH";
    case Language.SWEDISH:
      return "SWEDISH";
    case Language.FINNISH:
      return "FINNISH";
    case Language.POLISH:
      return "POLISH";
    case Language.TURKISH:
      return "TURKISH";
    case Language.SERBIAN:
      return "SERBIAN";
    case Language.RUSSIAN:
      return "RUSSIAN";
    case Language.DUTCH:
      return "DUTCH";
    case Language.GREEK:
      return "GREEK";
    case Language.NORWEGIAN:
      return "NORWEGIAN";
    case Language.SLOVENIAN:
      return "SLOVENIAN";
    case Language.UKRAINIAN:
      return "UKRAINIAN";
    case Language.BULGARIAN:
      return "BULGARIAN";
    case Language.CZECH:
      return "CZECH";
    case Language.DANISH:
      return "DANISH";
    case Language.SIMPLIFIED_CHINESE:
      return "SIMPLIFIED_CHINESE";
    case Language.TRADITIONAL_CHINESE:
      return "TRADITIONAL_CHINESE";
    case Language.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DeviceUIConfig {
  /** A version integer used to invalidate saved files when we make incompatible changes. */
  version: number;
  /** TFT display brightness 1..255 */
  screenBrightness: number;
  /** Screen timeout 0..900 */
  screenTimeout: number;
  /** Screen/Settings lock enabled */
  screenLock: boolean;
  settingsLock: boolean;
  pinCode: number;
  /** Color theme */
  theme: Theme;
  /** Audible message, banner and ring tone */
  alertEnabled: boolean;
  bannerEnabled: boolean;
  ringToneId: number;
  /** Localization */
  language: Language;
  /** Node list filter */
  nodeFilter:
    | NodeFilter
    | undefined;
  /** Node list highlightening */
  nodeHighlight:
    | NodeHighlight
    | undefined;
  /** 8 integers for screen calibration data */
  calibrationData: Uint8Array;
  /** Map related data */
  mapData:
    | Map
    | undefined;
  /** Compass mode */
  compassMode: CompassMode;
  /**
   * RGB color for BaseUI
   * 0xRRGGBB format, e.g. 0xFF0000 for red
   */
  screenRgbColor: number;
  /**
   * Clockface analog style
   * true for analog clockface, false for digital clockface
   */
  isClockfaceAnalog: boolean;
  /** How the GPS coordinates are formatted on the OLED screen. */
  gpsFormat: DeviceUIConfig_GpsCoordinateFormat;
}

/** How the GPS coordinates are displayed on the OLED screen. */
export enum DeviceUIConfig_GpsCoordinateFormat {
  /**
   * DEC - GPS coordinates are displayed in the normal decimal degrees format:
   * DD.DDDDDD DDD.DDDDDD
   */
  DEC = 0,
  /**
   * DMS - GPS coordinates are displayed in the degrees minutes seconds format:
   * DD°MM'SS"C DDD°MM'SS"C, where C is the compass point representing the locations quadrant
   */
  DMS = 1,
  /**
   * UTM - Universal Transverse Mercator format:
   * ZZB EEEEEE NNNNNNN, where Z is zone, B is band, E is easting, N is northing
   */
  UTM = 2,
  /**
   * MGRS - Military Grid Reference System format:
   * ZZB CD EEEEE NNNNN, where Z is zone, B is band, C is the east 100k square, D is the north 100k square,
   * E is easting, N is northing
   */
  MGRS = 3,
  /** OLC - Open Location Code (aka Plus Codes). */
  OLC = 4,
  /**
   * OSGR - Ordnance Survey Grid Reference (the National Grid System of the UK).
   * Format: AB EEEEE NNNNN, where A is the east 100k square, B is the north 100k square,
   * E is the easting, N is the northing
   */
  OSGR = 5,
  /**
   * MLS - Maidenhead Locator System
   * Described here: https://en.wikipedia.org/wiki/Maidenhead_Locator_System
   */
  MLS = 6,
  UNRECOGNIZED = -1,
}

export function deviceUIConfig_GpsCoordinateFormatFromJSON(object: any): DeviceUIConfig_GpsCoordinateFormat {
  switch (object) {
    case 0:
    case "DEC":
      return DeviceUIConfig_GpsCoordinateFormat.DEC;
    case 1:
    case "DMS":
      return DeviceUIConfig_GpsCoordinateFormat.DMS;
    case 2:
    case "UTM":
      return DeviceUIConfig_GpsCoordinateFormat.UTM;
    case 3:
    case "MGRS":
      return DeviceUIConfig_GpsCoordinateFormat.MGRS;
    case 4:
    case "OLC":
      return DeviceUIConfig_GpsCoordinateFormat.OLC;
    case 5:
    case "OSGR":
      return DeviceUIConfig_GpsCoordinateFormat.OSGR;
    case 6:
    case "MLS":
      return DeviceUIConfig_GpsCoordinateFormat.MLS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DeviceUIConfig_GpsCoordinateFormat.UNRECOGNIZED;
  }
}

export function deviceUIConfig_GpsCoordinateFormatToJSON(object: DeviceUIConfig_GpsCoordinateFormat): string {
  switch (object) {
    case DeviceUIConfig_GpsCoordinateFormat.DEC:
      return "DEC";
    case DeviceUIConfig_GpsCoordinateFormat.DMS:
      return "DMS";
    case DeviceUIConfig_GpsCoordinateFormat.UTM:
      return "UTM";
    case DeviceUIConfig_GpsCoordinateFormat.MGRS:
      return "MGRS";
    case DeviceUIConfig_GpsCoordinateFormat.OLC:
      return "OLC";
    case DeviceUIConfig_GpsCoordinateFormat.OSGR:
      return "OSGR";
    case DeviceUIConfig_GpsCoordinateFormat.MLS:
      return "MLS";
    case DeviceUIConfig_GpsCoordinateFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NodeFilter {
  /** Filter unknown nodes */
  unknownSwitch: boolean;
  /** Filter offline nodes */
  offlineSwitch: boolean;
  /** Filter nodes w/o public key */
  publicKeySwitch: boolean;
  /** Filter based on hops away */
  hopsAway: number;
  /** Filter nodes w/o position */
  positionSwitch: boolean;
  /** Filter nodes by matching name string */
  nodeName: string;
  /** Filter based on channel */
  channel: number;
}

export interface NodeHighlight {
  /** Hightlight nodes w/ active chat */
  chatSwitch: boolean;
  /** Highlight nodes w/ position */
  positionSwitch: boolean;
  /** Highlight nodes w/ telemetry data */
  telemetrySwitch: boolean;
  /** Highlight nodes w/ iaq data */
  iaqSwitch: boolean;
  /** Highlight nodes by matching name string */
  nodeName: string;
}

export interface GeoPoint {
  /** Zoom level */
  zoom: number;
  /** Coordinate: latitude */
  latitude: number;
  /** Coordinate: longitude */
  longitude: number;
}

export interface Map {
  /** Home coordinates */
  home:
    | GeoPoint
    | undefined;
  /** Map tile style */
  style: string;
  /** Map scroll follows GPS */
  followGps: boolean;
}

function createBaseDeviceUIConfig(): DeviceUIConfig {
  return {
    version: 0,
    screenBrightness: 0,
    screenTimeout: 0,
    screenLock: false,
    settingsLock: false,
    pinCode: 0,
    theme: 0,
    alertEnabled: false,
    bannerEnabled: false,
    ringToneId: 0,
    language: 0,
    nodeFilter: undefined,
    nodeHighlight: undefined,
    calibrationData: new Uint8Array(0),
    mapData: undefined,
    compassMode: 0,
    screenRgbColor: 0,
    isClockfaceAnalog: false,
    gpsFormat: 0,
  };
}

export const DeviceUIConfig = {
  encode(message: DeviceUIConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    if (message.screenBrightness !== 0) {
      writer.uint32(16).uint32(message.screenBrightness);
    }
    if (message.screenTimeout !== 0) {
      writer.uint32(24).uint32(message.screenTimeout);
    }
    if (message.screenLock !== false) {
      writer.uint32(32).bool(message.screenLock);
    }
    if (message.settingsLock !== false) {
      writer.uint32(40).bool(message.settingsLock);
    }
    if (message.pinCode !== 0) {
      writer.uint32(48).uint32(message.pinCode);
    }
    if (message.theme !== 0) {
      writer.uint32(56).int32(message.theme);
    }
    if (message.alertEnabled !== false) {
      writer.uint32(64).bool(message.alertEnabled);
    }
    if (message.bannerEnabled !== false) {
      writer.uint32(72).bool(message.bannerEnabled);
    }
    if (message.ringToneId !== 0) {
      writer.uint32(80).uint32(message.ringToneId);
    }
    if (message.language !== 0) {
      writer.uint32(88).int32(message.language);
    }
    if (message.nodeFilter !== undefined) {
      NodeFilter.encode(message.nodeFilter, writer.uint32(98).fork()).ldelim();
    }
    if (message.nodeHighlight !== undefined) {
      NodeHighlight.encode(message.nodeHighlight, writer.uint32(106).fork()).ldelim();
    }
    if (message.calibrationData.length !== 0) {
      writer.uint32(114).bytes(message.calibrationData);
    }
    if (message.mapData !== undefined) {
      Map.encode(message.mapData, writer.uint32(122).fork()).ldelim();
    }
    if (message.compassMode !== 0) {
      writer.uint32(128).int32(message.compassMode);
    }
    if (message.screenRgbColor !== 0) {
      writer.uint32(136).uint32(message.screenRgbColor);
    }
    if (message.isClockfaceAnalog !== false) {
      writer.uint32(144).bool(message.isClockfaceAnalog);
    }
    if (message.gpsFormat !== 0) {
      writer.uint32(152).int32(message.gpsFormat);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeviceUIConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceUIConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.screenBrightness = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.screenTimeout = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.screenLock = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.settingsLock = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.pinCode = reader.uint32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.theme = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.alertEnabled = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.bannerEnabled = reader.bool();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.ringToneId = reader.uint32();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.nodeFilter = NodeFilter.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.nodeHighlight = NodeHighlight.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.calibrationData = reader.bytes();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.mapData = Map.decode(reader, reader.uint32());
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.compassMode = reader.int32() as any;
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.screenRgbColor = reader.uint32();
          continue;
        case 18:
          if (tag !== 144) {
            break;
          }

          message.isClockfaceAnalog = reader.bool();
          continue;
        case 19:
          if (tag !== 152) {
            break;
          }

          message.gpsFormat = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceUIConfig {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      screenBrightness: isSet(object.screenBrightness) ? globalThis.Number(object.screenBrightness) : 0,
      screenTimeout: isSet(object.screenTimeout) ? globalThis.Number(object.screenTimeout) : 0,
      screenLock: isSet(object.screenLock) ? globalThis.Boolean(object.screenLock) : false,
      settingsLock: isSet(object.settingsLock) ? globalThis.Boolean(object.settingsLock) : false,
      pinCode: isSet(object.pinCode) ? globalThis.Number(object.pinCode) : 0,
      theme: isSet(object.theme) ? themeFromJSON(object.theme) : 0,
      alertEnabled: isSet(object.alertEnabled) ? globalThis.Boolean(object.alertEnabled) : false,
      bannerEnabled: isSet(object.bannerEnabled) ? globalThis.Boolean(object.bannerEnabled) : false,
      ringToneId: isSet(object.ringToneId) ? globalThis.Number(object.ringToneId) : 0,
      language: isSet(object.language) ? languageFromJSON(object.language) : 0,
      nodeFilter: isSet(object.nodeFilter) ? NodeFilter.fromJSON(object.nodeFilter) : undefined,
      nodeHighlight: isSet(object.nodeHighlight) ? NodeHighlight.fromJSON(object.nodeHighlight) : undefined,
      calibrationData: isSet(object.calibrationData) ? bytesFromBase64(object.calibrationData) : new Uint8Array(0),
      mapData: isSet(object.mapData) ? Map.fromJSON(object.mapData) : undefined,
      compassMode: isSet(object.compassMode) ? compassModeFromJSON(object.compassMode) : 0,
      screenRgbColor: isSet(object.screenRgbColor) ? globalThis.Number(object.screenRgbColor) : 0,
      isClockfaceAnalog: isSet(object.isClockfaceAnalog) ? globalThis.Boolean(object.isClockfaceAnalog) : false,
      gpsFormat: isSet(object.gpsFormat) ? deviceUIConfig_GpsCoordinateFormatFromJSON(object.gpsFormat) : 0,
    };
  },

  toJSON(message: DeviceUIConfig): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.screenBrightness !== 0) {
      obj.screenBrightness = Math.round(message.screenBrightness);
    }
    if (message.screenTimeout !== 0) {
      obj.screenTimeout = Math.round(message.screenTimeout);
    }
    if (message.screenLock !== false) {
      obj.screenLock = message.screenLock;
    }
    if (message.settingsLock !== false) {
      obj.settingsLock = message.settingsLock;
    }
    if (message.pinCode !== 0) {
      obj.pinCode = Math.round(message.pinCode);
    }
    if (message.theme !== 0) {
      obj.theme = themeToJSON(message.theme);
    }
    if (message.alertEnabled !== false) {
      obj.alertEnabled = message.alertEnabled;
    }
    if (message.bannerEnabled !== false) {
      obj.bannerEnabled = message.bannerEnabled;
    }
    if (message.ringToneId !== 0) {
      obj.ringToneId = Math.round(message.ringToneId);
    }
    if (message.language !== 0) {
      obj.language = languageToJSON(message.language);
    }
    if (message.nodeFilter !== undefined) {
      obj.nodeFilter = NodeFilter.toJSON(message.nodeFilter);
    }
    if (message.nodeHighlight !== undefined) {
      obj.nodeHighlight = NodeHighlight.toJSON(message.nodeHighlight);
    }
    if (message.calibrationData.length !== 0) {
      obj.calibrationData = base64FromBytes(message.calibrationData);
    }
    if (message.mapData !== undefined) {
      obj.mapData = Map.toJSON(message.mapData);
    }
    if (message.compassMode !== 0) {
      obj.compassMode = compassModeToJSON(message.compassMode);
    }
    if (message.screenRgbColor !== 0) {
      obj.screenRgbColor = Math.round(message.screenRgbColor);
    }
    if (message.isClockfaceAnalog !== false) {
      obj.isClockfaceAnalog = message.isClockfaceAnalog;
    }
    if (message.gpsFormat !== 0) {
      obj.gpsFormat = deviceUIConfig_GpsCoordinateFormatToJSON(message.gpsFormat);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceUIConfig>, I>>(base?: I): DeviceUIConfig {
    return DeviceUIConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceUIConfig>, I>>(object: I): DeviceUIConfig {
    const message = createBaseDeviceUIConfig();
    message.version = object.version ?? 0;
    message.screenBrightness = object.screenBrightness ?? 0;
    message.screenTimeout = object.screenTimeout ?? 0;
    message.screenLock = object.screenLock ?? false;
    message.settingsLock = object.settingsLock ?? false;
    message.pinCode = object.pinCode ?? 0;
    message.theme = object.theme ?? 0;
    message.alertEnabled = object.alertEnabled ?? false;
    message.bannerEnabled = object.bannerEnabled ?? false;
    message.ringToneId = object.ringToneId ?? 0;
    message.language = object.language ?? 0;
    message.nodeFilter = (object.nodeFilter !== undefined && object.nodeFilter !== null)
      ? NodeFilter.fromPartial(object.nodeFilter)
      : undefined;
    message.nodeHighlight = (object.nodeHighlight !== undefined && object.nodeHighlight !== null)
      ? NodeHighlight.fromPartial(object.nodeHighlight)
      : undefined;
    message.calibrationData = object.calibrationData ?? new Uint8Array(0);
    message.mapData = (object.mapData !== undefined && object.mapData !== null)
      ? Map.fromPartial(object.mapData)
      : undefined;
    message.compassMode = object.compassMode ?? 0;
    message.screenRgbColor = object.screenRgbColor ?? 0;
    message.isClockfaceAnalog = object.isClockfaceAnalog ?? false;
    message.gpsFormat = object.gpsFormat ?? 0;
    return message;
  },
};

function createBaseNodeFilter(): NodeFilter {
  return {
    unknownSwitch: false,
    offlineSwitch: false,
    publicKeySwitch: false,
    hopsAway: 0,
    positionSwitch: false,
    nodeName: "",
    channel: 0,
  };
}

export const NodeFilter = {
  encode(message: NodeFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unknownSwitch !== false) {
      writer.uint32(8).bool(message.unknownSwitch);
    }
    if (message.offlineSwitch !== false) {
      writer.uint32(16).bool(message.offlineSwitch);
    }
    if (message.publicKeySwitch !== false) {
      writer.uint32(24).bool(message.publicKeySwitch);
    }
    if (message.hopsAway !== 0) {
      writer.uint32(32).int32(message.hopsAway);
    }
    if (message.positionSwitch !== false) {
      writer.uint32(40).bool(message.positionSwitch);
    }
    if (message.nodeName !== "") {
      writer.uint32(50).string(message.nodeName);
    }
    if (message.channel !== 0) {
      writer.uint32(56).int32(message.channel);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unknownSwitch = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.offlineSwitch = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.publicKeySwitch = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.hopsAway = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.positionSwitch = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.nodeName = reader.string();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.channel = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeFilter {
    return {
      unknownSwitch: isSet(object.unknownSwitch) ? globalThis.Boolean(object.unknownSwitch) : false,
      offlineSwitch: isSet(object.offlineSwitch) ? globalThis.Boolean(object.offlineSwitch) : false,
      publicKeySwitch: isSet(object.publicKeySwitch) ? globalThis.Boolean(object.publicKeySwitch) : false,
      hopsAway: isSet(object.hopsAway) ? globalThis.Number(object.hopsAway) : 0,
      positionSwitch: isSet(object.positionSwitch) ? globalThis.Boolean(object.positionSwitch) : false,
      nodeName: isSet(object.nodeName) ? globalThis.String(object.nodeName) : "",
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
    };
  },

  toJSON(message: NodeFilter): unknown {
    const obj: any = {};
    if (message.unknownSwitch !== false) {
      obj.unknownSwitch = message.unknownSwitch;
    }
    if (message.offlineSwitch !== false) {
      obj.offlineSwitch = message.offlineSwitch;
    }
    if (message.publicKeySwitch !== false) {
      obj.publicKeySwitch = message.publicKeySwitch;
    }
    if (message.hopsAway !== 0) {
      obj.hopsAway = Math.round(message.hopsAway);
    }
    if (message.positionSwitch !== false) {
      obj.positionSwitch = message.positionSwitch;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeFilter>, I>>(base?: I): NodeFilter {
    return NodeFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeFilter>, I>>(object: I): NodeFilter {
    const message = createBaseNodeFilter();
    message.unknownSwitch = object.unknownSwitch ?? false;
    message.offlineSwitch = object.offlineSwitch ?? false;
    message.publicKeySwitch = object.publicKeySwitch ?? false;
    message.hopsAway = object.hopsAway ?? 0;
    message.positionSwitch = object.positionSwitch ?? false;
    message.nodeName = object.nodeName ?? "";
    message.channel = object.channel ?? 0;
    return message;
  },
};

function createBaseNodeHighlight(): NodeHighlight {
  return { chatSwitch: false, positionSwitch: false, telemetrySwitch: false, iaqSwitch: false, nodeName: "" };
}

export const NodeHighlight = {
  encode(message: NodeHighlight, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chatSwitch !== false) {
      writer.uint32(8).bool(message.chatSwitch);
    }
    if (message.positionSwitch !== false) {
      writer.uint32(16).bool(message.positionSwitch);
    }
    if (message.telemetrySwitch !== false) {
      writer.uint32(24).bool(message.telemetrySwitch);
    }
    if (message.iaqSwitch !== false) {
      writer.uint32(32).bool(message.iaqSwitch);
    }
    if (message.nodeName !== "") {
      writer.uint32(42).string(message.nodeName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeHighlight {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeHighlight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.chatSwitch = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.positionSwitch = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.telemetrySwitch = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.iaqSwitch = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.nodeName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeHighlight {
    return {
      chatSwitch: isSet(object.chatSwitch) ? globalThis.Boolean(object.chatSwitch) : false,
      positionSwitch: isSet(object.positionSwitch) ? globalThis.Boolean(object.positionSwitch) : false,
      telemetrySwitch: isSet(object.telemetrySwitch) ? globalThis.Boolean(object.telemetrySwitch) : false,
      iaqSwitch: isSet(object.iaqSwitch) ? globalThis.Boolean(object.iaqSwitch) : false,
      nodeName: isSet(object.nodeName) ? globalThis.String(object.nodeName) : "",
    };
  },

  toJSON(message: NodeHighlight): unknown {
    const obj: any = {};
    if (message.chatSwitch !== false) {
      obj.chatSwitch = message.chatSwitch;
    }
    if (message.positionSwitch !== false) {
      obj.positionSwitch = message.positionSwitch;
    }
    if (message.telemetrySwitch !== false) {
      obj.telemetrySwitch = message.telemetrySwitch;
    }
    if (message.iaqSwitch !== false) {
      obj.iaqSwitch = message.iaqSwitch;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeHighlight>, I>>(base?: I): NodeHighlight {
    return NodeHighlight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeHighlight>, I>>(object: I): NodeHighlight {
    const message = createBaseNodeHighlight();
    message.chatSwitch = object.chatSwitch ?? false;
    message.positionSwitch = object.positionSwitch ?? false;
    message.telemetrySwitch = object.telemetrySwitch ?? false;
    message.iaqSwitch = object.iaqSwitch ?? false;
    message.nodeName = object.nodeName ?? "";
    return message;
  },
};

function createBaseGeoPoint(): GeoPoint {
  return { zoom: 0, latitude: 0, longitude: 0 };
}

export const GeoPoint = {
  encode(message: GeoPoint, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.zoom !== 0) {
      writer.uint32(8).int32(message.zoom);
    }
    if (message.latitude !== 0) {
      writer.uint32(16).int32(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(24).int32(message.longitude);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GeoPoint {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoPoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.zoom = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.latitude = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.longitude = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoPoint {
    return {
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0,
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: GeoPoint): unknown {
    const obj: any = {};
    if (message.zoom !== 0) {
      obj.zoom = Math.round(message.zoom);
    }
    if (message.latitude !== 0) {
      obj.latitude = Math.round(message.latitude);
    }
    if (message.longitude !== 0) {
      obj.longitude = Math.round(message.longitude);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GeoPoint>, I>>(base?: I): GeoPoint {
    return GeoPoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GeoPoint>, I>>(object: I): GeoPoint {
    const message = createBaseGeoPoint();
    message.zoom = object.zoom ?? 0;
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBaseMap(): Map {
  return { home: undefined, style: "", followGps: false };
}

export const Map = {
  encode(message: Map, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.home !== undefined) {
      GeoPoint.encode(message.home, writer.uint32(10).fork()).ldelim();
    }
    if (message.style !== "") {
      writer.uint32(18).string(message.style);
    }
    if (message.followGps !== false) {
      writer.uint32(24).bool(message.followGps);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Map {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMap();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.home = GeoPoint.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.style = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.followGps = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Map {
    return {
      home: isSet(object.home) ? GeoPoint.fromJSON(object.home) : undefined,
      style: isSet(object.style) ? globalThis.String(object.style) : "",
      followGps: isSet(object.followGps) ? globalThis.Boolean(object.followGps) : false,
    };
  },

  toJSON(message: Map): unknown {
    const obj: any = {};
    if (message.home !== undefined) {
      obj.home = GeoPoint.toJSON(message.home);
    }
    if (message.style !== "") {
      obj.style = message.style;
    }
    if (message.followGps !== false) {
      obj.followGps = message.followGps;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Map>, I>>(base?: I): Map {
    return Map.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Map>, I>>(object: I): Map {
    const message = createBaseMap();
    message.home = (object.home !== undefined && object.home !== null) ? GeoPoint.fromPartial(object.home) : undefined;
    message.style = object.style ?? "";
    message.followGps = object.followGps ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
