// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/deviceonly.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Channel } from "./channel";
import { Config_DeviceConfig_Role, config_DeviceConfig_RoleFromJSON, config_DeviceConfig_RoleToJSON } from "./config";
import { LocalConfig, LocalModuleConfig } from "./localonly";
import {
  HardwareModel,
  hardwareModelFromJSON,
  hardwareModelToJSON,
  MeshPacket,
  MyNodeInfo,
  NodeRemoteHardwarePin,
  Position_LocSource,
  position_LocSourceFromJSON,
  position_LocSourceToJSON,
  StatusMessage,
  User,
} from "./mesh";
import { DeviceMetrics, EnvironmentMetrics } from "./telemetry";

/** Position with static location information only for NodeDBLite */
export interface PositionLite {
  /**
   * The new preferred location encoding, multiply by 1e-7 to get degrees
   * in floating point
   */
  latitudeI: number;
  /** TODO: REPLACE */
  longitudeI: number;
  /** In meters above MSL (but see issue #359) */
  altitude: number;
  /**
   * This is usually not sent over the mesh (to save space), but it is sent
   * from the phone so that the local device can set its RTC If it is sent over
   * the mesh (because there are devices on the mesh without GPS), it will only
   * be sent by devices which has a hardware GPS clock.
   * seconds since 1970
   */
  time: number;
  /** TODO: REPLACE */
  locationSource: Position_LocSource;
  /** Indicates the bits of precision set by the sending node */
  precisionBits: number;
}

export interface UserLite {
  /**
   * This is the addr of the radio.
   *
   * @deprecated
   */
  macaddr: Uint8Array;
  /** A full name for this user, i.e. "Kevin Hester" */
  longName: string;
  /**
   * A VERY short name, ideally two characters.
   * Suitable for a tiny OLED screen
   */
  shortName: string;
  /**
   * TBEAM, HELTEC, etc...
   * Starting in 1.2.11 moved to hw_model enum in the NodeInfo object.
   * Apps will still need the string here for older builds
   * (so OTA update can find the right image), but if the enum is available it will be used instead.
   */
  hwModel: HardwareModel;
  /**
   * In some regions Ham radio operators have different bandwidth limitations than others.
   * If this user is a licensed operator, set this flag.
   * Also, "long_name" should be their licence number.
   */
  isLicensed: boolean;
  /** Indicates that the user's role in the mesh */
  role: Config_DeviceConfig_Role;
  /**
   * The public key of the user's device.
   * This is sent out to other nodes on the mesh to allow them to compute a shared secret key.
   */
  publicKey: Uint8Array;
  /** Whether or not the node can be messaged */
  isUnmessagable?: boolean | undefined;
}

export interface NodeInfoLite {
  /** The node number */
  num: number;
  /**
   * In-memory SNR of the last received message in dB. Not serialised directly:
   * always zeroed before encode; persisted as snr_q4 = 19 below.
   */
  snr: number;
  /** Set to indicate the last time we received a packet from this node */
  lastHeard: number;
  /** local channel index we heard that node on. Only populated if its not the default channel. */
  channel: number;
  /** Number of hops away from us this node is (0 if direct neighbor) */
  hopsAway?:
    | number
    | undefined;
  /** Last byte of the node number of the node that should be used as the next hop to reach this node. */
  nextHop: number;
  /** Bitfield for storing booleans. See NODEINFO_BITFIELD_* in src/mesh/NodeDB.h. */
  bitfield: number;
  /** A full name for this user, i.e. "Kevin Hester". */
  longName: string;
  /**
   * A VERY short name, ideally two characters or an emoji.
   * Suitable for a tiny OLED screen.
   */
  shortName: string;
  /** Hardware model the user's device is running. */
  hwModel: HardwareModel;
  /** The user's role in the mesh. */
  role: Config_DeviceConfig_Role;
  /** The public key of the user's device, for PKI-based encrypted DMs. */
  publicKey: Uint8Array;
  /**
   * Q4-encoded SNR: dB × 4, sint32 zigzag. Matches RouteDiscovery convention.
   * Encode: snr_q4 = (int32_t)(snr * 4.0f). Decode: snr = snr_q4 / 4.0f.
   * float snr is always zeroed on disk; this field carries all persisted SNR.
   */
  snrQ4: number;
}

/**
 * This message is never sent over the wire, but it is used for serializing DB
 * state to flash in the device code
 * FIXME, since we write this each time we enter deep sleep (and have infinite
 * flash) it would be better to use some sort of append only data structure for
 * the receive queue and use the preferences store for the other stuff
 */
export interface DeviceState {
  /** Read only settings/info about this node */
  myNode:
    | MyNodeInfo
    | undefined;
  /** My owner info */
  owner:
    | User
    | undefined;
  /** Received packets saved for delivery to the phone */
  receiveQueue: MeshPacket[];
  /**
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  version: number;
  /**
   * We keep the last received text message (only) stored in the device flash,
   * so we can show it on the screen.
   * Might be null
   */
  rxTextMessage:
    | MeshPacket
    | undefined;
  /**
   * Used only during development.
   * Indicates developer is testing and changes should never be saved to flash.
   * Deprecated in 2.3.1
   *
   * @deprecated
   */
  noSave: boolean;
  /**
   * Previously used to manage GPS factory resets.
   * Deprecated in 2.5.23
   *
   * @deprecated
   */
  didGpsReset: boolean;
  /**
   * We keep the last received waypoint stored in the device flash,
   * so we can show it on the screen.
   * Might be null
   */
  rxWaypoint:
    | MeshPacket
    | undefined;
  /** The mesh's nodes with their available gpio pins for RemoteHardware module */
  nodeRemoteHardwarePins: NodeRemoteHardwarePin[];
}

export interface NodePositionEntry {
  num: number;
  position: PositionLite | undefined;
}

export interface NodeTelemetryEntry {
  num: number;
  deviceMetrics: DeviceMetrics | undefined;
}

export interface NodeEnvironmentEntry {
  num: number;
  environmentMetrics: EnvironmentMetrics | undefined;
}

export interface NodeStatusEntry {
  num: number;
  status: StatusMessage | undefined;
}

export interface NodeDatabase {
  /**
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  version: number;
  /** New lite version of NodeDB to decrease memory footprint */
  nodes: NodeInfoLite[];
  /**
   * Per-NodeNum satellite arrays. Constrained platforms (e.g. STM32WL) omit
   * these via MESHTASTIC_EXCLUDE_*DB build flags.
   */
  positions: NodePositionEntry[];
  telemetry: NodeTelemetryEntry[];
  status: NodeStatusEntry[];
  environment: NodeEnvironmentEntry[];
}

/** The on-disk saved channels */
export interface ChannelFile {
  /** The channels our node knows about */
  channels: Channel[];
  /**
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  version: number;
}

/** The on-disk backup of the node's preferences */
export interface BackupPreferences {
  /** The version of the backup */
  version: number;
  /** The timestamp of the backup (if node has time) */
  timestamp: number;
  /** The node's configuration */
  config:
    | LocalConfig
    | undefined;
  /** The node's module configuration */
  moduleConfig:
    | LocalModuleConfig
    | undefined;
  /** The node's channels */
  channels:
    | ChannelFile
    | undefined;
  /** The node's user (owner) information */
  owner: User | undefined;
}

function createBasePositionLite(): PositionLite {
  return { latitudeI: 0, longitudeI: 0, altitude: 0, time: 0, locationSource: 0, precisionBits: 0 };
}

export const PositionLite = {
  encode(message: PositionLite, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.latitudeI !== 0) {
      writer.uint32(13).sfixed32(message.latitudeI);
    }
    if (message.longitudeI !== 0) {
      writer.uint32(21).sfixed32(message.longitudeI);
    }
    if (message.altitude !== 0) {
      writer.uint32(24).int32(message.altitude);
    }
    if (message.time !== 0) {
      writer.uint32(37).fixed32(message.time);
    }
    if (message.locationSource !== 0) {
      writer.uint32(40).int32(message.locationSource);
    }
    if (message.precisionBits !== 0) {
      writer.uint32(48).uint32(message.precisionBits);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PositionLite {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePositionLite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.latitudeI = reader.sfixed32();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.longitudeI = reader.sfixed32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.altitude = reader.int32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.time = reader.fixed32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.locationSource = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.precisionBits = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PositionLite {
    return {
      latitudeI: isSet(object.latitudeI) ? globalThis.Number(object.latitudeI) : 0,
      longitudeI: isSet(object.longitudeI) ? globalThis.Number(object.longitudeI) : 0,
      altitude: isSet(object.altitude) ? globalThis.Number(object.altitude) : 0,
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      locationSource: isSet(object.locationSource) ? position_LocSourceFromJSON(object.locationSource) : 0,
      precisionBits: isSet(object.precisionBits) ? globalThis.Number(object.precisionBits) : 0,
    };
  },

  toJSON(message: PositionLite): unknown {
    const obj: any = {};
    if (message.latitudeI !== 0) {
      obj.latitudeI = Math.round(message.latitudeI);
    }
    if (message.longitudeI !== 0) {
      obj.longitudeI = Math.round(message.longitudeI);
    }
    if (message.altitude !== 0) {
      obj.altitude = Math.round(message.altitude);
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.locationSource !== 0) {
      obj.locationSource = position_LocSourceToJSON(message.locationSource);
    }
    if (message.precisionBits !== 0) {
      obj.precisionBits = Math.round(message.precisionBits);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PositionLite>, I>>(base?: I): PositionLite {
    return PositionLite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PositionLite>, I>>(object: I): PositionLite {
    const message = createBasePositionLite();
    message.latitudeI = object.latitudeI ?? 0;
    message.longitudeI = object.longitudeI ?? 0;
    message.altitude = object.altitude ?? 0;
    message.time = object.time ?? 0;
    message.locationSource = object.locationSource ?? 0;
    message.precisionBits = object.precisionBits ?? 0;
    return message;
  },
};

function createBaseUserLite(): UserLite {
  return {
    macaddr: new Uint8Array(0),
    longName: "",
    shortName: "",
    hwModel: 0,
    isLicensed: false,
    role: 0,
    publicKey: new Uint8Array(0),
    isUnmessagable: undefined,
  };
}

export const UserLite = {
  encode(message: UserLite, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.macaddr.length !== 0) {
      writer.uint32(10).bytes(message.macaddr);
    }
    if (message.longName !== "") {
      writer.uint32(18).string(message.longName);
    }
    if (message.shortName !== "") {
      writer.uint32(26).string(message.shortName);
    }
    if (message.hwModel !== 0) {
      writer.uint32(32).int32(message.hwModel);
    }
    if (message.isLicensed !== false) {
      writer.uint32(40).bool(message.isLicensed);
    }
    if (message.role !== 0) {
      writer.uint32(48).int32(message.role);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(58).bytes(message.publicKey);
    }
    if (message.isUnmessagable !== undefined) {
      writer.uint32(72).bool(message.isUnmessagable);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserLite {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserLite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.macaddr = reader.bytes();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.longName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.shortName = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.hwModel = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.isLicensed = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.isUnmessagable = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserLite {
    return {
      macaddr: isSet(object.macaddr) ? bytesFromBase64(object.macaddr) : new Uint8Array(0),
      longName: isSet(object.longName) ? globalThis.String(object.longName) : "",
      shortName: isSet(object.shortName) ? globalThis.String(object.shortName) : "",
      hwModel: isSet(object.hwModel) ? hardwareModelFromJSON(object.hwModel) : 0,
      isLicensed: isSet(object.isLicensed) ? globalThis.Boolean(object.isLicensed) : false,
      role: isSet(object.role) ? config_DeviceConfig_RoleFromJSON(object.role) : 0,
      publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0),
      isUnmessagable: isSet(object.isUnmessagable) ? globalThis.Boolean(object.isUnmessagable) : undefined,
    };
  },

  toJSON(message: UserLite): unknown {
    const obj: any = {};
    if (message.macaddr.length !== 0) {
      obj.macaddr = base64FromBytes(message.macaddr);
    }
    if (message.longName !== "") {
      obj.longName = message.longName;
    }
    if (message.shortName !== "") {
      obj.shortName = message.shortName;
    }
    if (message.hwModel !== 0) {
      obj.hwModel = hardwareModelToJSON(message.hwModel);
    }
    if (message.isLicensed !== false) {
      obj.isLicensed = message.isLicensed;
    }
    if (message.role !== 0) {
      obj.role = config_DeviceConfig_RoleToJSON(message.role);
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.isUnmessagable !== undefined) {
      obj.isUnmessagable = message.isUnmessagable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserLite>, I>>(base?: I): UserLite {
    return UserLite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserLite>, I>>(object: I): UserLite {
    const message = createBaseUserLite();
    message.macaddr = object.macaddr ?? new Uint8Array(0);
    message.longName = object.longName ?? "";
    message.shortName = object.shortName ?? "";
    message.hwModel = object.hwModel ?? 0;
    message.isLicensed = object.isLicensed ?? false;
    message.role = object.role ?? 0;
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.isUnmessagable = object.isUnmessagable ?? undefined;
    return message;
  },
};

function createBaseNodeInfoLite(): NodeInfoLite {
  return {
    num: 0,
    snr: 0,
    lastHeard: 0,
    channel: 0,
    hopsAway: undefined,
    nextHop: 0,
    bitfield: 0,
    longName: "",
    shortName: "",
    hwModel: 0,
    role: 0,
    publicKey: new Uint8Array(0),
    snrQ4: 0,
  };
}

export const NodeInfoLite = {
  encode(message: NodeInfoLite, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.snr !== 0) {
      writer.uint32(37).float(message.snr);
    }
    if (message.lastHeard !== 0) {
      writer.uint32(45).fixed32(message.lastHeard);
    }
    if (message.channel !== 0) {
      writer.uint32(56).uint32(message.channel);
    }
    if (message.hopsAway !== undefined) {
      writer.uint32(72).uint32(message.hopsAway);
    }
    if (message.nextHop !== 0) {
      writer.uint32(96).uint32(message.nextHop);
    }
    if (message.bitfield !== 0) {
      writer.uint32(104).uint32(message.bitfield);
    }
    if (message.longName !== "") {
      writer.uint32(114).string(message.longName);
    }
    if (message.shortName !== "") {
      writer.uint32(122).string(message.shortName);
    }
    if (message.hwModel !== 0) {
      writer.uint32(128).int32(message.hwModel);
    }
    if (message.role !== 0) {
      writer.uint32(136).int32(message.role);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(146).bytes(message.publicKey);
    }
    if (message.snrQ4 !== 0) {
      writer.uint32(152).sint32(message.snrQ4);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeInfoLite {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeInfoLite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.snr = reader.float();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.lastHeard = reader.fixed32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.channel = reader.uint32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.hopsAway = reader.uint32();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.nextHop = reader.uint32();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.bitfield = reader.uint32();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.longName = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.shortName = reader.string();
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.hwModel = reader.int32() as any;
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        case 19:
          if (tag !== 152) {
            break;
          }

          message.snrQ4 = reader.sint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeInfoLite {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      snr: isSet(object.snr) ? globalThis.Number(object.snr) : 0,
      lastHeard: isSet(object.lastHeard) ? globalThis.Number(object.lastHeard) : 0,
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
      hopsAway: isSet(object.hopsAway) ? globalThis.Number(object.hopsAway) : undefined,
      nextHop: isSet(object.nextHop) ? globalThis.Number(object.nextHop) : 0,
      bitfield: isSet(object.bitfield) ? globalThis.Number(object.bitfield) : 0,
      longName: isSet(object.longName) ? globalThis.String(object.longName) : "",
      shortName: isSet(object.shortName) ? globalThis.String(object.shortName) : "",
      hwModel: isSet(object.hwModel) ? hardwareModelFromJSON(object.hwModel) : 0,
      role: isSet(object.role) ? config_DeviceConfig_RoleFromJSON(object.role) : 0,
      publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0),
      snrQ4: isSet(object.snrQ4) ? globalThis.Number(object.snrQ4) : 0,
    };
  },

  toJSON(message: NodeInfoLite): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.snr !== 0) {
      obj.snr = message.snr;
    }
    if (message.lastHeard !== 0) {
      obj.lastHeard = Math.round(message.lastHeard);
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    if (message.hopsAway !== undefined) {
      obj.hopsAway = Math.round(message.hopsAway);
    }
    if (message.nextHop !== 0) {
      obj.nextHop = Math.round(message.nextHop);
    }
    if (message.bitfield !== 0) {
      obj.bitfield = Math.round(message.bitfield);
    }
    if (message.longName !== "") {
      obj.longName = message.longName;
    }
    if (message.shortName !== "") {
      obj.shortName = message.shortName;
    }
    if (message.hwModel !== 0) {
      obj.hwModel = hardwareModelToJSON(message.hwModel);
    }
    if (message.role !== 0) {
      obj.role = config_DeviceConfig_RoleToJSON(message.role);
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.snrQ4 !== 0) {
      obj.snrQ4 = Math.round(message.snrQ4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeInfoLite>, I>>(base?: I): NodeInfoLite {
    return NodeInfoLite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeInfoLite>, I>>(object: I): NodeInfoLite {
    const message = createBaseNodeInfoLite();
    message.num = object.num ?? 0;
    message.snr = object.snr ?? 0;
    message.lastHeard = object.lastHeard ?? 0;
    message.channel = object.channel ?? 0;
    message.hopsAway = object.hopsAway ?? undefined;
    message.nextHop = object.nextHop ?? 0;
    message.bitfield = object.bitfield ?? 0;
    message.longName = object.longName ?? "";
    message.shortName = object.shortName ?? "";
    message.hwModel = object.hwModel ?? 0;
    message.role = object.role ?? 0;
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.snrQ4 = object.snrQ4 ?? 0;
    return message;
  },
};

function createBaseDeviceState(): DeviceState {
  return {
    myNode: undefined,
    owner: undefined,
    receiveQueue: [],
    version: 0,
    rxTextMessage: undefined,
    noSave: false,
    didGpsReset: false,
    rxWaypoint: undefined,
    nodeRemoteHardwarePins: [],
  };
}

export const DeviceState = {
  encode(message: DeviceState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.myNode !== undefined) {
      MyNodeInfo.encode(message.myNode, writer.uint32(18).fork()).ldelim();
    }
    if (message.owner !== undefined) {
      User.encode(message.owner, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.receiveQueue) {
      MeshPacket.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    if (message.version !== 0) {
      writer.uint32(64).uint32(message.version);
    }
    if (message.rxTextMessage !== undefined) {
      MeshPacket.encode(message.rxTextMessage, writer.uint32(58).fork()).ldelim();
    }
    if (message.noSave !== false) {
      writer.uint32(72).bool(message.noSave);
    }
    if (message.didGpsReset !== false) {
      writer.uint32(88).bool(message.didGpsReset);
    }
    if (message.rxWaypoint !== undefined) {
      MeshPacket.encode(message.rxWaypoint, writer.uint32(98).fork()).ldelim();
    }
    for (const v of message.nodeRemoteHardwarePins) {
      NodeRemoteHardwarePin.encode(v!, writer.uint32(106).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeviceState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.myNode = MyNodeInfo.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.owner = User.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.receiveQueue.push(MeshPacket.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.rxTextMessage = MeshPacket.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.noSave = reader.bool();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.didGpsReset = reader.bool();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.rxWaypoint = MeshPacket.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.nodeRemoteHardwarePins.push(NodeRemoteHardwarePin.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceState {
    return {
      myNode: isSet(object.myNode) ? MyNodeInfo.fromJSON(object.myNode) : undefined,
      owner: isSet(object.owner) ? User.fromJSON(object.owner) : undefined,
      receiveQueue: globalThis.Array.isArray(object?.receiveQueue)
        ? object.receiveQueue.map((e: any) => MeshPacket.fromJSON(e))
        : [],
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      rxTextMessage: isSet(object.rxTextMessage) ? MeshPacket.fromJSON(object.rxTextMessage) : undefined,
      noSave: isSet(object.noSave) ? globalThis.Boolean(object.noSave) : false,
      didGpsReset: isSet(object.didGpsReset) ? globalThis.Boolean(object.didGpsReset) : false,
      rxWaypoint: isSet(object.rxWaypoint) ? MeshPacket.fromJSON(object.rxWaypoint) : undefined,
      nodeRemoteHardwarePins: globalThis.Array.isArray(object?.nodeRemoteHardwarePins)
        ? object.nodeRemoteHardwarePins.map((e: any) => NodeRemoteHardwarePin.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DeviceState): unknown {
    const obj: any = {};
    if (message.myNode !== undefined) {
      obj.myNode = MyNodeInfo.toJSON(message.myNode);
    }
    if (message.owner !== undefined) {
      obj.owner = User.toJSON(message.owner);
    }
    if (message.receiveQueue?.length) {
      obj.receiveQueue = message.receiveQueue.map((e) => MeshPacket.toJSON(e));
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.rxTextMessage !== undefined) {
      obj.rxTextMessage = MeshPacket.toJSON(message.rxTextMessage);
    }
    if (message.noSave !== false) {
      obj.noSave = message.noSave;
    }
    if (message.didGpsReset !== false) {
      obj.didGpsReset = message.didGpsReset;
    }
    if (message.rxWaypoint !== undefined) {
      obj.rxWaypoint = MeshPacket.toJSON(message.rxWaypoint);
    }
    if (message.nodeRemoteHardwarePins?.length) {
      obj.nodeRemoteHardwarePins = message.nodeRemoteHardwarePins.map((e) => NodeRemoteHardwarePin.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceState>, I>>(base?: I): DeviceState {
    return DeviceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceState>, I>>(object: I): DeviceState {
    const message = createBaseDeviceState();
    message.myNode = (object.myNode !== undefined && object.myNode !== null)
      ? MyNodeInfo.fromPartial(object.myNode)
      : undefined;
    message.owner = (object.owner !== undefined && object.owner !== null) ? User.fromPartial(object.owner) : undefined;
    message.receiveQueue = object.receiveQueue?.map((e) => MeshPacket.fromPartial(e)) || [];
    message.version = object.version ?? 0;
    message.rxTextMessage = (object.rxTextMessage !== undefined && object.rxTextMessage !== null)
      ? MeshPacket.fromPartial(object.rxTextMessage)
      : undefined;
    message.noSave = object.noSave ?? false;
    message.didGpsReset = object.didGpsReset ?? false;
    message.rxWaypoint = (object.rxWaypoint !== undefined && object.rxWaypoint !== null)
      ? MeshPacket.fromPartial(object.rxWaypoint)
      : undefined;
    message.nodeRemoteHardwarePins = object.nodeRemoteHardwarePins?.map((e) => NodeRemoteHardwarePin.fromPartial(e)) ||
      [];
    return message;
  },
};

function createBaseNodePositionEntry(): NodePositionEntry {
  return { num: 0, position: undefined };
}

export const NodePositionEntry = {
  encode(message: NodePositionEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.position !== undefined) {
      PositionLite.encode(message.position, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodePositionEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodePositionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.position = PositionLite.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodePositionEntry {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      position: isSet(object.position) ? PositionLite.fromJSON(object.position) : undefined,
    };
  },

  toJSON(message: NodePositionEntry): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.position !== undefined) {
      obj.position = PositionLite.toJSON(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodePositionEntry>, I>>(base?: I): NodePositionEntry {
    return NodePositionEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodePositionEntry>, I>>(object: I): NodePositionEntry {
    const message = createBaseNodePositionEntry();
    message.num = object.num ?? 0;
    message.position = (object.position !== undefined && object.position !== null)
      ? PositionLite.fromPartial(object.position)
      : undefined;
    return message;
  },
};

function createBaseNodeTelemetryEntry(): NodeTelemetryEntry {
  return { num: 0, deviceMetrics: undefined };
}

export const NodeTelemetryEntry = {
  encode(message: NodeTelemetryEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.deviceMetrics !== undefined) {
      DeviceMetrics.encode(message.deviceMetrics, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeTelemetryEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeTelemetryEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.deviceMetrics = DeviceMetrics.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeTelemetryEntry {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      deviceMetrics: isSet(object.deviceMetrics) ? DeviceMetrics.fromJSON(object.deviceMetrics) : undefined,
    };
  },

  toJSON(message: NodeTelemetryEntry): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.deviceMetrics !== undefined) {
      obj.deviceMetrics = DeviceMetrics.toJSON(message.deviceMetrics);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeTelemetryEntry>, I>>(base?: I): NodeTelemetryEntry {
    return NodeTelemetryEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeTelemetryEntry>, I>>(object: I): NodeTelemetryEntry {
    const message = createBaseNodeTelemetryEntry();
    message.num = object.num ?? 0;
    message.deviceMetrics = (object.deviceMetrics !== undefined && object.deviceMetrics !== null)
      ? DeviceMetrics.fromPartial(object.deviceMetrics)
      : undefined;
    return message;
  },
};

function createBaseNodeEnvironmentEntry(): NodeEnvironmentEntry {
  return { num: 0, environmentMetrics: undefined };
}

export const NodeEnvironmentEntry = {
  encode(message: NodeEnvironmentEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.environmentMetrics !== undefined) {
      EnvironmentMetrics.encode(message.environmentMetrics, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeEnvironmentEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeEnvironmentEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.environmentMetrics = EnvironmentMetrics.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeEnvironmentEntry {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      environmentMetrics: isSet(object.environmentMetrics)
        ? EnvironmentMetrics.fromJSON(object.environmentMetrics)
        : undefined,
    };
  },

  toJSON(message: NodeEnvironmentEntry): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.environmentMetrics !== undefined) {
      obj.environmentMetrics = EnvironmentMetrics.toJSON(message.environmentMetrics);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeEnvironmentEntry>, I>>(base?: I): NodeEnvironmentEntry {
    return NodeEnvironmentEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeEnvironmentEntry>, I>>(object: I): NodeEnvironmentEntry {
    const message = createBaseNodeEnvironmentEntry();
    message.num = object.num ?? 0;
    message.environmentMetrics = (object.environmentMetrics !== undefined && object.environmentMetrics !== null)
      ? EnvironmentMetrics.fromPartial(object.environmentMetrics)
      : undefined;
    return message;
  },
};

function createBaseNodeStatusEntry(): NodeStatusEntry {
  return { num: 0, status: undefined };
}

export const NodeStatusEntry = {
  encode(message: NodeStatusEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.status !== undefined) {
      StatusMessage.encode(message.status, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeStatusEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeStatusEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.status = StatusMessage.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeStatusEntry {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      status: isSet(object.status) ? StatusMessage.fromJSON(object.status) : undefined,
    };
  },

  toJSON(message: NodeStatusEntry): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.status !== undefined) {
      obj.status = StatusMessage.toJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeStatusEntry>, I>>(base?: I): NodeStatusEntry {
    return NodeStatusEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeStatusEntry>, I>>(object: I): NodeStatusEntry {
    const message = createBaseNodeStatusEntry();
    message.num = object.num ?? 0;
    message.status = (object.status !== undefined && object.status !== null)
      ? StatusMessage.fromPartial(object.status)
      : undefined;
    return message;
  },
};

function createBaseNodeDatabase(): NodeDatabase {
  return { version: 0, nodes: [], positions: [], telemetry: [], status: [], environment: [] };
}

export const NodeDatabase = {
  encode(message: NodeDatabase, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    for (const v of message.nodes) {
      NodeInfoLite.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.positions) {
      NodePositionEntry.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.telemetry) {
      NodeTelemetryEntry.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    for (const v of message.status) {
      NodeStatusEntry.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    for (const v of message.environment) {
      NodeEnvironmentEntry.encode(v!, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeDatabase {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeDatabase();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.nodes.push(NodeInfoLite.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.positions.push(NodePositionEntry.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.telemetry.push(NodeTelemetryEntry.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.status.push(NodeStatusEntry.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.environment.push(NodeEnvironmentEntry.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeDatabase {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => NodeInfoLite.fromJSON(e)) : [],
      positions: globalThis.Array.isArray(object?.positions)
        ? object.positions.map((e: any) => NodePositionEntry.fromJSON(e))
        : [],
      telemetry: globalThis.Array.isArray(object?.telemetry)
        ? object.telemetry.map((e: any) => NodeTelemetryEntry.fromJSON(e))
        : [],
      status: globalThis.Array.isArray(object?.status)
        ? object.status.map((e: any) => NodeStatusEntry.fromJSON(e))
        : [],
      environment: globalThis.Array.isArray(object?.environment)
        ? object.environment.map((e: any) => NodeEnvironmentEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: NodeDatabase): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => NodeInfoLite.toJSON(e));
    }
    if (message.positions?.length) {
      obj.positions = message.positions.map((e) => NodePositionEntry.toJSON(e));
    }
    if (message.telemetry?.length) {
      obj.telemetry = message.telemetry.map((e) => NodeTelemetryEntry.toJSON(e));
    }
    if (message.status?.length) {
      obj.status = message.status.map((e) => NodeStatusEntry.toJSON(e));
    }
    if (message.environment?.length) {
      obj.environment = message.environment.map((e) => NodeEnvironmentEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeDatabase>, I>>(base?: I): NodeDatabase {
    return NodeDatabase.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeDatabase>, I>>(object: I): NodeDatabase {
    const message = createBaseNodeDatabase();
    message.version = object.version ?? 0;
    message.nodes = object.nodes?.map((e) => NodeInfoLite.fromPartial(e)) || [];
    message.positions = object.positions?.map((e) => NodePositionEntry.fromPartial(e)) || [];
    message.telemetry = object.telemetry?.map((e) => NodeTelemetryEntry.fromPartial(e)) || [];
    message.status = object.status?.map((e) => NodeStatusEntry.fromPartial(e)) || [];
    message.environment = object.environment?.map((e) => NodeEnvironmentEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChannelFile(): ChannelFile {
  return { channels: [], version: 0 };
}

export const ChannelFile = {
  encode(message: ChannelFile, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.channels) {
      Channel.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.version !== 0) {
      writer.uint32(16).uint32(message.version);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ChannelFile {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.channels.push(Channel.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.version = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelFile {
    return {
      channels: globalThis.Array.isArray(object?.channels) ? object.channels.map((e: any) => Channel.fromJSON(e)) : [],
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: ChannelFile): unknown {
    const obj: any = {};
    if (message.channels?.length) {
      obj.channels = message.channels.map((e) => Channel.toJSON(e));
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelFile>, I>>(base?: I): ChannelFile {
    return ChannelFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelFile>, I>>(object: I): ChannelFile {
    const message = createBaseChannelFile();
    message.channels = object.channels?.map((e) => Channel.fromPartial(e)) || [];
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseBackupPreferences(): BackupPreferences {
  return {
    version: 0,
    timestamp: 0,
    config: undefined,
    moduleConfig: undefined,
    channels: undefined,
    owner: undefined,
  };
}

export const BackupPreferences = {
  encode(message: BackupPreferences, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    if (message.timestamp !== 0) {
      writer.uint32(21).fixed32(message.timestamp);
    }
    if (message.config !== undefined) {
      LocalConfig.encode(message.config, writer.uint32(26).fork()).ldelim();
    }
    if (message.moduleConfig !== undefined) {
      LocalModuleConfig.encode(message.moduleConfig, writer.uint32(34).fork()).ldelim();
    }
    if (message.channels !== undefined) {
      ChannelFile.encode(message.channels, writer.uint32(42).fork()).ldelim();
    }
    if (message.owner !== undefined) {
      User.encode(message.owner, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BackupPreferences {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBackupPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.timestamp = reader.fixed32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.config = LocalConfig.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.moduleConfig = LocalModuleConfig.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.channels = ChannelFile.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.owner = User.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BackupPreferences {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      config: isSet(object.config) ? LocalConfig.fromJSON(object.config) : undefined,
      moduleConfig: isSet(object.moduleConfig) ? LocalModuleConfig.fromJSON(object.moduleConfig) : undefined,
      channels: isSet(object.channels) ? ChannelFile.fromJSON(object.channels) : undefined,
      owner: isSet(object.owner) ? User.fromJSON(object.owner) : undefined,
    };
  },

  toJSON(message: BackupPreferences): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.config !== undefined) {
      obj.config = LocalConfig.toJSON(message.config);
    }
    if (message.moduleConfig !== undefined) {
      obj.moduleConfig = LocalModuleConfig.toJSON(message.moduleConfig);
    }
    if (message.channels !== undefined) {
      obj.channels = ChannelFile.toJSON(message.channels);
    }
    if (message.owner !== undefined) {
      obj.owner = User.toJSON(message.owner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BackupPreferences>, I>>(base?: I): BackupPreferences {
    return BackupPreferences.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BackupPreferences>, I>>(object: I): BackupPreferences {
    const message = createBaseBackupPreferences();
    message.version = object.version ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.config = (object.config !== undefined && object.config !== null)
      ? LocalConfig.fromPartial(object.config)
      : undefined;
    message.moduleConfig = (object.moduleConfig !== undefined && object.moduleConfig !== null)
      ? LocalModuleConfig.fromPartial(object.moduleConfig)
      : undefined;
    message.channels = (object.channels !== undefined && object.channels !== null)
      ? ChannelFile.fromPartial(object.channels)
      : undefined;
    message.owner = (object.owner !== undefined && object.owner !== null) ? User.fromPartial(object.owner) : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
