// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/deviceonly_legacy.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { PositionLite, UserLite } from "./deviceonly";
import { DeviceMetrics } from "./telemetry";

/**
 * Legacy NodeInfoLite descriptor used only to decode pre-split
 * /prefs/nodes.proto saves during the v24 -> v25 migration boot.
 * This preserves the original NodeInfoLite-compatible field numbers needed
 * to parse old wire bytes cleanly, including user (2), position (3),
 * device_metrics (6), and the legacy-only compatibility fields via_mqtt (8),
 * is_favorite (10), and is_ignored (11). Steady-state code does not use
 * this struct; it is dropped after migration completes. This file should be
 * removed once DEVICESTATE_MIN_VER advances past 24.
 */
export interface NodeInfoLiteLegacy {
  num: number;
  user: UserLite | undefined;
  position: PositionLite | undefined;
  snr: number;
  lastHeard: number;
  deviceMetrics: DeviceMetrics | undefined;
  channel: number;
  viaMqtt: boolean;
  hopsAway?: number | undefined;
  isFavorite: boolean;
  isIgnored: boolean;
  nextHop: number;
  bitfield: number;
}

/**
 * Legacy NodeDatabase shape: one repeated array of fat NodeInfoLite_Legacy
 * with no satellite position/telemetry arrays.
 */
export interface NodeDatabaseLegacy {
  version: number;
  nodes: NodeInfoLiteLegacy[];
}

function createBaseNodeInfoLiteLegacy(): NodeInfoLiteLegacy {
  return {
    num: 0,
    user: undefined,
    position: undefined,
    snr: 0,
    lastHeard: 0,
    deviceMetrics: undefined,
    channel: 0,
    viaMqtt: false,
    hopsAway: undefined,
    isFavorite: false,
    isIgnored: false,
    nextHop: 0,
    bitfield: 0,
  };
}

export const NodeInfoLiteLegacy = {
  encode(message: NodeInfoLiteLegacy, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.num !== 0) {
      writer.uint32(8).uint32(message.num);
    }
    if (message.user !== undefined) {
      UserLite.encode(message.user, writer.uint32(18).fork()).ldelim();
    }
    if (message.position !== undefined) {
      PositionLite.encode(message.position, writer.uint32(26).fork()).ldelim();
    }
    if (message.snr !== 0) {
      writer.uint32(37).float(message.snr);
    }
    if (message.lastHeard !== 0) {
      writer.uint32(45).fixed32(message.lastHeard);
    }
    if (message.deviceMetrics !== undefined) {
      DeviceMetrics.encode(message.deviceMetrics, writer.uint32(50).fork()).ldelim();
    }
    if (message.channel !== 0) {
      writer.uint32(56).uint32(message.channel);
    }
    if (message.viaMqtt !== false) {
      writer.uint32(64).bool(message.viaMqtt);
    }
    if (message.hopsAway !== undefined) {
      writer.uint32(72).uint32(message.hopsAway);
    }
    if (message.isFavorite !== false) {
      writer.uint32(80).bool(message.isFavorite);
    }
    if (message.isIgnored !== false) {
      writer.uint32(88).bool(message.isIgnored);
    }
    if (message.nextHop !== 0) {
      writer.uint32(96).uint32(message.nextHop);
    }
    if (message.bitfield !== 0) {
      writer.uint32(104).uint32(message.bitfield);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeInfoLiteLegacy {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeInfoLiteLegacy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.num = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.user = UserLite.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.position = PositionLite.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.snr = reader.float();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.lastHeard = reader.fixed32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.deviceMetrics = DeviceMetrics.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.channel = reader.uint32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.viaMqtt = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.hopsAway = reader.uint32();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.isFavorite = reader.bool();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.isIgnored = reader.bool();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.nextHop = reader.uint32();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.bitfield = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeInfoLiteLegacy {
    return {
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
      user: isSet(object.user) ? UserLite.fromJSON(object.user) : undefined,
      position: isSet(object.position) ? PositionLite.fromJSON(object.position) : undefined,
      snr: isSet(object.snr) ? globalThis.Number(object.snr) : 0,
      lastHeard: isSet(object.lastHeard) ? globalThis.Number(object.lastHeard) : 0,
      deviceMetrics: isSet(object.deviceMetrics) ? DeviceMetrics.fromJSON(object.deviceMetrics) : undefined,
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
      viaMqtt: isSet(object.viaMqtt) ? globalThis.Boolean(object.viaMqtt) : false,
      hopsAway: isSet(object.hopsAway) ? globalThis.Number(object.hopsAway) : undefined,
      isFavorite: isSet(object.isFavorite) ? globalThis.Boolean(object.isFavorite) : false,
      isIgnored: isSet(object.isIgnored) ? globalThis.Boolean(object.isIgnored) : false,
      nextHop: isSet(object.nextHop) ? globalThis.Number(object.nextHop) : 0,
      bitfield: isSet(object.bitfield) ? globalThis.Number(object.bitfield) : 0,
    };
  },

  toJSON(message: NodeInfoLiteLegacy): unknown {
    const obj: any = {};
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    if (message.user !== undefined) {
      obj.user = UserLite.toJSON(message.user);
    }
    if (message.position !== undefined) {
      obj.position = PositionLite.toJSON(message.position);
    }
    if (message.snr !== 0) {
      obj.snr = message.snr;
    }
    if (message.lastHeard !== 0) {
      obj.lastHeard = Math.round(message.lastHeard);
    }
    if (message.deviceMetrics !== undefined) {
      obj.deviceMetrics = DeviceMetrics.toJSON(message.deviceMetrics);
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    if (message.viaMqtt !== false) {
      obj.viaMqtt = message.viaMqtt;
    }
    if (message.hopsAway !== undefined) {
      obj.hopsAway = Math.round(message.hopsAway);
    }
    if (message.isFavorite !== false) {
      obj.isFavorite = message.isFavorite;
    }
    if (message.isIgnored !== false) {
      obj.isIgnored = message.isIgnored;
    }
    if (message.nextHop !== 0) {
      obj.nextHop = Math.round(message.nextHop);
    }
    if (message.bitfield !== 0) {
      obj.bitfield = Math.round(message.bitfield);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeInfoLiteLegacy>, I>>(base?: I): NodeInfoLiteLegacy {
    return NodeInfoLiteLegacy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeInfoLiteLegacy>, I>>(object: I): NodeInfoLiteLegacy {
    const message = createBaseNodeInfoLiteLegacy();
    message.num = object.num ?? 0;
    message.user = (object.user !== undefined && object.user !== null) ? UserLite.fromPartial(object.user) : undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? PositionLite.fromPartial(object.position)
      : undefined;
    message.snr = object.snr ?? 0;
    message.lastHeard = object.lastHeard ?? 0;
    message.deviceMetrics = (object.deviceMetrics !== undefined && object.deviceMetrics !== null)
      ? DeviceMetrics.fromPartial(object.deviceMetrics)
      : undefined;
    message.channel = object.channel ?? 0;
    message.viaMqtt = object.viaMqtt ?? false;
    message.hopsAway = object.hopsAway ?? undefined;
    message.isFavorite = object.isFavorite ?? false;
    message.isIgnored = object.isIgnored ?? false;
    message.nextHop = object.nextHop ?? 0;
    message.bitfield = object.bitfield ?? 0;
    return message;
  },
};

function createBaseNodeDatabaseLegacy(): NodeDatabaseLegacy {
  return { version: 0, nodes: [] };
}

export const NodeDatabaseLegacy = {
  encode(message: NodeDatabaseLegacy, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    for (const v of message.nodes) {
      NodeInfoLiteLegacy.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): NodeDatabaseLegacy {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeDatabaseLegacy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.nodes.push(NodeInfoLiteLegacy.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeDatabaseLegacy {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      nodes: globalThis.Array.isArray(object?.nodes)
        ? object.nodes.map((e: any) => NodeInfoLiteLegacy.fromJSON(e))
        : [],
    };
  },

  toJSON(message: NodeDatabaseLegacy): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => NodeInfoLiteLegacy.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeDatabaseLegacy>, I>>(base?: I): NodeDatabaseLegacy {
    return NodeDatabaseLegacy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeDatabaseLegacy>, I>>(object: I): NodeDatabaseLegacy {
    const message = createBaseNodeDatabaseLegacy();
    message.version = object.version ?? 0;
    message.nodes = object.nodes?.map((e) => NodeInfoLiteLegacy.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
