// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/interdevice.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export enum MessageType {
  ACK = 0,
  /** COLLECT_INTERVAL - in ms */
  COLLECT_INTERVAL = 160,
  /** BEEP_ON - duration ms */
  BEEP_ON = 161,
  /** BEEP_OFF - cancel prematurely */
  BEEP_OFF = 162,
  SHUTDOWN = 163,
  POWER_ON = 164,
  SCD41_TEMP = 176,
  SCD41_HUMIDITY = 177,
  SCD41_CO2 = 178,
  AHT20_TEMP = 179,
  AHT20_HUMIDITY = 180,
  TVOC_INDEX = 181,
  UNRECOGNIZED = -1,
}

export function messageTypeFromJSON(object: any): MessageType {
  switch (object) {
    case 0:
    case "ACK":
      return MessageType.ACK;
    case 160:
    case "COLLECT_INTERVAL":
      return MessageType.COLLECT_INTERVAL;
    case 161:
    case "BEEP_ON":
      return MessageType.BEEP_ON;
    case 162:
    case "BEEP_OFF":
      return MessageType.BEEP_OFF;
    case 163:
    case "SHUTDOWN":
      return MessageType.SHUTDOWN;
    case 164:
    case "POWER_ON":
      return MessageType.POWER_ON;
    case 176:
    case "SCD41_TEMP":
      return MessageType.SCD41_TEMP;
    case 177:
    case "SCD41_HUMIDITY":
      return MessageType.SCD41_HUMIDITY;
    case 178:
    case "SCD41_CO2":
      return MessageType.SCD41_CO2;
    case 179:
    case "AHT20_TEMP":
      return MessageType.AHT20_TEMP;
    case 180:
    case "AHT20_HUMIDITY":
      return MessageType.AHT20_HUMIDITY;
    case 181:
    case "TVOC_INDEX":
      return MessageType.TVOC_INDEX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageType.UNRECOGNIZED;
  }
}

export function messageTypeToJSON(object: MessageType): string {
  switch (object) {
    case MessageType.ACK:
      return "ACK";
    case MessageType.COLLECT_INTERVAL:
      return "COLLECT_INTERVAL";
    case MessageType.BEEP_ON:
      return "BEEP_ON";
    case MessageType.BEEP_OFF:
      return "BEEP_OFF";
    case MessageType.SHUTDOWN:
      return "SHUTDOWN";
    case MessageType.POWER_ON:
      return "POWER_ON";
    case MessageType.SCD41_TEMP:
      return "SCD41_TEMP";
    case MessageType.SCD41_HUMIDITY:
      return "SCD41_HUMIDITY";
    case MessageType.SCD41_CO2:
      return "SCD41_CO2";
    case MessageType.AHT20_TEMP:
      return "AHT20_TEMP";
    case MessageType.AHT20_HUMIDITY:
      return "AHT20_HUMIDITY";
    case MessageType.TVOC_INDEX:
      return "TVOC_INDEX";
    case MessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SensorData {
  /** The message type */
  type: MessageType;
  floatValue?: number | undefined;
  uint32Value?: number | undefined;
}

export interface InterdeviceMessage {
  nmea?: string | undefined;
  sensor?: SensorData | undefined;
}

function createBaseSensorData(): SensorData {
  return { type: 0, floatValue: undefined, uint32Value: undefined };
}

export const SensorData = {
  encode(message: SensorData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.floatValue !== undefined) {
      writer.uint32(21).float(message.floatValue);
    }
    if (message.uint32Value !== undefined) {
      writer.uint32(24).uint32(message.uint32Value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SensorData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.floatValue = reader.float();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.uint32Value = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SensorData {
    return {
      type: isSet(object.type) ? messageTypeFromJSON(object.type) : 0,
      floatValue: isSet(object.floatValue) ? globalThis.Number(object.floatValue) : undefined,
      uint32Value: isSet(object.uint32Value) ? globalThis.Number(object.uint32Value) : undefined,
    };
  },

  toJSON(message: SensorData): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = messageTypeToJSON(message.type);
    }
    if (message.floatValue !== undefined) {
      obj.floatValue = message.floatValue;
    }
    if (message.uint32Value !== undefined) {
      obj.uint32Value = Math.round(message.uint32Value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SensorData>, I>>(base?: I): SensorData {
    return SensorData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SensorData>, I>>(object: I): SensorData {
    const message = createBaseSensorData();
    message.type = object.type ?? 0;
    message.floatValue = object.floatValue ?? undefined;
    message.uint32Value = object.uint32Value ?? undefined;
    return message;
  },
};

function createBaseInterdeviceMessage(): InterdeviceMessage {
  return { nmea: undefined, sensor: undefined };
}

export const InterdeviceMessage = {
  encode(message: InterdeviceMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.nmea !== undefined) {
      writer.uint32(10).string(message.nmea);
    }
    if (message.sensor !== undefined) {
      SensorData.encode(message.sensor, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): InterdeviceMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInterdeviceMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.nmea = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.sensor = SensorData.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InterdeviceMessage {
    return {
      nmea: isSet(object.nmea) ? globalThis.String(object.nmea) : undefined,
      sensor: isSet(object.sensor) ? SensorData.fromJSON(object.sensor) : undefined,
    };
  },

  toJSON(message: InterdeviceMessage): unknown {
    const obj: any = {};
    if (message.nmea !== undefined) {
      obj.nmea = message.nmea;
    }
    if (message.sensor !== undefined) {
      obj.sensor = SensorData.toJSON(message.sensor);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InterdeviceMessage>, I>>(base?: I): InterdeviceMessage {
    return InterdeviceMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InterdeviceMessage>, I>>(object: I): InterdeviceMessage {
    const message = createBaseInterdeviceMessage();
    message.nmea = object.nmea ?? undefined;
    message.sensor = (object.sensor !== undefined && object.sensor !== null)
      ? SensorData.fromPartial(object.sensor)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
