// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/localonly.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import {
  Config_BluetoothConfig,
  Config_DeviceConfig,
  Config_DisplayConfig,
  Config_LoRaConfig,
  Config_NetworkConfig,
  Config_PositionConfig,
  Config_PowerConfig,
  Config_SecurityConfig,
} from "./config";
import {
  ModuleConfig_AmbientLightingConfig,
  ModuleConfig_AudioConfig,
  ModuleConfig_CannedMessageConfig,
  ModuleConfig_DetectionSensorConfig,
  ModuleConfig_ExternalNotificationConfig,
  ModuleConfig_MeshBeaconConfig,
  ModuleConfig_MQTTConfig,
  ModuleConfig_NeighborInfoConfig,
  ModuleConfig_PaxcounterConfig,
  ModuleConfig_RangeTestConfig,
  ModuleConfig_RemoteHardwareConfig,
  ModuleConfig_SerialConfig,
  ModuleConfig_StatusMessageConfig,
  ModuleConfig_StoreForwardConfig,
  ModuleConfig_TAKConfig,
  ModuleConfig_TelemetryConfig,
  ModuleConfig_TrafficManagementConfig,
} from "./module_config";

export interface LocalConfig {
  /** The part of the config that is specific to the Device */
  device:
    | Config_DeviceConfig
    | undefined;
  /** The part of the config that is specific to the GPS Position */
  position:
    | Config_PositionConfig
    | undefined;
  /** The part of the config that is specific to the Power settings */
  power:
    | Config_PowerConfig
    | undefined;
  /** The part of the config that is specific to the Wifi Settings */
  network:
    | Config_NetworkConfig
    | undefined;
  /** The part of the config that is specific to the Display */
  display:
    | Config_DisplayConfig
    | undefined;
  /** The part of the config that is specific to the Lora Radio */
  lora:
    | Config_LoRaConfig
    | undefined;
  /** The part of the config that is specific to the Bluetooth settings */
  bluetooth:
    | Config_BluetoothConfig
    | undefined;
  /**
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  version: number;
  /** The part of the config that is specific to Security settings */
  security: Config_SecurityConfig | undefined;
}

export interface LocalModuleConfig {
  /** The part of the config that is specific to the MQTT module */
  mqtt:
    | ModuleConfig_MQTTConfig
    | undefined;
  /** The part of the config that is specific to the Serial module */
  serial:
    | ModuleConfig_SerialConfig
    | undefined;
  /** The part of the config that is specific to the ExternalNotification module */
  externalNotification:
    | ModuleConfig_ExternalNotificationConfig
    | undefined;
  /** The part of the config that is specific to the Store & Forward module */
  storeForward:
    | ModuleConfig_StoreForwardConfig
    | undefined;
  /** The part of the config that is specific to the RangeTest module */
  rangeTest:
    | ModuleConfig_RangeTestConfig
    | undefined;
  /** The part of the config that is specific to the Telemetry module */
  telemetry:
    | ModuleConfig_TelemetryConfig
    | undefined;
  /** The part of the config that is specific to the Canned Message module */
  cannedMessage:
    | ModuleConfig_CannedMessageConfig
    | undefined;
  /** The part of the config that is specific to the Audio module */
  audio:
    | ModuleConfig_AudioConfig
    | undefined;
  /** The part of the config that is specific to the Remote Hardware module */
  remoteHardware:
    | ModuleConfig_RemoteHardwareConfig
    | undefined;
  /** The part of the config that is specific to the Neighbor Info module */
  neighborInfo:
    | ModuleConfig_NeighborInfoConfig
    | undefined;
  /** The part of the config that is specific to the Ambient Lighting module */
  ambientLighting:
    | ModuleConfig_AmbientLightingConfig
    | undefined;
  /** The part of the config that is specific to the Detection Sensor module */
  detectionSensor:
    | ModuleConfig_DetectionSensorConfig
    | undefined;
  /** Paxcounter Config */
  paxcounter:
    | ModuleConfig_PaxcounterConfig
    | undefined;
  /** StatusMessage Config */
  statusmessage:
    | ModuleConfig_StatusMessageConfig
    | undefined;
  /** The part of the config that is specific to the Traffic Management module */
  trafficManagement:
    | ModuleConfig_TrafficManagementConfig
    | undefined;
  /** TAK Config */
  tak:
    | ModuleConfig_TAKConfig
    | undefined;
  /** MeshBeacon Config */
  meshBeacon:
    | ModuleConfig_MeshBeaconConfig
    | undefined;
  /**
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  version: number;
}

function createBaseLocalConfig(): LocalConfig {
  return {
    device: undefined,
    position: undefined,
    power: undefined,
    network: undefined,
    display: undefined,
    lora: undefined,
    bluetooth: undefined,
    version: 0,
    security: undefined,
  };
}

export const LocalConfig = {
  encode(message: LocalConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.device !== undefined) {
      Config_DeviceConfig.encode(message.device, writer.uint32(10).fork()).ldelim();
    }
    if (message.position !== undefined) {
      Config_PositionConfig.encode(message.position, writer.uint32(18).fork()).ldelim();
    }
    if (message.power !== undefined) {
      Config_PowerConfig.encode(message.power, writer.uint32(26).fork()).ldelim();
    }
    if (message.network !== undefined) {
      Config_NetworkConfig.encode(message.network, writer.uint32(34).fork()).ldelim();
    }
    if (message.display !== undefined) {
      Config_DisplayConfig.encode(message.display, writer.uint32(42).fork()).ldelim();
    }
    if (message.lora !== undefined) {
      Config_LoRaConfig.encode(message.lora, writer.uint32(50).fork()).ldelim();
    }
    if (message.bluetooth !== undefined) {
      Config_BluetoothConfig.encode(message.bluetooth, writer.uint32(58).fork()).ldelim();
    }
    if (message.version !== 0) {
      writer.uint32(64).uint32(message.version);
    }
    if (message.security !== undefined) {
      Config_SecurityConfig.encode(message.security, writer.uint32(74).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LocalConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.device = Config_DeviceConfig.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.position = Config_PositionConfig.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.power = Config_PowerConfig.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.network = Config_NetworkConfig.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.display = Config_DisplayConfig.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.lora = Config_LoRaConfig.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.bluetooth = Config_BluetoothConfig.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.security = Config_SecurityConfig.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalConfig {
    return {
      device: isSet(object.device) ? Config_DeviceConfig.fromJSON(object.device) : undefined,
      position: isSet(object.position) ? Config_PositionConfig.fromJSON(object.position) : undefined,
      power: isSet(object.power) ? Config_PowerConfig.fromJSON(object.power) : undefined,
      network: isSet(object.network) ? Config_NetworkConfig.fromJSON(object.network) : undefined,
      display: isSet(object.display) ? Config_DisplayConfig.fromJSON(object.display) : undefined,
      lora: isSet(object.lora) ? Config_LoRaConfig.fromJSON(object.lora) : undefined,
      bluetooth: isSet(object.bluetooth) ? Config_BluetoothConfig.fromJSON(object.bluetooth) : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      security: isSet(object.security) ? Config_SecurityConfig.fromJSON(object.security) : undefined,
    };
  },

  toJSON(message: LocalConfig): unknown {
    const obj: any = {};
    if (message.device !== undefined) {
      obj.device = Config_DeviceConfig.toJSON(message.device);
    }
    if (message.position !== undefined) {
      obj.position = Config_PositionConfig.toJSON(message.position);
    }
    if (message.power !== undefined) {
      obj.power = Config_PowerConfig.toJSON(message.power);
    }
    if (message.network !== undefined) {
      obj.network = Config_NetworkConfig.toJSON(message.network);
    }
    if (message.display !== undefined) {
      obj.display = Config_DisplayConfig.toJSON(message.display);
    }
    if (message.lora !== undefined) {
      obj.lora = Config_LoRaConfig.toJSON(message.lora);
    }
    if (message.bluetooth !== undefined) {
      obj.bluetooth = Config_BluetoothConfig.toJSON(message.bluetooth);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.security !== undefined) {
      obj.security = Config_SecurityConfig.toJSON(message.security);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalConfig>, I>>(base?: I): LocalConfig {
    return LocalConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalConfig>, I>>(object: I): LocalConfig {
    const message = createBaseLocalConfig();
    message.device = (object.device !== undefined && object.device !== null)
      ? Config_DeviceConfig.fromPartial(object.device)
      : undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? Config_PositionConfig.fromPartial(object.position)
      : undefined;
    message.power = (object.power !== undefined && object.power !== null)
      ? Config_PowerConfig.fromPartial(object.power)
      : undefined;
    message.network = (object.network !== undefined && object.network !== null)
      ? Config_NetworkConfig.fromPartial(object.network)
      : undefined;
    message.display = (object.display !== undefined && object.display !== null)
      ? Config_DisplayConfig.fromPartial(object.display)
      : undefined;
    message.lora = (object.lora !== undefined && object.lora !== null)
      ? Config_LoRaConfig.fromPartial(object.lora)
      : undefined;
    message.bluetooth = (object.bluetooth !== undefined && object.bluetooth !== null)
      ? Config_BluetoothConfig.fromPartial(object.bluetooth)
      : undefined;
    message.version = object.version ?? 0;
    message.security = (object.security !== undefined && object.security !== null)
      ? Config_SecurityConfig.fromPartial(object.security)
      : undefined;
    return message;
  },
};

function createBaseLocalModuleConfig(): LocalModuleConfig {
  return {
    mqtt: undefined,
    serial: undefined,
    externalNotification: undefined,
    storeForward: undefined,
    rangeTest: undefined,
    telemetry: undefined,
    cannedMessage: undefined,
    audio: undefined,
    remoteHardware: undefined,
    neighborInfo: undefined,
    ambientLighting: undefined,
    detectionSensor: undefined,
    paxcounter: undefined,
    statusmessage: undefined,
    trafficManagement: undefined,
    tak: undefined,
    meshBeacon: undefined,
    version: 0,
  };
}

export const LocalModuleConfig = {
  encode(message: LocalModuleConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.mqtt !== undefined) {
      ModuleConfig_MQTTConfig.encode(message.mqtt, writer.uint32(10).fork()).ldelim();
    }
    if (message.serial !== undefined) {
      ModuleConfig_SerialConfig.encode(message.serial, writer.uint32(18).fork()).ldelim();
    }
    if (message.externalNotification !== undefined) {
      ModuleConfig_ExternalNotificationConfig.encode(message.externalNotification, writer.uint32(26).fork()).ldelim();
    }
    if (message.storeForward !== undefined) {
      ModuleConfig_StoreForwardConfig.encode(message.storeForward, writer.uint32(34).fork()).ldelim();
    }
    if (message.rangeTest !== undefined) {
      ModuleConfig_RangeTestConfig.encode(message.rangeTest, writer.uint32(42).fork()).ldelim();
    }
    if (message.telemetry !== undefined) {
      ModuleConfig_TelemetryConfig.encode(message.telemetry, writer.uint32(50).fork()).ldelim();
    }
    if (message.cannedMessage !== undefined) {
      ModuleConfig_CannedMessageConfig.encode(message.cannedMessage, writer.uint32(58).fork()).ldelim();
    }
    if (message.audio !== undefined) {
      ModuleConfig_AudioConfig.encode(message.audio, writer.uint32(74).fork()).ldelim();
    }
    if (message.remoteHardware !== undefined) {
      ModuleConfig_RemoteHardwareConfig.encode(message.remoteHardware, writer.uint32(82).fork()).ldelim();
    }
    if (message.neighborInfo !== undefined) {
      ModuleConfig_NeighborInfoConfig.encode(message.neighborInfo, writer.uint32(90).fork()).ldelim();
    }
    if (message.ambientLighting !== undefined) {
      ModuleConfig_AmbientLightingConfig.encode(message.ambientLighting, writer.uint32(98).fork()).ldelim();
    }
    if (message.detectionSensor !== undefined) {
      ModuleConfig_DetectionSensorConfig.encode(message.detectionSensor, writer.uint32(106).fork()).ldelim();
    }
    if (message.paxcounter !== undefined) {
      ModuleConfig_PaxcounterConfig.encode(message.paxcounter, writer.uint32(114).fork()).ldelim();
    }
    if (message.statusmessage !== undefined) {
      ModuleConfig_StatusMessageConfig.encode(message.statusmessage, writer.uint32(122).fork()).ldelim();
    }
    if (message.trafficManagement !== undefined) {
      ModuleConfig_TrafficManagementConfig.encode(message.trafficManagement, writer.uint32(130).fork()).ldelim();
    }
    if (message.tak !== undefined) {
      ModuleConfig_TAKConfig.encode(message.tak, writer.uint32(138).fork()).ldelim();
    }
    if (message.meshBeacon !== undefined) {
      ModuleConfig_MeshBeaconConfig.encode(message.meshBeacon, writer.uint32(146).fork()).ldelim();
    }
    if (message.version !== 0) {
      writer.uint32(64).uint32(message.version);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LocalModuleConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalModuleConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.mqtt = ModuleConfig_MQTTConfig.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.serial = ModuleConfig_SerialConfig.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.externalNotification = ModuleConfig_ExternalNotificationConfig.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.storeForward = ModuleConfig_StoreForwardConfig.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.rangeTest = ModuleConfig_RangeTestConfig.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.telemetry = ModuleConfig_TelemetryConfig.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.cannedMessage = ModuleConfig_CannedMessageConfig.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.audio = ModuleConfig_AudioConfig.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.remoteHardware = ModuleConfig_RemoteHardwareConfig.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.neighborInfo = ModuleConfig_NeighborInfoConfig.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.ambientLighting = ModuleConfig_AmbientLightingConfig.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.detectionSensor = ModuleConfig_DetectionSensorConfig.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.paxcounter = ModuleConfig_PaxcounterConfig.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.statusmessage = ModuleConfig_StatusMessageConfig.decode(reader, reader.uint32());
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.trafficManagement = ModuleConfig_TrafficManagementConfig.decode(reader, reader.uint32());
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.tak = ModuleConfig_TAKConfig.decode(reader, reader.uint32());
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.meshBeacon = ModuleConfig_MeshBeaconConfig.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.version = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalModuleConfig {
    return {
      mqtt: isSet(object.mqtt) ? ModuleConfig_MQTTConfig.fromJSON(object.mqtt) : undefined,
      serial: isSet(object.serial) ? ModuleConfig_SerialConfig.fromJSON(object.serial) : undefined,
      externalNotification: isSet(object.externalNotification)
        ? ModuleConfig_ExternalNotificationConfig.fromJSON(object.externalNotification)
        : undefined,
      storeForward: isSet(object.storeForward)
        ? ModuleConfig_StoreForwardConfig.fromJSON(object.storeForward)
        : undefined,
      rangeTest: isSet(object.rangeTest) ? ModuleConfig_RangeTestConfig.fromJSON(object.rangeTest) : undefined,
      telemetry: isSet(object.telemetry) ? ModuleConfig_TelemetryConfig.fromJSON(object.telemetry) : undefined,
      cannedMessage: isSet(object.cannedMessage)
        ? ModuleConfig_CannedMessageConfig.fromJSON(object.cannedMessage)
        : undefined,
      audio: isSet(object.audio) ? ModuleConfig_AudioConfig.fromJSON(object.audio) : undefined,
      remoteHardware: isSet(object.remoteHardware)
        ? ModuleConfig_RemoteHardwareConfig.fromJSON(object.remoteHardware)
        : undefined,
      neighborInfo: isSet(object.neighborInfo)
        ? ModuleConfig_NeighborInfoConfig.fromJSON(object.neighborInfo)
        : undefined,
      ambientLighting: isSet(object.ambientLighting)
        ? ModuleConfig_AmbientLightingConfig.fromJSON(object.ambientLighting)
        : undefined,
      detectionSensor: isSet(object.detectionSensor)
        ? ModuleConfig_DetectionSensorConfig.fromJSON(object.detectionSensor)
        : undefined,
      paxcounter: isSet(object.paxcounter) ? ModuleConfig_PaxcounterConfig.fromJSON(object.paxcounter) : undefined,
      statusmessage: isSet(object.statusmessage)
        ? ModuleConfig_StatusMessageConfig.fromJSON(object.statusmessage)
        : undefined,
      trafficManagement: isSet(object.trafficManagement)
        ? ModuleConfig_TrafficManagementConfig.fromJSON(object.trafficManagement)
        : undefined,
      tak: isSet(object.tak) ? ModuleConfig_TAKConfig.fromJSON(object.tak) : undefined,
      meshBeacon: isSet(object.meshBeacon) ? ModuleConfig_MeshBeaconConfig.fromJSON(object.meshBeacon) : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: LocalModuleConfig): unknown {
    const obj: any = {};
    if (message.mqtt !== undefined) {
      obj.mqtt = ModuleConfig_MQTTConfig.toJSON(message.mqtt);
    }
    if (message.serial !== undefined) {
      obj.serial = ModuleConfig_SerialConfig.toJSON(message.serial);
    }
    if (message.externalNotification !== undefined) {
      obj.externalNotification = ModuleConfig_ExternalNotificationConfig.toJSON(message.externalNotification);
    }
    if (message.storeForward !== undefined) {
      obj.storeForward = ModuleConfig_StoreForwardConfig.toJSON(message.storeForward);
    }
    if (message.rangeTest !== undefined) {
      obj.rangeTest = ModuleConfig_RangeTestConfig.toJSON(message.rangeTest);
    }
    if (message.telemetry !== undefined) {
      obj.telemetry = ModuleConfig_TelemetryConfig.toJSON(message.telemetry);
    }
    if (message.cannedMessage !== undefined) {
      obj.cannedMessage = ModuleConfig_CannedMessageConfig.toJSON(message.cannedMessage);
    }
    if (message.audio !== undefined) {
      obj.audio = ModuleConfig_AudioConfig.toJSON(message.audio);
    }
    if (message.remoteHardware !== undefined) {
      obj.remoteHardware = ModuleConfig_RemoteHardwareConfig.toJSON(message.remoteHardware);
    }
    if (message.neighborInfo !== undefined) {
      obj.neighborInfo = ModuleConfig_NeighborInfoConfig.toJSON(message.neighborInfo);
    }
    if (message.ambientLighting !== undefined) {
      obj.ambientLighting = ModuleConfig_AmbientLightingConfig.toJSON(message.ambientLighting);
    }
    if (message.detectionSensor !== undefined) {
      obj.detectionSensor = ModuleConfig_DetectionSensorConfig.toJSON(message.detectionSensor);
    }
    if (message.paxcounter !== undefined) {
      obj.paxcounter = ModuleConfig_PaxcounterConfig.toJSON(message.paxcounter);
    }
    if (message.statusmessage !== undefined) {
      obj.statusmessage = ModuleConfig_StatusMessageConfig.toJSON(message.statusmessage);
    }
    if (message.trafficManagement !== undefined) {
      obj.trafficManagement = ModuleConfig_TrafficManagementConfig.toJSON(message.trafficManagement);
    }
    if (message.tak !== undefined) {
      obj.tak = ModuleConfig_TAKConfig.toJSON(message.tak);
    }
    if (message.meshBeacon !== undefined) {
      obj.meshBeacon = ModuleConfig_MeshBeaconConfig.toJSON(message.meshBeacon);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalModuleConfig>, I>>(base?: I): LocalModuleConfig {
    return LocalModuleConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalModuleConfig>, I>>(object: I): LocalModuleConfig {
    const message = createBaseLocalModuleConfig();
    message.mqtt = (object.mqtt !== undefined && object.mqtt !== null)
      ? ModuleConfig_MQTTConfig.fromPartial(object.mqtt)
      : undefined;
    message.serial = (object.serial !== undefined && object.serial !== null)
      ? ModuleConfig_SerialConfig.fromPartial(object.serial)
      : undefined;
    message.externalNotification = (object.externalNotification !== undefined && object.externalNotification !== null)
      ? ModuleConfig_ExternalNotificationConfig.fromPartial(object.externalNotification)
      : undefined;
    message.storeForward = (object.storeForward !== undefined && object.storeForward !== null)
      ? ModuleConfig_StoreForwardConfig.fromPartial(object.storeForward)
      : undefined;
    message.rangeTest = (object.rangeTest !== undefined && object.rangeTest !== null)
      ? ModuleConfig_RangeTestConfig.fromPartial(object.rangeTest)
      : undefined;
    message.telemetry = (object.telemetry !== undefined && object.telemetry !== null)
      ? ModuleConfig_TelemetryConfig.fromPartial(object.telemetry)
      : undefined;
    message.cannedMessage = (object.cannedMessage !== undefined && object.cannedMessage !== null)
      ? ModuleConfig_CannedMessageConfig.fromPartial(object.cannedMessage)
      : undefined;
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? ModuleConfig_AudioConfig.fromPartial(object.audio)
      : undefined;
    message.remoteHardware = (object.remoteHardware !== undefined && object.remoteHardware !== null)
      ? ModuleConfig_RemoteHardwareConfig.fromPartial(object.remoteHardware)
      : undefined;
    message.neighborInfo = (object.neighborInfo !== undefined && object.neighborInfo !== null)
      ? ModuleConfig_NeighborInfoConfig.fromPartial(object.neighborInfo)
      : undefined;
    message.ambientLighting = (object.ambientLighting !== undefined && object.ambientLighting !== null)
      ? ModuleConfig_AmbientLightingConfig.fromPartial(object.ambientLighting)
      : undefined;
    message.detectionSensor = (object.detectionSensor !== undefined && object.detectionSensor !== null)
      ? ModuleConfig_DetectionSensorConfig.fromPartial(object.detectionSensor)
      : undefined;
    message.paxcounter = (object.paxcounter !== undefined && object.paxcounter !== null)
      ? ModuleConfig_PaxcounterConfig.fromPartial(object.paxcounter)
      : undefined;
    message.statusmessage = (object.statusmessage !== undefined && object.statusmessage !== null)
      ? ModuleConfig_StatusMessageConfig.fromPartial(object.statusmessage)
      : undefined;
    message.trafficManagement = (object.trafficManagement !== undefined && object.trafficManagement !== null)
      ? ModuleConfig_TrafficManagementConfig.fromPartial(object.trafficManagement)
      : undefined;
    message.tak = (object.tak !== undefined && object.tak !== null)
      ? ModuleConfig_TAKConfig.fromPartial(object.tak)
      : undefined;
    message.meshBeacon = (object.meshBeacon !== undefined && object.meshBeacon !== null)
      ? ModuleConfig_MeshBeaconConfig.fromPartial(object.meshBeacon)
      : undefined;
    message.version = object.version ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
