// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/mesh_beacon.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { ChannelSettings } from "./channel";
import {
  Config_LoRaConfig_ModemPreset,
  config_LoRaConfig_ModemPresetFromJSON,
  config_LoRaConfig_ModemPresetToJSON,
  Config_LoRaConfig_RegionCode,
  config_LoRaConfig_RegionCodeFromJSON,
  config_LoRaConfig_RegionCodeToJSON,
} from "./config";

/**
 * Payload for MESH_BEACON_APP packets.
 * Periodically broadcast by nodes in beacon mode.
 * Listeners deliver the text message to the local inbox and cache any offered
 * channel/preset for the client app to act on — the firmware never auto-applies them.
 */
export interface MeshBeacon {
  /** Human-readable beacon message. Max 100 bytes enforced by firmware on send. */
  message: string;
  /**
   * Optional channel (name + PSK) being advertised to listening clients.
   * A client app may offer to switch the user to this channel; firmware never applies it automatically.
   */
  offerChannel:
    | ChannelSettings
    | undefined;
  /** Optional region being advertised alongside offer_preset. */
  offerRegion: Config_LoRaConfig_RegionCode;
  /**
   * Optional modem preset being advertised.
   * Combined with offer_region, tells a client "there is a mesh on this preset/region".
   */
  offerPreset?: Config_LoRaConfig_ModemPreset | undefined;
}

function createBaseMeshBeacon(): MeshBeacon {
  return { message: "", offerChannel: undefined, offerRegion: 0, offerPreset: undefined };
}

export const MeshBeacon = {
  encode(message: MeshBeacon, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.offerChannel !== undefined) {
      ChannelSettings.encode(message.offerChannel, writer.uint32(18).fork()).ldelim();
    }
    if (message.offerRegion !== 0) {
      writer.uint32(24).int32(message.offerRegion);
    }
    if (message.offerPreset !== undefined) {
      writer.uint32(32).int32(message.offerPreset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MeshBeacon {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeshBeacon();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.offerChannel = ChannelSettings.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.offerRegion = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.offerPreset = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MeshBeacon {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      offerChannel: isSet(object.offerChannel) ? ChannelSettings.fromJSON(object.offerChannel) : undefined,
      offerRegion: isSet(object.offerRegion) ? config_LoRaConfig_RegionCodeFromJSON(object.offerRegion) : 0,
      offerPreset: isSet(object.offerPreset) ? config_LoRaConfig_ModemPresetFromJSON(object.offerPreset) : undefined,
    };
  },

  toJSON(message: MeshBeacon): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.offerChannel !== undefined) {
      obj.offerChannel = ChannelSettings.toJSON(message.offerChannel);
    }
    if (message.offerRegion !== 0) {
      obj.offerRegion = config_LoRaConfig_RegionCodeToJSON(message.offerRegion);
    }
    if (message.offerPreset !== undefined) {
      obj.offerPreset = config_LoRaConfig_ModemPresetToJSON(message.offerPreset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MeshBeacon>, I>>(base?: I): MeshBeacon {
    return MeshBeacon.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MeshBeacon>, I>>(object: I): MeshBeacon {
    const message = createBaseMeshBeacon();
    message.message = object.message ?? "";
    message.offerChannel = (object.offerChannel !== undefined && object.offerChannel !== null)
      ? ChannelSettings.fromPartial(object.offerChannel)
      : undefined;
    message.offerRegion = object.offerRegion ?? 0;
    message.offerPreset = object.offerPreset ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
