// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/mqtt.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import {
  Config_DeviceConfig_Role,
  config_DeviceConfig_RoleFromJSON,
  config_DeviceConfig_RoleToJSON,
  Config_LoRaConfig_ModemPreset,
  config_LoRaConfig_ModemPresetFromJSON,
  config_LoRaConfig_ModemPresetToJSON,
  Config_LoRaConfig_RegionCode,
  config_LoRaConfig_RegionCodeFromJSON,
  config_LoRaConfig_RegionCodeToJSON,
} from "./config";
import { HardwareModel, hardwareModelFromJSON, hardwareModelToJSON, MeshPacket } from "./mesh";

/** This message wraps a MeshPacket with extra metadata about the sender and how it arrived. */
export interface ServiceEnvelope {
  /** The (probably encrypted) packet */
  packet:
    | MeshPacket
    | undefined;
  /** The global channel ID it was sent on */
  channelId: string;
  /**
   * The sending gateway node ID. Can we use this to authenticate/prevent fake
   * nodeid impersonation for senders? - i.e. use gateway/mesh id (which is authenticated) + local node id as
   * the globally trusted nodenum
   */
  gatewayId: string;
}

/** Information about a node intended to be reported unencrypted to a map using MQTT. */
export interface MapReport {
  /** A full name for this user, i.e. "Kevin Hester" */
  longName: string;
  /**
   * A VERY short name, ideally two characters.
   * Suitable for a tiny OLED screen
   */
  shortName: string;
  /** Role of the node that applies specific settings for a particular use-case */
  role: Config_DeviceConfig_Role;
  /** Hardware model of the node, i.e. T-Beam, Heltec V3, etc... */
  hwModel: HardwareModel;
  /** Device firmware version string */
  firmwareVersion: string;
  /** The region code for the radio (US, CN, EU433, etc...) */
  region: Config_LoRaConfig_RegionCode;
  /** Modem preset used by the radio (LongFast, MediumSlow, etc...) */
  modemPreset: Config_LoRaConfig_ModemPreset;
  /**
   * Whether the node has a channel with default PSK and name (LongFast, MediumSlow, etc...)
   * and it uses the default frequency slot given the region and modem preset.
   */
  hasDefaultChannel: boolean;
  /** Latitude: multiply by 1e-7 to get degrees in floating point */
  latitudeI: number;
  /** Longitude: multiply by 1e-7 to get degrees in floating point */
  longitudeI: number;
  /** Altitude in meters above MSL */
  altitude: number;
  /** Indicates the bits of precision for latitude and longitude set by the sending node */
  positionPrecision: number;
  /** Number of online nodes (heard in the last 2 hours) this node has in its list that were received locally (not via MQTT) */
  numOnlineLocalNodes: number;
  /**
   * User has opted in to share their location (map report) with the mqtt server
   * Controlled by map_report.should_report_location
   */
  hasOptedReportLocation: boolean;
}

function createBaseServiceEnvelope(): ServiceEnvelope {
  return { packet: undefined, channelId: "", gatewayId: "" };
}

export const ServiceEnvelope = {
  encode(message: ServiceEnvelope, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.packet !== undefined) {
      MeshPacket.encode(message.packet, writer.uint32(10).fork()).ldelim();
    }
    if (message.channelId !== "") {
      writer.uint32(18).string(message.channelId);
    }
    if (message.gatewayId !== "") {
      writer.uint32(26).string(message.gatewayId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ServiceEnvelope {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.packet = MeshPacket.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.channelId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gatewayId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceEnvelope {
    return {
      packet: isSet(object.packet) ? MeshPacket.fromJSON(object.packet) : undefined,
      channelId: isSet(object.channelId) ? globalThis.String(object.channelId) : "",
      gatewayId: isSet(object.gatewayId) ? globalThis.String(object.gatewayId) : "",
    };
  },

  toJSON(message: ServiceEnvelope): unknown {
    const obj: any = {};
    if (message.packet !== undefined) {
      obj.packet = MeshPacket.toJSON(message.packet);
    }
    if (message.channelId !== "") {
      obj.channelId = message.channelId;
    }
    if (message.gatewayId !== "") {
      obj.gatewayId = message.gatewayId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceEnvelope>, I>>(base?: I): ServiceEnvelope {
    return ServiceEnvelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceEnvelope>, I>>(object: I): ServiceEnvelope {
    const message = createBaseServiceEnvelope();
    message.packet = (object.packet !== undefined && object.packet !== null)
      ? MeshPacket.fromPartial(object.packet)
      : undefined;
    message.channelId = object.channelId ?? "";
    message.gatewayId = object.gatewayId ?? "";
    return message;
  },
};

function createBaseMapReport(): MapReport {
  return {
    longName: "",
    shortName: "",
    role: 0,
    hwModel: 0,
    firmwareVersion: "",
    region: 0,
    modemPreset: 0,
    hasDefaultChannel: false,
    latitudeI: 0,
    longitudeI: 0,
    altitude: 0,
    positionPrecision: 0,
    numOnlineLocalNodes: 0,
    hasOptedReportLocation: false,
  };
}

export const MapReport = {
  encode(message: MapReport, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.longName !== "") {
      writer.uint32(10).string(message.longName);
    }
    if (message.shortName !== "") {
      writer.uint32(18).string(message.shortName);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.hwModel !== 0) {
      writer.uint32(32).int32(message.hwModel);
    }
    if (message.firmwareVersion !== "") {
      writer.uint32(42).string(message.firmwareVersion);
    }
    if (message.region !== 0) {
      writer.uint32(48).int32(message.region);
    }
    if (message.modemPreset !== 0) {
      writer.uint32(56).int32(message.modemPreset);
    }
    if (message.hasDefaultChannel !== false) {
      writer.uint32(64).bool(message.hasDefaultChannel);
    }
    if (message.latitudeI !== 0) {
      writer.uint32(77).sfixed32(message.latitudeI);
    }
    if (message.longitudeI !== 0) {
      writer.uint32(85).sfixed32(message.longitudeI);
    }
    if (message.altitude !== 0) {
      writer.uint32(88).int32(message.altitude);
    }
    if (message.positionPrecision !== 0) {
      writer.uint32(96).uint32(message.positionPrecision);
    }
    if (message.numOnlineLocalNodes !== 0) {
      writer.uint32(104).uint32(message.numOnlineLocalNodes);
    }
    if (message.hasOptedReportLocation !== false) {
      writer.uint32(112).bool(message.hasOptedReportLocation);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MapReport {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMapReport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.longName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.shortName = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.hwModel = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.firmwareVersion = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.region = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.modemPreset = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.hasDefaultChannel = reader.bool();
          continue;
        case 9:
          if (tag !== 77) {
            break;
          }

          message.latitudeI = reader.sfixed32();
          continue;
        case 10:
          if (tag !== 85) {
            break;
          }

          message.longitudeI = reader.sfixed32();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.altitude = reader.int32();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.positionPrecision = reader.uint32();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.numOnlineLocalNodes = reader.uint32();
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.hasOptedReportLocation = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MapReport {
    return {
      longName: isSet(object.longName) ? globalThis.String(object.longName) : "",
      shortName: isSet(object.shortName) ? globalThis.String(object.shortName) : "",
      role: isSet(object.role) ? config_DeviceConfig_RoleFromJSON(object.role) : 0,
      hwModel: isSet(object.hwModel) ? hardwareModelFromJSON(object.hwModel) : 0,
      firmwareVersion: isSet(object.firmwareVersion) ? globalThis.String(object.firmwareVersion) : "",
      region: isSet(object.region) ? config_LoRaConfig_RegionCodeFromJSON(object.region) : 0,
      modemPreset: isSet(object.modemPreset) ? config_LoRaConfig_ModemPresetFromJSON(object.modemPreset) : 0,
      hasDefaultChannel: isSet(object.hasDefaultChannel) ? globalThis.Boolean(object.hasDefaultChannel) : false,
      latitudeI: isSet(object.latitudeI) ? globalThis.Number(object.latitudeI) : 0,
      longitudeI: isSet(object.longitudeI) ? globalThis.Number(object.longitudeI) : 0,
      altitude: isSet(object.altitude) ? globalThis.Number(object.altitude) : 0,
      positionPrecision: isSet(object.positionPrecision) ? globalThis.Number(object.positionPrecision) : 0,
      numOnlineLocalNodes: isSet(object.numOnlineLocalNodes) ? globalThis.Number(object.numOnlineLocalNodes) : 0,
      hasOptedReportLocation: isSet(object.hasOptedReportLocation)
        ? globalThis.Boolean(object.hasOptedReportLocation)
        : false,
    };
  },

  toJSON(message: MapReport): unknown {
    const obj: any = {};
    if (message.longName !== "") {
      obj.longName = message.longName;
    }
    if (message.shortName !== "") {
      obj.shortName = message.shortName;
    }
    if (message.role !== 0) {
      obj.role = config_DeviceConfig_RoleToJSON(message.role);
    }
    if (message.hwModel !== 0) {
      obj.hwModel = hardwareModelToJSON(message.hwModel);
    }
    if (message.firmwareVersion !== "") {
      obj.firmwareVersion = message.firmwareVersion;
    }
    if (message.region !== 0) {
      obj.region = config_LoRaConfig_RegionCodeToJSON(message.region);
    }
    if (message.modemPreset !== 0) {
      obj.modemPreset = config_LoRaConfig_ModemPresetToJSON(message.modemPreset);
    }
    if (message.hasDefaultChannel !== false) {
      obj.hasDefaultChannel = message.hasDefaultChannel;
    }
    if (message.latitudeI !== 0) {
      obj.latitudeI = Math.round(message.latitudeI);
    }
    if (message.longitudeI !== 0) {
      obj.longitudeI = Math.round(message.longitudeI);
    }
    if (message.altitude !== 0) {
      obj.altitude = Math.round(message.altitude);
    }
    if (message.positionPrecision !== 0) {
      obj.positionPrecision = Math.round(message.positionPrecision);
    }
    if (message.numOnlineLocalNodes !== 0) {
      obj.numOnlineLocalNodes = Math.round(message.numOnlineLocalNodes);
    }
    if (message.hasOptedReportLocation !== false) {
      obj.hasOptedReportLocation = message.hasOptedReportLocation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MapReport>, I>>(base?: I): MapReport {
    return MapReport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MapReport>, I>>(object: I): MapReport {
    const message = createBaseMapReport();
    message.longName = object.longName ?? "";
    message.shortName = object.shortName ?? "";
    message.role = object.role ?? 0;
    message.hwModel = object.hwModel ?? 0;
    message.firmwareVersion = object.firmwareVersion ?? "";
    message.region = object.region ?? 0;
    message.modemPreset = object.modemPreset ?? 0;
    message.hasDefaultChannel = object.hasDefaultChannel ?? false;
    message.latitudeI = object.latitudeI ?? 0;
    message.longitudeI = object.longitudeI ?? 0;
    message.altitude = object.altitude ?? 0;
    message.positionPrecision = object.positionPrecision ?? 0;
    message.numOnlineLocalNodes = object.numOnlineLocalNodes ?? 0;
    message.hasOptedReportLocation = object.hasOptedReportLocation ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
