// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/paxcount.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/** TODO: REPLACE */
export interface Paxcount {
  /** seen Wifi devices */
  wifi: number;
  /** Seen BLE devices */
  ble: number;
  /** Uptime in seconds */
  uptime: number;
}

function createBasePaxcount(): Paxcount {
  return { wifi: 0, ble: 0, uptime: 0 };
}

export const Paxcount = {
  encode(message: Paxcount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.wifi !== 0) {
      writer.uint32(8).uint32(message.wifi);
    }
    if (message.ble !== 0) {
      writer.uint32(16).uint32(message.ble);
    }
    if (message.uptime !== 0) {
      writer.uint32(24).uint32(message.uptime);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Paxcount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaxcount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.wifi = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.ble = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.uptime = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Paxcount {
    return {
      wifi: isSet(object.wifi) ? globalThis.Number(object.wifi) : 0,
      ble: isSet(object.ble) ? globalThis.Number(object.ble) : 0,
      uptime: isSet(object.uptime) ? globalThis.Number(object.uptime) : 0,
    };
  },

  toJSON(message: Paxcount): unknown {
    const obj: any = {};
    if (message.wifi !== 0) {
      obj.wifi = Math.round(message.wifi);
    }
    if (message.ble !== 0) {
      obj.ble = Math.round(message.ble);
    }
    if (message.uptime !== 0) {
      obj.uptime = Math.round(message.uptime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Paxcount>, I>>(base?: I): Paxcount {
    return Paxcount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Paxcount>, I>>(object: I): Paxcount {
    const message = createBasePaxcount();
    message.wifi = object.wifi ?? 0;
    message.ble = object.ble ?? 0;
    message.uptime = object.uptime ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
