// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/portnums.proto

/* eslint-disable */

/**
 * For any new 'apps' that run on the device or via sister apps on phones/PCs they should pick and use a
 * unique 'portnum' for their application.
 * If you are making a new app using meshtastic, please send in a pull request to add your 'portnum' to this
 * master table.
 * PortNums should be assigned in the following range:
 * 0-63   Core Meshtastic use, do not use for third party apps
 * 64-127 Registered 3rd party apps, send in a pull request that adds a new entry to portnums.proto to  register your application
 * 256-511 Use one of these portnums for your private applications that you don't want to register publically
 * All other values are reserved.
 * Note: This was formerly a Type enum named 'typ' with the same id #
 * We have change to this 'portnum' based scheme for specifying app handlers for particular payloads.
 * This change is backwards compatible by treating the legacy OPAQUE/CLEAR_TEXT values identically.
 */
export enum PortNum {
  /**
   * UNKNOWN_APP - Deprecated: do not use in new code (formerly called OPAQUE)
   * A message sent from a device outside of the mesh, in a form the mesh does not understand
   * NOTE: This must be 0, because it is documented in IMeshService.aidl to be so
   * ENCODING: binary undefined
   */
  UNKNOWN_APP = 0,
  /**
   * TEXT_MESSAGE_APP - A simple UTF-8 text message, which even the little micros in the mesh
   * can understand and show on their screen eventually in some circumstances
   * even signal might send messages in this form (see below)
   * ENCODING: UTF-8 Plaintext (?)
   */
  TEXT_MESSAGE_APP = 1,
  /**
   * REMOTE_HARDWARE_APP - Reserved for built-in GPIO/example app.
   * See remote_hardware.proto/HardwareMessage for details on the message sent/received to this port number
   * ENCODING: Protobuf
   */
  REMOTE_HARDWARE_APP = 2,
  /**
   * POSITION_APP - The built-in position messaging app.
   * Payload is a Position message.
   * ENCODING: Protobuf
   */
  POSITION_APP = 3,
  /**
   * NODEINFO_APP - The built-in user info app.
   * Payload is a User message.
   * ENCODING: Protobuf
   */
  NODEINFO_APP = 4,
  /**
   * ROUTING_APP - Protocol control packets for mesh protocol use.
   * Payload is a Routing message.
   * ENCODING: Protobuf
   */
  ROUTING_APP = 5,
  /**
   * ADMIN_APP - Admin control packets.
   * Payload is a AdminMessage message.
   * ENCODING: Protobuf
   */
  ADMIN_APP = 6,
  /**
   * TEXT_MESSAGE_COMPRESSED_APP - Compressed TEXT_MESSAGE payloads.
   * ENCODING: UTF-8 Plaintext (?) with Unishox2 Compression
   * NOTE: The Device Firmware converts a TEXT_MESSAGE_APP to TEXT_MESSAGE_COMPRESSED_APP if the compressed
   * payload is shorter. There's no need for app developers to do this themselves. Also the firmware will decompress
   * any incoming TEXT_MESSAGE_COMPRESSED_APP payload and convert to TEXT_MESSAGE_APP.
   */
  TEXT_MESSAGE_COMPRESSED_APP = 7,
  /**
   * WAYPOINT_APP - Waypoint payloads.
   * Payload is a Waypoint message.
   * ENCODING: Protobuf
   */
  WAYPOINT_APP = 8,
  /**
   * AUDIO_APP - Audio Payloads.
   * Encapsulated codec2 packets. On 2.4 GHZ Bandwidths only for now
   * ENCODING: codec2 audio frames
   * NOTE: audio frames contain a 3 byte header (0xc0 0xde 0xc2) and a one byte marker for the decompressed bitrate.
   * This marker comes from the 'moduleConfig.audio.bitrate' enum minus one.
   */
  AUDIO_APP = 9,
  /**
   * DETECTION_SENSOR_APP - Same as Text Message but originating from Detection Sensor Module.
   * NOTE: This portnum traffic is not sent to the public MQTT starting at firmware version 2.2.9
   */
  DETECTION_SENSOR_APP = 10,
  /** ALERT_APP - Same as Text Message but used for critical alerts. */
  ALERT_APP = 11,
  /** KEY_VERIFICATION_APP - Module/port for handling key verification requests. */
  KEY_VERIFICATION_APP = 12,
  /** REMOTE_SHELL_APP - Module/port for handling primitive remote shell access. */
  REMOTE_SHELL_APP = 13,
  /**
   * REPLY_APP - Provides a 'ping' service that replies to any packet it receives.
   * Also serves as a small example module.
   * ENCODING: ASCII Plaintext
   */
  REPLY_APP = 32,
  /**
   * IP_TUNNEL_APP - Used for the python IP tunnel feature
   * ENCODING: IP Packet. Handled by the python API, firmware ignores this one and pases on.
   */
  IP_TUNNEL_APP = 33,
  /**
   * PAXCOUNTER_APP - Paxcounter lib included in the firmware
   * ENCODING: protobuf
   */
  PAXCOUNTER_APP = 34,
  /**
   * STORE_FORWARD_PLUSPLUS_APP - Store and Forward++ module included in the firmware
   * ENCODING: protobuf
   * This module is specifically for Native Linux nodes, and provides a Git-style
   * chain of messages.
   */
  STORE_FORWARD_PLUSPLUS_APP = 35,
  /**
   * NODE_STATUS_APP - Node Status module
   * ENCODING: protobuf
   * This module allows setting an extra string of status for a node.
   * Broadcasts on change and on a timer, possibly once a day.
   */
  NODE_STATUS_APP = 36,
  /**
   * MESH_BEACON_APP - Beacon module broadcast packets.
   * ENCODING: protobuf
   * Periodically broadcast by nodes in beacon mode; received by nodes with MeshBeaconConfig.FLAG_LISTEN_ENABLED.
   * Carries a text message plus optional channel/preset offers for client apps.
   */
  MESH_BEACON_APP = 37,
  /**
   * SERIAL_APP - Provides a hardware serial interface to send and receive from the Meshtastic network.
   * Connect to the RX/TX pins of a device with 38400 8N1. Packets received from the Meshtastic
   * network is forwarded to the RX pin while sending a packet to TX will go out to the Mesh network.
   * Maximum packet size of 240 bytes.
   * Module is disabled by default can be turned on by setting SERIAL_MODULE_ENABLED = 1 in SerialPlugh.cpp.
   * ENCODING: binary undefined
   */
  SERIAL_APP = 64,
  /**
   * STORE_FORWARD_APP - STORE_FORWARD_APP (Work in Progress)
   * Maintained by Jm Casler (MC Hamster) : jm@casler.org
   * ENCODING: Protobuf
   */
  STORE_FORWARD_APP = 65,
  /**
   * RANGE_TEST_APP - Optional port for messages for the range test module.
   * ENCODING: ASCII Plaintext
   * NOTE: This portnum traffic is not sent to the public MQTT starting at firmware version 2.2.9
   */
  RANGE_TEST_APP = 66,
  /**
   * TELEMETRY_APP - Provides a format to send and receive telemetry data from the Meshtastic network.
   * Maintained by Charles Crossan (crossan007) : crossan007@gmail.com
   * ENCODING: Protobuf
   */
  TELEMETRY_APP = 67,
  /**
   * ZPS_APP - Experimental tools for estimating node position without a GPS
   * Maintained by Github user a-f-G-U-C (a Meshtastic contributor)
   * Project files at https://github.com/a-f-G-U-C/Meshtastic-ZPS
   * ENCODING: arrays of int64 fields
   */
  ZPS_APP = 68,
  /**
   * SIMULATOR_APP - Used to let multiple instances of Linux native applications communicate
   * as if they did using their LoRa chip.
   * Maintained by GitHub user GUVWAF.
   * Project files at https://github.com/GUVWAF/Meshtasticator
   * ENCODING: Protobuf (?)
   */
  SIMULATOR_APP = 69,
  /**
   * TRACEROUTE_APP - Provides a traceroute functionality to show the route a packet towards
   * a certain destination would take on the mesh. Contains a RouteDiscovery message as payload.
   * ENCODING: Protobuf
   */
  TRACEROUTE_APP = 70,
  /**
   * NEIGHBORINFO_APP - Aggregates edge info for the network by sending out a list of each node's neighbors
   * ENCODING: Protobuf
   */
  NEIGHBORINFO_APP = 71,
  /**
   * ATAK_PLUGIN - ATAK Plugin
   * Portnum for payloads from the official Meshtastic ATAK plugin
   */
  ATAK_PLUGIN = 72,
  /** MAP_REPORT_APP - Provides unencrypted information about a node for consumption by a map via MQTT */
  MAP_REPORT_APP = 73,
  /** POWERSTRESS_APP - PowerStress based monitoring support (for automated power consumption testing) */
  POWERSTRESS_APP = 74,
  /**
   * LORAWAN_BRIDGE - LoraWAN Payload Transport
   * ENCODING: compact binary LoRaWAN uplink (10-byte RF metadata + PHY payload) - see LoRaWANBridgeModule
   */
  LORAWAN_BRIDGE = 75,
  /**
   * RETICULUM_TUNNEL_APP - Reticulum Network Stack Tunnel App
   * ENCODING: Fragmented RNS Packet. Handled by Meshtastic RNS interface
   */
  RETICULUM_TUNNEL_APP = 76,
  /**
   * CAYENNE_APP - App for transporting Cayenne Low Power Payload, popular for LoRaWAN sensor nodes. Offers ability to send
   * arbitrary telemetry over meshtastic that is not covered by telemetry.proto
   * ENCODING: CayenneLLP
   */
  CAYENNE_APP = 77,
  /**
   * ATAK_PLUGIN_V2 - ATAK Plugin V2
   * Portnum for payloads from the official Meshtastic ATAK plugin using
   * TAKPacketV2 with zstd dictionary compression.
   */
  ATAK_PLUGIN_V2 = 78,
  /**
   * GROUPALARM_APP - GroupAlarm integration
   * Used for transporting GroupAlarm-related messages between Meshtastic nodes
   * and companion applications/services.
   */
  GROUPALARM_APP = 112,
  /**
   * PRIVATE_APP - Private applications should use portnums >= 256.
   * To simplify initial development and testing you can use "PRIVATE_APP"
   * in your code without needing to rebuild protobuf files (via [regen-protos.sh](https://github.com/meshtastic/firmware/blob/master/bin/regen-protos.sh))
   */
  PRIVATE_APP = 256,
  /**
   * ATAK_FORWARDER - ATAK Forwarder Module https://github.com/paulmandal/atak-forwarder
   * ENCODING: libcotshrink
   */
  ATAK_FORWARDER = 257,
  /** MAX - Currently we limit port nums to no higher than this value */
  MAX = 511,
  UNRECOGNIZED = -1,
}

export function portNumFromJSON(object: any): PortNum {
  switch (object) {
    case 0:
    case "UNKNOWN_APP":
      return PortNum.UNKNOWN_APP;
    case 1:
    case "TEXT_MESSAGE_APP":
      return PortNum.TEXT_MESSAGE_APP;
    case 2:
    case "REMOTE_HARDWARE_APP":
      return PortNum.REMOTE_HARDWARE_APP;
    case 3:
    case "POSITION_APP":
      return PortNum.POSITION_APP;
    case 4:
    case "NODEINFO_APP":
      return PortNum.NODEINFO_APP;
    case 5:
    case "ROUTING_APP":
      return PortNum.ROUTING_APP;
    case 6:
    case "ADMIN_APP":
      return PortNum.ADMIN_APP;
    case 7:
    case "TEXT_MESSAGE_COMPRESSED_APP":
      return PortNum.TEXT_MESSAGE_COMPRESSED_APP;
    case 8:
    case "WAYPOINT_APP":
      return PortNum.WAYPOINT_APP;
    case 9:
    case "AUDIO_APP":
      return PortNum.AUDIO_APP;
    case 10:
    case "DETECTION_SENSOR_APP":
      return PortNum.DETECTION_SENSOR_APP;
    case 11:
    case "ALERT_APP":
      return PortNum.ALERT_APP;
    case 12:
    case "KEY_VERIFICATION_APP":
      return PortNum.KEY_VERIFICATION_APP;
    case 13:
    case "REMOTE_SHELL_APP":
      return PortNum.REMOTE_SHELL_APP;
    case 32:
    case "REPLY_APP":
      return PortNum.REPLY_APP;
    case 33:
    case "IP_TUNNEL_APP":
      return PortNum.IP_TUNNEL_APP;
    case 34:
    case "PAXCOUNTER_APP":
      return PortNum.PAXCOUNTER_APP;
    case 35:
    case "STORE_FORWARD_PLUSPLUS_APP":
      return PortNum.STORE_FORWARD_PLUSPLUS_APP;
    case 36:
    case "NODE_STATUS_APP":
      return PortNum.NODE_STATUS_APP;
    case 37:
    case "MESH_BEACON_APP":
      return PortNum.MESH_BEACON_APP;
    case 64:
    case "SERIAL_APP":
      return PortNum.SERIAL_APP;
    case 65:
    case "STORE_FORWARD_APP":
      return PortNum.STORE_FORWARD_APP;
    case 66:
    case "RANGE_TEST_APP":
      return PortNum.RANGE_TEST_APP;
    case 67:
    case "TELEMETRY_APP":
      return PortNum.TELEMETRY_APP;
    case 68:
    case "ZPS_APP":
      return PortNum.ZPS_APP;
    case 69:
    case "SIMULATOR_APP":
      return PortNum.SIMULATOR_APP;
    case 70:
    case "TRACEROUTE_APP":
      return PortNum.TRACEROUTE_APP;
    case 71:
    case "NEIGHBORINFO_APP":
      return PortNum.NEIGHBORINFO_APP;
    case 72:
    case "ATAK_PLUGIN":
      return PortNum.ATAK_PLUGIN;
    case 73:
    case "MAP_REPORT_APP":
      return PortNum.MAP_REPORT_APP;
    case 74:
    case "POWERSTRESS_APP":
      return PortNum.POWERSTRESS_APP;
    case 75:
    case "LORAWAN_BRIDGE":
      return PortNum.LORAWAN_BRIDGE;
    case 76:
    case "RETICULUM_TUNNEL_APP":
      return PortNum.RETICULUM_TUNNEL_APP;
    case 77:
    case "CAYENNE_APP":
      return PortNum.CAYENNE_APP;
    case 78:
    case "ATAK_PLUGIN_V2":
      return PortNum.ATAK_PLUGIN_V2;
    case 112:
    case "GROUPALARM_APP":
      return PortNum.GROUPALARM_APP;
    case 256:
    case "PRIVATE_APP":
      return PortNum.PRIVATE_APP;
    case 257:
    case "ATAK_FORWARDER":
      return PortNum.ATAK_FORWARDER;
    case 511:
    case "MAX":
      return PortNum.MAX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PortNum.UNRECOGNIZED;
  }
}

export function portNumToJSON(object: PortNum): string {
  switch (object) {
    case PortNum.UNKNOWN_APP:
      return "UNKNOWN_APP";
    case PortNum.TEXT_MESSAGE_APP:
      return "TEXT_MESSAGE_APP";
    case PortNum.REMOTE_HARDWARE_APP:
      return "REMOTE_HARDWARE_APP";
    case PortNum.POSITION_APP:
      return "POSITION_APP";
    case PortNum.NODEINFO_APP:
      return "NODEINFO_APP";
    case PortNum.ROUTING_APP:
      return "ROUTING_APP";
    case PortNum.ADMIN_APP:
      return "ADMIN_APP";
    case PortNum.TEXT_MESSAGE_COMPRESSED_APP:
      return "TEXT_MESSAGE_COMPRESSED_APP";
    case PortNum.WAYPOINT_APP:
      return "WAYPOINT_APP";
    case PortNum.AUDIO_APP:
      return "AUDIO_APP";
    case PortNum.DETECTION_SENSOR_APP:
      return "DETECTION_SENSOR_APP";
    case PortNum.ALERT_APP:
      return "ALERT_APP";
    case PortNum.KEY_VERIFICATION_APP:
      return "KEY_VERIFICATION_APP";
    case PortNum.REMOTE_SHELL_APP:
      return "REMOTE_SHELL_APP";
    case PortNum.REPLY_APP:
      return "REPLY_APP";
    case PortNum.IP_TUNNEL_APP:
      return "IP_TUNNEL_APP";
    case PortNum.PAXCOUNTER_APP:
      return "PAXCOUNTER_APP";
    case PortNum.STORE_FORWARD_PLUSPLUS_APP:
      return "STORE_FORWARD_PLUSPLUS_APP";
    case PortNum.NODE_STATUS_APP:
      return "NODE_STATUS_APP";
    case PortNum.MESH_BEACON_APP:
      return "MESH_BEACON_APP";
    case PortNum.SERIAL_APP:
      return "SERIAL_APP";
    case PortNum.STORE_FORWARD_APP:
      return "STORE_FORWARD_APP";
    case PortNum.RANGE_TEST_APP:
      return "RANGE_TEST_APP";
    case PortNum.TELEMETRY_APP:
      return "TELEMETRY_APP";
    case PortNum.ZPS_APP:
      return "ZPS_APP";
    case PortNum.SIMULATOR_APP:
      return "SIMULATOR_APP";
    case PortNum.TRACEROUTE_APP:
      return "TRACEROUTE_APP";
    case PortNum.NEIGHBORINFO_APP:
      return "NEIGHBORINFO_APP";
    case PortNum.ATAK_PLUGIN:
      return "ATAK_PLUGIN";
    case PortNum.MAP_REPORT_APP:
      return "MAP_REPORT_APP";
    case PortNum.POWERSTRESS_APP:
      return "POWERSTRESS_APP";
    case PortNum.LORAWAN_BRIDGE:
      return "LORAWAN_BRIDGE";
    case PortNum.RETICULUM_TUNNEL_APP:
      return "RETICULUM_TUNNEL_APP";
    case PortNum.CAYENNE_APP:
      return "CAYENNE_APP";
    case PortNum.ATAK_PLUGIN_V2:
      return "ATAK_PLUGIN_V2";
    case PortNum.GROUPALARM_APP:
      return "GROUPALARM_APP";
    case PortNum.PRIVATE_APP:
      return "PRIVATE_APP";
    case PortNum.ATAK_FORWARDER:
      return "ATAK_FORWARDER";
    case PortNum.MAX:
      return "MAX";
    case PortNum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
