// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/powermon.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/**
 * Note: There are no 'PowerMon' messages normally in use (PowerMons are sent only as structured logs - slogs).
 * But we wrap our State enum in this message to effectively nest a namespace (without our linter yelling at us)
 */
export interface PowerMon {
}

/**
 * Any significant power changing event in meshtastic should be tagged with a powermon state transition.
 * If you are making new meshtastic features feel free to add new entries at the end of this definition.
 */
export enum PowerMon_State {
  None = 0,
  CPU_DeepSleep = 1,
  CPU_LightSleep = 2,
  /**
   * Vext1_On - The external Vext1 power is on.  Many boards have auxillary power rails that the CPU turns on only
   * occasionally.  In cases where that rail has multiple devices on it we usually want to have logging on
   * the state of that rail as an independent record.
   * For instance on the Heltec Tracker 1.1 board, this rail is the power source for the GPS and screen.
   *
   * The log messages will be short and complete (see PowerMon.Event in the protobufs for details).
   * something like "S:PM:C,0x00001234,REASON" where the hex number is the bitmask of all current states.
   * (We use a bitmask for states so that if a log message gets lost it won't be fatal)
   */
  Vext1_On = 4,
  Lora_RXOn = 8,
  Lora_TXOn = 16,
  Lora_RXActive = 32,
  BT_On = 64,
  LED_On = 128,
  Screen_On = 256,
  Screen_Drawing = 512,
  Wifi_On = 1024,
  /**
   * GPS_Active - GPS is actively trying to find our location
   * See GPSPowerState for more details
   */
  GPS_Active = 2048,
  UNRECOGNIZED = -1,
}

export function powerMon_StateFromJSON(object: any): PowerMon_State {
  switch (object) {
    case 0:
    case "None":
      return PowerMon_State.None;
    case 1:
    case "CPU_DeepSleep":
      return PowerMon_State.CPU_DeepSleep;
    case 2:
    case "CPU_LightSleep":
      return PowerMon_State.CPU_LightSleep;
    case 4:
    case "Vext1_On":
      return PowerMon_State.Vext1_On;
    case 8:
    case "Lora_RXOn":
      return PowerMon_State.Lora_RXOn;
    case 16:
    case "Lora_TXOn":
      return PowerMon_State.Lora_TXOn;
    case 32:
    case "Lora_RXActive":
      return PowerMon_State.Lora_RXActive;
    case 64:
    case "BT_On":
      return PowerMon_State.BT_On;
    case 128:
    case "LED_On":
      return PowerMon_State.LED_On;
    case 256:
    case "Screen_On":
      return PowerMon_State.Screen_On;
    case 512:
    case "Screen_Drawing":
      return PowerMon_State.Screen_Drawing;
    case 1024:
    case "Wifi_On":
      return PowerMon_State.Wifi_On;
    case 2048:
    case "GPS_Active":
      return PowerMon_State.GPS_Active;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PowerMon_State.UNRECOGNIZED;
  }
}

export function powerMon_StateToJSON(object: PowerMon_State): string {
  switch (object) {
    case PowerMon_State.None:
      return "None";
    case PowerMon_State.CPU_DeepSleep:
      return "CPU_DeepSleep";
    case PowerMon_State.CPU_LightSleep:
      return "CPU_LightSleep";
    case PowerMon_State.Vext1_On:
      return "Vext1_On";
    case PowerMon_State.Lora_RXOn:
      return "Lora_RXOn";
    case PowerMon_State.Lora_TXOn:
      return "Lora_TXOn";
    case PowerMon_State.Lora_RXActive:
      return "Lora_RXActive";
    case PowerMon_State.BT_On:
      return "BT_On";
    case PowerMon_State.LED_On:
      return "LED_On";
    case PowerMon_State.Screen_On:
      return "Screen_On";
    case PowerMon_State.Screen_Drawing:
      return "Screen_Drawing";
    case PowerMon_State.Wifi_On:
      return "Wifi_On";
    case PowerMon_State.GPS_Active:
      return "GPS_Active";
    case PowerMon_State.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PowerStress testing support via the C++ PowerStress module */
export interface PowerStressMessage {
  /** What type of HardwareMessage is this? */
  cmd: PowerStressMessage_Opcode;
  numSeconds: number;
}

/**
 * What operation would we like the UUT to perform.
 * note: senders should probably set want_response in their request packets, so that they can know when the state
 * machine has started processing their request
 */
export enum PowerStressMessage_Opcode {
  /** UNSET - Unset/unused */
  UNSET = 0,
  /** PRINT_INFO - Print board version slog and send an ack that we are alive and ready to process commands */
  PRINT_INFO = 1,
  /** FORCE_QUIET - Try to turn off all automatic processing of packets, screen, sleeping, etc (to make it easier to measure in isolation) */
  FORCE_QUIET = 2,
  /** END_QUIET - Stop powerstress processing - probably by just rebooting the board */
  END_QUIET = 3,
  /** SCREEN_ON - Turn the screen on */
  SCREEN_ON = 16,
  /** SCREEN_OFF - Turn the screen off */
  SCREEN_OFF = 17,
  /** CPU_IDLE - Let the CPU run but we assume mostly idling for num_seconds */
  CPU_IDLE = 32,
  /** CPU_DEEPSLEEP - Force deep sleep for FIXME seconds */
  CPU_DEEPSLEEP = 33,
  /** CPU_FULLON - Spin the CPU as fast as possible for num_seconds */
  CPU_FULLON = 34,
  /** LED_ON - Turn the LED on for num_seconds (and leave it on - for baseline power measurement purposes) */
  LED_ON = 48,
  /** LED_OFF - Force the LED off for num_seconds */
  LED_OFF = 49,
  /** LORA_OFF - Completely turn off the LORA radio for num_seconds */
  LORA_OFF = 64,
  /** LORA_TX - Send Lora packets for num_seconds */
  LORA_TX = 65,
  /** LORA_RX - Receive Lora packets for num_seconds (node will be mostly just listening, unless an external agent is helping stress this by sending packets on the current channel) */
  LORA_RX = 66,
  /** BT_OFF - Turn off the BT radio for num_seconds */
  BT_OFF = 80,
  /** BT_ON - Turn on the BT radio for num_seconds */
  BT_ON = 81,
  /** WIFI_OFF - Turn off the WIFI radio for num_seconds */
  WIFI_OFF = 96,
  /** WIFI_ON - Turn on the WIFI radio for num_seconds */
  WIFI_ON = 97,
  /** GPS_OFF - Turn off the GPS radio for num_seconds */
  GPS_OFF = 112,
  /** GPS_ON - Turn on the GPS radio for num_seconds */
  GPS_ON = 113,
  UNRECOGNIZED = -1,
}

export function powerStressMessage_OpcodeFromJSON(object: any): PowerStressMessage_Opcode {
  switch (object) {
    case 0:
    case "UNSET":
      return PowerStressMessage_Opcode.UNSET;
    case 1:
    case "PRINT_INFO":
      return PowerStressMessage_Opcode.PRINT_INFO;
    case 2:
    case "FORCE_QUIET":
      return PowerStressMessage_Opcode.FORCE_QUIET;
    case 3:
    case "END_QUIET":
      return PowerStressMessage_Opcode.END_QUIET;
    case 16:
    case "SCREEN_ON":
      return PowerStressMessage_Opcode.SCREEN_ON;
    case 17:
    case "SCREEN_OFF":
      return PowerStressMessage_Opcode.SCREEN_OFF;
    case 32:
    case "CPU_IDLE":
      return PowerStressMessage_Opcode.CPU_IDLE;
    case 33:
    case "CPU_DEEPSLEEP":
      return PowerStressMessage_Opcode.CPU_DEEPSLEEP;
    case 34:
    case "CPU_FULLON":
      return PowerStressMessage_Opcode.CPU_FULLON;
    case 48:
    case "LED_ON":
      return PowerStressMessage_Opcode.LED_ON;
    case 49:
    case "LED_OFF":
      return PowerStressMessage_Opcode.LED_OFF;
    case 64:
    case "LORA_OFF":
      return PowerStressMessage_Opcode.LORA_OFF;
    case 65:
    case "LORA_TX":
      return PowerStressMessage_Opcode.LORA_TX;
    case 66:
    case "LORA_RX":
      return PowerStressMessage_Opcode.LORA_RX;
    case 80:
    case "BT_OFF":
      return PowerStressMessage_Opcode.BT_OFF;
    case 81:
    case "BT_ON":
      return PowerStressMessage_Opcode.BT_ON;
    case 96:
    case "WIFI_OFF":
      return PowerStressMessage_Opcode.WIFI_OFF;
    case 97:
    case "WIFI_ON":
      return PowerStressMessage_Opcode.WIFI_ON;
    case 112:
    case "GPS_OFF":
      return PowerStressMessage_Opcode.GPS_OFF;
    case 113:
    case "GPS_ON":
      return PowerStressMessage_Opcode.GPS_ON;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PowerStressMessage_Opcode.UNRECOGNIZED;
  }
}

export function powerStressMessage_OpcodeToJSON(object: PowerStressMessage_Opcode): string {
  switch (object) {
    case PowerStressMessage_Opcode.UNSET:
      return "UNSET";
    case PowerStressMessage_Opcode.PRINT_INFO:
      return "PRINT_INFO";
    case PowerStressMessage_Opcode.FORCE_QUIET:
      return "FORCE_QUIET";
    case PowerStressMessage_Opcode.END_QUIET:
      return "END_QUIET";
    case PowerStressMessage_Opcode.SCREEN_ON:
      return "SCREEN_ON";
    case PowerStressMessage_Opcode.SCREEN_OFF:
      return "SCREEN_OFF";
    case PowerStressMessage_Opcode.CPU_IDLE:
      return "CPU_IDLE";
    case PowerStressMessage_Opcode.CPU_DEEPSLEEP:
      return "CPU_DEEPSLEEP";
    case PowerStressMessage_Opcode.CPU_FULLON:
      return "CPU_FULLON";
    case PowerStressMessage_Opcode.LED_ON:
      return "LED_ON";
    case PowerStressMessage_Opcode.LED_OFF:
      return "LED_OFF";
    case PowerStressMessage_Opcode.LORA_OFF:
      return "LORA_OFF";
    case PowerStressMessage_Opcode.LORA_TX:
      return "LORA_TX";
    case PowerStressMessage_Opcode.LORA_RX:
      return "LORA_RX";
    case PowerStressMessage_Opcode.BT_OFF:
      return "BT_OFF";
    case PowerStressMessage_Opcode.BT_ON:
      return "BT_ON";
    case PowerStressMessage_Opcode.WIFI_OFF:
      return "WIFI_OFF";
    case PowerStressMessage_Opcode.WIFI_ON:
      return "WIFI_ON";
    case PowerStressMessage_Opcode.GPS_OFF:
      return "GPS_OFF";
    case PowerStressMessage_Opcode.GPS_ON:
      return "GPS_ON";
    case PowerStressMessage_Opcode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBasePowerMon(): PowerMon {
  return {};
}

export const PowerMon = {
  encode(_: PowerMon, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PowerMon {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePowerMon();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PowerMon {
    return {};
  },

  toJSON(_: PowerMon): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PowerMon>, I>>(base?: I): PowerMon {
    return PowerMon.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PowerMon>, I>>(_: I): PowerMon {
    const message = createBasePowerMon();
    return message;
  },
};

function createBasePowerStressMessage(): PowerStressMessage {
  return { cmd: 0, numSeconds: 0 };
}

export const PowerStressMessage = {
  encode(message: PowerStressMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.cmd !== 0) {
      writer.uint32(8).int32(message.cmd);
    }
    if (message.numSeconds !== 0) {
      writer.uint32(21).float(message.numSeconds);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PowerStressMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePowerStressMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.cmd = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.numSeconds = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PowerStressMessage {
    return {
      cmd: isSet(object.cmd) ? powerStressMessage_OpcodeFromJSON(object.cmd) : 0,
      numSeconds: isSet(object.numSeconds) ? globalThis.Number(object.numSeconds) : 0,
    };
  },

  toJSON(message: PowerStressMessage): unknown {
    const obj: any = {};
    if (message.cmd !== 0) {
      obj.cmd = powerStressMessage_OpcodeToJSON(message.cmd);
    }
    if (message.numSeconds !== 0) {
      obj.numSeconds = message.numSeconds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PowerStressMessage>, I>>(base?: I): PowerStressMessage {
    return PowerStressMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PowerStressMessage>, I>>(object: I): PowerStressMessage {
    const message = createBasePowerStressMessage();
    message.cmd = object.cmd ?? 0;
    message.numSeconds = object.numSeconds ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
