// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/remote_hardware.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import Long = require("long");

/**
 * An example app to show off the module system. This message is used for
 * REMOTE_HARDWARE_APP PortNums.
 * Also provides easy remote access to any GPIO.
 * In the future other remote hardware operations can be added based on user interest
 * (i.e. serial output, spi/i2c input/output).
 * FIXME - currently this feature is turned on by default which is dangerous
 * because no security yet (beyond the channel mechanism).
 * It should be off by default and then protected based on some TBD mechanism
 * (a special channel once multichannel support is included?)
 */
export interface HardwareMessage {
  /** What type of HardwareMessage is this? */
  type: HardwareMessage_Type;
  /** What gpios are we changing. Not used for all MessageTypes, see MessageType for details */
  gpioMask: number;
  /**
   * For gpios that were listed in gpio_mask as valid, what are the signal levels for those gpios.
   * Not used for all MessageTypes, see MessageType for details
   */
  gpioValue: number;
}

/** TODO: REPLACE */
export enum HardwareMessage_Type {
  /** UNSET - Unset/unused */
  UNSET = 0,
  /** WRITE_GPIOS - Set gpio gpios based on gpio_mask/gpio_value */
  WRITE_GPIOS = 1,
  /**
   * WATCH_GPIOS - We are now interested in watching the gpio_mask gpios.
   * If the selected gpios change, please broadcast GPIOS_CHANGED.
   * Will implicitly change the gpios requested to be INPUT gpios.
   */
  WATCH_GPIOS = 2,
  /** GPIOS_CHANGED - The gpios listed in gpio_mask have changed, the new values are listed in gpio_value */
  GPIOS_CHANGED = 3,
  /** READ_GPIOS - Read the gpios specified in gpio_mask, send back a READ_GPIOS_REPLY reply with gpio_value populated */
  READ_GPIOS = 4,
  /** READ_GPIOS_REPLY - A reply to READ_GPIOS. gpio_mask and gpio_value will be populated */
  READ_GPIOS_REPLY = 5,
  UNRECOGNIZED = -1,
}

export function hardwareMessage_TypeFromJSON(object: any): HardwareMessage_Type {
  switch (object) {
    case 0:
    case "UNSET":
      return HardwareMessage_Type.UNSET;
    case 1:
    case "WRITE_GPIOS":
      return HardwareMessage_Type.WRITE_GPIOS;
    case 2:
    case "WATCH_GPIOS":
      return HardwareMessage_Type.WATCH_GPIOS;
    case 3:
    case "GPIOS_CHANGED":
      return HardwareMessage_Type.GPIOS_CHANGED;
    case 4:
    case "READ_GPIOS":
      return HardwareMessage_Type.READ_GPIOS;
    case 5:
    case "READ_GPIOS_REPLY":
      return HardwareMessage_Type.READ_GPIOS_REPLY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HardwareMessage_Type.UNRECOGNIZED;
  }
}

export function hardwareMessage_TypeToJSON(object: HardwareMessage_Type): string {
  switch (object) {
    case HardwareMessage_Type.UNSET:
      return "UNSET";
    case HardwareMessage_Type.WRITE_GPIOS:
      return "WRITE_GPIOS";
    case HardwareMessage_Type.WATCH_GPIOS:
      return "WATCH_GPIOS";
    case HardwareMessage_Type.GPIOS_CHANGED:
      return "GPIOS_CHANGED";
    case HardwareMessage_Type.READ_GPIOS:
      return "READ_GPIOS";
    case HardwareMessage_Type.READ_GPIOS_REPLY:
      return "READ_GPIOS_REPLY";
    case HardwareMessage_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseHardwareMessage(): HardwareMessage {
  return { type: 0, gpioMask: 0, gpioValue: 0 };
}

export const HardwareMessage = {
  encode(message: HardwareMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.gpioMask !== 0) {
      writer.uint32(16).uint64(message.gpioMask);
    }
    if (message.gpioValue !== 0) {
      writer.uint32(24).uint64(message.gpioValue);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HardwareMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHardwareMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.gpioMask = longToNumber(reader.uint64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.gpioValue = longToNumber(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HardwareMessage {
    return {
      type: isSet(object.type) ? hardwareMessage_TypeFromJSON(object.type) : 0,
      gpioMask: isSet(object.gpioMask) ? globalThis.Number(object.gpioMask) : 0,
      gpioValue: isSet(object.gpioValue) ? globalThis.Number(object.gpioValue) : 0,
    };
  },

  toJSON(message: HardwareMessage): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = hardwareMessage_TypeToJSON(message.type);
    }
    if (message.gpioMask !== 0) {
      obj.gpioMask = Math.round(message.gpioMask);
    }
    if (message.gpioValue !== 0) {
      obj.gpioValue = Math.round(message.gpioValue);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HardwareMessage>, I>>(base?: I): HardwareMessage {
    return HardwareMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HardwareMessage>, I>>(object: I): HardwareMessage {
    const message = createBaseHardwareMessage();
    message.type = object.type ?? 0;
    message.gpioMask = object.gpioMask ?? 0;
    message.gpioValue = object.gpioValue ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
