// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/rtttl.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/** Canned message module configuration. */
export interface RTTTLConfig {
  /** Ringtone for PWM Buzzer in RTTTL Format. */
  ringtone: string;
}

function createBaseRTTTLConfig(): RTTTLConfig {
  return { ringtone: "" };
}

export const RTTTLConfig = {
  encode(message: RTTTLConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ringtone !== "") {
      writer.uint32(10).string(message.ringtone);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RTTTLConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRTTTLConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ringtone = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RTTTLConfig {
    return { ringtone: isSet(object.ringtone) ? globalThis.String(object.ringtone) : "" };
  },

  toJSON(message: RTTTLConfig): unknown {
    const obj: any = {};
    if (message.ringtone !== "") {
      obj.ringtone = message.ringtone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RTTTLConfig>, I>>(base?: I): RTTTLConfig {
    return RTTTLConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RTTTLConfig>, I>>(object: I): RTTTLConfig {
    const message = createBaseRTTTLConfig();
    message.ringtone = object.ringtone ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
