// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/serial_hal.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export interface SerialHalCommand {
  /**
   * Host-assigned request id. Replies echo this id back in
   * SerialHalResponse.transaction_id.
   */
  transactionId: number;
  type: SerialHalCommand_Type;
  pin: number;
  value: number;
  mode: number;
  data: Uint8Array;
}

export enum SerialHalCommand_Type {
  UNSET = 0,
  PIN_MODE = 1,
  DIGITAL_WRITE = 2,
  DIGITAL_READ = 3,
  ATTACH_INTERRUPT = 4,
  DETACH_INTERRUPT = 5,
  SPI_TRANSFER = 6,
  NOOP = 7,
  UNRECOGNIZED = -1,
}

export function serialHalCommand_TypeFromJSON(object: any): SerialHalCommand_Type {
  switch (object) {
    case 0:
    case "UNSET":
      return SerialHalCommand_Type.UNSET;
    case 1:
    case "PIN_MODE":
      return SerialHalCommand_Type.PIN_MODE;
    case 2:
    case "DIGITAL_WRITE":
      return SerialHalCommand_Type.DIGITAL_WRITE;
    case 3:
    case "DIGITAL_READ":
      return SerialHalCommand_Type.DIGITAL_READ;
    case 4:
    case "ATTACH_INTERRUPT":
      return SerialHalCommand_Type.ATTACH_INTERRUPT;
    case 5:
    case "DETACH_INTERRUPT":
      return SerialHalCommand_Type.DETACH_INTERRUPT;
    case 6:
    case "SPI_TRANSFER":
      return SerialHalCommand_Type.SPI_TRANSFER;
    case 7:
    case "NOOP":
      return SerialHalCommand_Type.NOOP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SerialHalCommand_Type.UNRECOGNIZED;
  }
}

export function serialHalCommand_TypeToJSON(object: SerialHalCommand_Type): string {
  switch (object) {
    case SerialHalCommand_Type.UNSET:
      return "UNSET";
    case SerialHalCommand_Type.PIN_MODE:
      return "PIN_MODE";
    case SerialHalCommand_Type.DIGITAL_WRITE:
      return "DIGITAL_WRITE";
    case SerialHalCommand_Type.DIGITAL_READ:
      return "DIGITAL_READ";
    case SerialHalCommand_Type.ATTACH_INTERRUPT:
      return "ATTACH_INTERRUPT";
    case SerialHalCommand_Type.DETACH_INTERRUPT:
      return "DETACH_INTERRUPT";
    case SerialHalCommand_Type.SPI_TRANSFER:
      return "SPI_TRANSFER";
    case SerialHalCommand_Type.NOOP:
      return "NOOP";
    case SerialHalCommand_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SerialHalResponse {
  /**
   * Matches the originating SerialHalCommand.transaction_id for normal
   * request/response traffic.
   *
   * A value of 0 indicates an unsolicited interrupt notification generated by
   * the device. In that case, the host should interpret value as the GPIO pin
   * that triggered.
   */
  transactionId: number;
  result: SerialHalResponse_Result;
  /**
   * Used by DIGITAL_READ replies and interrupt notifications. For interrupt
   * notifications (transaction_id == 0), this carries the pin number.
   */
  value: number;
  data: Uint8Array;
  error: string;
}

export enum SerialHalResponse_Result {
  OK = 0,
  ERROR = 1,
  BAD_REQUEST = 2,
  UNSUPPORTED = 3,
  UNRECOGNIZED = -1,
}

export function serialHalResponse_ResultFromJSON(object: any): SerialHalResponse_Result {
  switch (object) {
    case 0:
    case "OK":
      return SerialHalResponse_Result.OK;
    case 1:
    case "ERROR":
      return SerialHalResponse_Result.ERROR;
    case 2:
    case "BAD_REQUEST":
      return SerialHalResponse_Result.BAD_REQUEST;
    case 3:
    case "UNSUPPORTED":
      return SerialHalResponse_Result.UNSUPPORTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SerialHalResponse_Result.UNRECOGNIZED;
  }
}

export function serialHalResponse_ResultToJSON(object: SerialHalResponse_Result): string {
  switch (object) {
    case SerialHalResponse_Result.OK:
      return "OK";
    case SerialHalResponse_Result.ERROR:
      return "ERROR";
    case SerialHalResponse_Result.BAD_REQUEST:
      return "BAD_REQUEST";
    case SerialHalResponse_Result.UNSUPPORTED:
      return "UNSUPPORTED";
    case SerialHalResponse_Result.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseSerialHalCommand(): SerialHalCommand {
  return { transactionId: 0, type: 0, pin: 0, value: 0, mode: 0, data: new Uint8Array(0) };
}

export const SerialHalCommand = {
  encode(message: SerialHalCommand, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.transactionId !== 0) {
      writer.uint32(8).uint32(message.transactionId);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.pin !== 0) {
      writer.uint32(24).uint32(message.pin);
    }
    if (message.value !== 0) {
      writer.uint32(32).uint32(message.value);
    }
    if (message.mode !== 0) {
      writer.uint32(40).uint32(message.mode);
    }
    if (message.data.length !== 0) {
      writer.uint32(50).bytes(message.data);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SerialHalCommand {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSerialHalCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.transactionId = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.pin = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.value = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.data = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SerialHalCommand {
    return {
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      type: isSet(object.type) ? serialHalCommand_TypeFromJSON(object.type) : 0,
      pin: isSet(object.pin) ? globalThis.Number(object.pin) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: SerialHalCommand): unknown {
    const obj: any = {};
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.type !== 0) {
      obj.type = serialHalCommand_TypeToJSON(message.type);
    }
    if (message.pin !== 0) {
      obj.pin = Math.round(message.pin);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SerialHalCommand>, I>>(base?: I): SerialHalCommand {
    return SerialHalCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SerialHalCommand>, I>>(object: I): SerialHalCommand {
    const message = createBaseSerialHalCommand();
    message.transactionId = object.transactionId ?? 0;
    message.type = object.type ?? 0;
    message.pin = object.pin ?? 0;
    message.value = object.value ?? 0;
    message.mode = object.mode ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSerialHalResponse(): SerialHalResponse {
  return { transactionId: 0, result: 0, value: 0, data: new Uint8Array(0), error: "" };
}

export const SerialHalResponse = {
  encode(message: SerialHalResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.transactionId !== 0) {
      writer.uint32(8).uint32(message.transactionId);
    }
    if (message.result !== 0) {
      writer.uint32(16).int32(message.result);
    }
    if (message.value !== 0) {
      writer.uint32(24).uint32(message.value);
    }
    if (message.data.length !== 0) {
      writer.uint32(34).bytes(message.data);
    }
    if (message.error !== "") {
      writer.uint32(42).string(message.error);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SerialHalResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSerialHalResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.transactionId = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.value = reader.uint32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.data = reader.bytes();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.error = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SerialHalResponse {
    return {
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      result: isSet(object.result) ? serialHalResponse_ResultFromJSON(object.result) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SerialHalResponse): unknown {
    const obj: any = {};
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.result !== 0) {
      obj.result = serialHalResponse_ResultToJSON(message.result);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SerialHalResponse>, I>>(base?: I): SerialHalResponse {
    return SerialHalResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SerialHalResponse>, I>>(object: I): SerialHalResponse {
    const message = createBaseSerialHalResponse();
    message.transactionId = object.transactionId ?? 0;
    message.result = object.result ?? 0;
    message.value = object.value ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    message.error = object.error ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
