// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/storeforward.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

/** TODO: REPLACE */
export interface StoreAndForward {
  /** TODO: REPLACE */
  rr: StoreAndForward_RequestResponse;
  /** TODO: REPLACE */
  stats?:
    | StoreAndForward_Statistics
    | undefined;
  /** TODO: REPLACE */
  history?:
    | StoreAndForward_History
    | undefined;
  /** TODO: REPLACE */
  heartbeat?:
    | StoreAndForward_Heartbeat
    | undefined;
  /** Text from history message. */
  text?: Uint8Array | undefined;
}

/**
 * 001 - 063 = From Router
 * 064 - 127 = From Client
 */
export enum StoreAndForward_RequestResponse {
  /** UNSET - Unset/unused */
  UNSET = 0,
  /** ROUTER_ERROR - Router is an in error state. */
  ROUTER_ERROR = 1,
  /** ROUTER_HEARTBEAT - Router heartbeat */
  ROUTER_HEARTBEAT = 2,
  /**
   * ROUTER_PING - Router has requested the client respond. This can work as a
   * "are you there" message.
   */
  ROUTER_PING = 3,
  /** ROUTER_PONG - The response to a "Ping" */
  ROUTER_PONG = 4,
  /** ROUTER_BUSY - Router is currently busy. Please try again later. */
  ROUTER_BUSY = 5,
  /** ROUTER_HISTORY - Router is responding to a request for history. */
  ROUTER_HISTORY = 6,
  /** ROUTER_STATS - Router is responding to a request for stats. */
  ROUTER_STATS = 7,
  /** ROUTER_TEXT_DIRECT - Router sends a text message from its history that was a direct message. */
  ROUTER_TEXT_DIRECT = 8,
  /** ROUTER_TEXT_BROADCAST - Router sends a text message from its history that was a broadcast. */
  ROUTER_TEXT_BROADCAST = 9,
  /** CLIENT_ERROR - Client is an in error state. */
  CLIENT_ERROR = 64,
  /** CLIENT_HISTORY - Client has requested a replay from the router. */
  CLIENT_HISTORY = 65,
  /** CLIENT_STATS - Client has requested stats from the router. */
  CLIENT_STATS = 66,
  /**
   * CLIENT_PING - Client has requested the router respond. This can work as a
   * "are you there" message.
   */
  CLIENT_PING = 67,
  /** CLIENT_PONG - The response to a "Ping" */
  CLIENT_PONG = 68,
  /** CLIENT_ABORT - Client has requested that the router abort processing the client's request */
  CLIENT_ABORT = 106,
  UNRECOGNIZED = -1,
}

export function storeAndForward_RequestResponseFromJSON(object: any): StoreAndForward_RequestResponse {
  switch (object) {
    case 0:
    case "UNSET":
      return StoreAndForward_RequestResponse.UNSET;
    case 1:
    case "ROUTER_ERROR":
      return StoreAndForward_RequestResponse.ROUTER_ERROR;
    case 2:
    case "ROUTER_HEARTBEAT":
      return StoreAndForward_RequestResponse.ROUTER_HEARTBEAT;
    case 3:
    case "ROUTER_PING":
      return StoreAndForward_RequestResponse.ROUTER_PING;
    case 4:
    case "ROUTER_PONG":
      return StoreAndForward_RequestResponse.ROUTER_PONG;
    case 5:
    case "ROUTER_BUSY":
      return StoreAndForward_RequestResponse.ROUTER_BUSY;
    case 6:
    case "ROUTER_HISTORY":
      return StoreAndForward_RequestResponse.ROUTER_HISTORY;
    case 7:
    case "ROUTER_STATS":
      return StoreAndForward_RequestResponse.ROUTER_STATS;
    case 8:
    case "ROUTER_TEXT_DIRECT":
      return StoreAndForward_RequestResponse.ROUTER_TEXT_DIRECT;
    case 9:
    case "ROUTER_TEXT_BROADCAST":
      return StoreAndForward_RequestResponse.ROUTER_TEXT_BROADCAST;
    case 64:
    case "CLIENT_ERROR":
      return StoreAndForward_RequestResponse.CLIENT_ERROR;
    case 65:
    case "CLIENT_HISTORY":
      return StoreAndForward_RequestResponse.CLIENT_HISTORY;
    case 66:
    case "CLIENT_STATS":
      return StoreAndForward_RequestResponse.CLIENT_STATS;
    case 67:
    case "CLIENT_PING":
      return StoreAndForward_RequestResponse.CLIENT_PING;
    case 68:
    case "CLIENT_PONG":
      return StoreAndForward_RequestResponse.CLIENT_PONG;
    case 106:
    case "CLIENT_ABORT":
      return StoreAndForward_RequestResponse.CLIENT_ABORT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StoreAndForward_RequestResponse.UNRECOGNIZED;
  }
}

export function storeAndForward_RequestResponseToJSON(object: StoreAndForward_RequestResponse): string {
  switch (object) {
    case StoreAndForward_RequestResponse.UNSET:
      return "UNSET";
    case StoreAndForward_RequestResponse.ROUTER_ERROR:
      return "ROUTER_ERROR";
    case StoreAndForward_RequestResponse.ROUTER_HEARTBEAT:
      return "ROUTER_HEARTBEAT";
    case StoreAndForward_RequestResponse.ROUTER_PING:
      return "ROUTER_PING";
    case StoreAndForward_RequestResponse.ROUTER_PONG:
      return "ROUTER_PONG";
    case StoreAndForward_RequestResponse.ROUTER_BUSY:
      return "ROUTER_BUSY";
    case StoreAndForward_RequestResponse.ROUTER_HISTORY:
      return "ROUTER_HISTORY";
    case StoreAndForward_RequestResponse.ROUTER_STATS:
      return "ROUTER_STATS";
    case StoreAndForward_RequestResponse.ROUTER_TEXT_DIRECT:
      return "ROUTER_TEXT_DIRECT";
    case StoreAndForward_RequestResponse.ROUTER_TEXT_BROADCAST:
      return "ROUTER_TEXT_BROADCAST";
    case StoreAndForward_RequestResponse.CLIENT_ERROR:
      return "CLIENT_ERROR";
    case StoreAndForward_RequestResponse.CLIENT_HISTORY:
      return "CLIENT_HISTORY";
    case StoreAndForward_RequestResponse.CLIENT_STATS:
      return "CLIENT_STATS";
    case StoreAndForward_RequestResponse.CLIENT_PING:
      return "CLIENT_PING";
    case StoreAndForward_RequestResponse.CLIENT_PONG:
      return "CLIENT_PONG";
    case StoreAndForward_RequestResponse.CLIENT_ABORT:
      return "CLIENT_ABORT";
    case StoreAndForward_RequestResponse.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** TODO: REPLACE */
export interface StoreAndForward_Statistics {
  /** Number of messages we have ever seen */
  messagesTotal: number;
  /** Number of messages we have currently saved our history. */
  messagesSaved: number;
  /** Maximum number of messages we will save */
  messagesMax: number;
  /** Router uptime in seconds */
  upTime: number;
  /** Number of times any client sent a request to the S&F. */
  requests: number;
  /** Number of times the history was requested. */
  requestsHistory: number;
  /** Is the heartbeat enabled on the server? */
  heartbeat: boolean;
  /** Maximum number of messages the server will return. */
  returnMax: number;
  /** Maximum history window in minutes the server will return messages from. */
  returnWindow: number;
}

/** TODO: REPLACE */
export interface StoreAndForward_History {
  /** Number of that will be sent to the client */
  historyMessages: number;
  /** The window of messages that was used to filter the history client requested */
  window: number;
  /**
   * Index in the packet history of the last message sent in a previous request to the server.
   * Will be sent to the client before sending the history and can be set in a subsequent request to avoid getting packets the server already sent to the client.
   */
  lastRequest: number;
}

/** TODO: REPLACE */
export interface StoreAndForward_Heartbeat {
  /** Period in seconds that the heartbeat is sent out that will be sent to the client */
  period: number;
  /** If set, this is not the primary Store & Forward router on the mesh */
  secondary: number;
}

function createBaseStoreAndForward(): StoreAndForward {
  return { rr: 0, stats: undefined, history: undefined, heartbeat: undefined, text: undefined };
}

export const StoreAndForward = {
  encode(message: StoreAndForward, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.rr !== 0) {
      writer.uint32(8).int32(message.rr);
    }
    if (message.stats !== undefined) {
      StoreAndForward_Statistics.encode(message.stats, writer.uint32(18).fork()).ldelim();
    }
    if (message.history !== undefined) {
      StoreAndForward_History.encode(message.history, writer.uint32(26).fork()).ldelim();
    }
    if (message.heartbeat !== undefined) {
      StoreAndForward_Heartbeat.encode(message.heartbeat, writer.uint32(34).fork()).ldelim();
    }
    if (message.text !== undefined) {
      writer.uint32(42).bytes(message.text);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StoreAndForward {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreAndForward();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.rr = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.stats = StoreAndForward_Statistics.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.history = StoreAndForward_History.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.heartbeat = StoreAndForward_Heartbeat.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.text = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreAndForward {
    return {
      rr: isSet(object.rr) ? storeAndForward_RequestResponseFromJSON(object.rr) : 0,
      stats: isSet(object.stats) ? StoreAndForward_Statistics.fromJSON(object.stats) : undefined,
      history: isSet(object.history) ? StoreAndForward_History.fromJSON(object.history) : undefined,
      heartbeat: isSet(object.heartbeat) ? StoreAndForward_Heartbeat.fromJSON(object.heartbeat) : undefined,
      text: isSet(object.text) ? bytesFromBase64(object.text) : undefined,
    };
  },

  toJSON(message: StoreAndForward): unknown {
    const obj: any = {};
    if (message.rr !== 0) {
      obj.rr = storeAndForward_RequestResponseToJSON(message.rr);
    }
    if (message.stats !== undefined) {
      obj.stats = StoreAndForward_Statistics.toJSON(message.stats);
    }
    if (message.history !== undefined) {
      obj.history = StoreAndForward_History.toJSON(message.history);
    }
    if (message.heartbeat !== undefined) {
      obj.heartbeat = StoreAndForward_Heartbeat.toJSON(message.heartbeat);
    }
    if (message.text !== undefined) {
      obj.text = base64FromBytes(message.text);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoreAndForward>, I>>(base?: I): StoreAndForward {
    return StoreAndForward.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreAndForward>, I>>(object: I): StoreAndForward {
    const message = createBaseStoreAndForward();
    message.rr = object.rr ?? 0;
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? StoreAndForward_Statistics.fromPartial(object.stats)
      : undefined;
    message.history = (object.history !== undefined && object.history !== null)
      ? StoreAndForward_History.fromPartial(object.history)
      : undefined;
    message.heartbeat = (object.heartbeat !== undefined && object.heartbeat !== null)
      ? StoreAndForward_Heartbeat.fromPartial(object.heartbeat)
      : undefined;
    message.text = object.text ?? undefined;
    return message;
  },
};

function createBaseStoreAndForward_Statistics(): StoreAndForward_Statistics {
  return {
    messagesTotal: 0,
    messagesSaved: 0,
    messagesMax: 0,
    upTime: 0,
    requests: 0,
    requestsHistory: 0,
    heartbeat: false,
    returnMax: 0,
    returnWindow: 0,
  };
}

export const StoreAndForward_Statistics = {
  encode(message: StoreAndForward_Statistics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.messagesTotal !== 0) {
      writer.uint32(8).uint32(message.messagesTotal);
    }
    if (message.messagesSaved !== 0) {
      writer.uint32(16).uint32(message.messagesSaved);
    }
    if (message.messagesMax !== 0) {
      writer.uint32(24).uint32(message.messagesMax);
    }
    if (message.upTime !== 0) {
      writer.uint32(32).uint32(message.upTime);
    }
    if (message.requests !== 0) {
      writer.uint32(40).uint32(message.requests);
    }
    if (message.requestsHistory !== 0) {
      writer.uint32(48).uint32(message.requestsHistory);
    }
    if (message.heartbeat !== false) {
      writer.uint32(56).bool(message.heartbeat);
    }
    if (message.returnMax !== 0) {
      writer.uint32(64).uint32(message.returnMax);
    }
    if (message.returnWindow !== 0) {
      writer.uint32(72).uint32(message.returnWindow);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StoreAndForward_Statistics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreAndForward_Statistics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.messagesTotal = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.messagesSaved = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.messagesMax = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.upTime = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.requests = reader.uint32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.requestsHistory = reader.uint32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.heartbeat = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.returnMax = reader.uint32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.returnWindow = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreAndForward_Statistics {
    return {
      messagesTotal: isSet(object.messagesTotal) ? globalThis.Number(object.messagesTotal) : 0,
      messagesSaved: isSet(object.messagesSaved) ? globalThis.Number(object.messagesSaved) : 0,
      messagesMax: isSet(object.messagesMax) ? globalThis.Number(object.messagesMax) : 0,
      upTime: isSet(object.upTime) ? globalThis.Number(object.upTime) : 0,
      requests: isSet(object.requests) ? globalThis.Number(object.requests) : 0,
      requestsHistory: isSet(object.requestsHistory) ? globalThis.Number(object.requestsHistory) : 0,
      heartbeat: isSet(object.heartbeat) ? globalThis.Boolean(object.heartbeat) : false,
      returnMax: isSet(object.returnMax) ? globalThis.Number(object.returnMax) : 0,
      returnWindow: isSet(object.returnWindow) ? globalThis.Number(object.returnWindow) : 0,
    };
  },

  toJSON(message: StoreAndForward_Statistics): unknown {
    const obj: any = {};
    if (message.messagesTotal !== 0) {
      obj.messagesTotal = Math.round(message.messagesTotal);
    }
    if (message.messagesSaved !== 0) {
      obj.messagesSaved = Math.round(message.messagesSaved);
    }
    if (message.messagesMax !== 0) {
      obj.messagesMax = Math.round(message.messagesMax);
    }
    if (message.upTime !== 0) {
      obj.upTime = Math.round(message.upTime);
    }
    if (message.requests !== 0) {
      obj.requests = Math.round(message.requests);
    }
    if (message.requestsHistory !== 0) {
      obj.requestsHistory = Math.round(message.requestsHistory);
    }
    if (message.heartbeat !== false) {
      obj.heartbeat = message.heartbeat;
    }
    if (message.returnMax !== 0) {
      obj.returnMax = Math.round(message.returnMax);
    }
    if (message.returnWindow !== 0) {
      obj.returnWindow = Math.round(message.returnWindow);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoreAndForward_Statistics>, I>>(base?: I): StoreAndForward_Statistics {
    return StoreAndForward_Statistics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreAndForward_Statistics>, I>>(object: I): StoreAndForward_Statistics {
    const message = createBaseStoreAndForward_Statistics();
    message.messagesTotal = object.messagesTotal ?? 0;
    message.messagesSaved = object.messagesSaved ?? 0;
    message.messagesMax = object.messagesMax ?? 0;
    message.upTime = object.upTime ?? 0;
    message.requests = object.requests ?? 0;
    message.requestsHistory = object.requestsHistory ?? 0;
    message.heartbeat = object.heartbeat ?? false;
    message.returnMax = object.returnMax ?? 0;
    message.returnWindow = object.returnWindow ?? 0;
    return message;
  },
};

function createBaseStoreAndForward_History(): StoreAndForward_History {
  return { historyMessages: 0, window: 0, lastRequest: 0 };
}

export const StoreAndForward_History = {
  encode(message: StoreAndForward_History, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.historyMessages !== 0) {
      writer.uint32(8).uint32(message.historyMessages);
    }
    if (message.window !== 0) {
      writer.uint32(16).uint32(message.window);
    }
    if (message.lastRequest !== 0) {
      writer.uint32(24).uint32(message.lastRequest);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StoreAndForward_History {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreAndForward_History();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.historyMessages = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.window = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.lastRequest = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreAndForward_History {
    return {
      historyMessages: isSet(object.historyMessages) ? globalThis.Number(object.historyMessages) : 0,
      window: isSet(object.window) ? globalThis.Number(object.window) : 0,
      lastRequest: isSet(object.lastRequest) ? globalThis.Number(object.lastRequest) : 0,
    };
  },

  toJSON(message: StoreAndForward_History): unknown {
    const obj: any = {};
    if (message.historyMessages !== 0) {
      obj.historyMessages = Math.round(message.historyMessages);
    }
    if (message.window !== 0) {
      obj.window = Math.round(message.window);
    }
    if (message.lastRequest !== 0) {
      obj.lastRequest = Math.round(message.lastRequest);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoreAndForward_History>, I>>(base?: I): StoreAndForward_History {
    return StoreAndForward_History.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreAndForward_History>, I>>(object: I): StoreAndForward_History {
    const message = createBaseStoreAndForward_History();
    message.historyMessages = object.historyMessages ?? 0;
    message.window = object.window ?? 0;
    message.lastRequest = object.lastRequest ?? 0;
    return message;
  },
};

function createBaseStoreAndForward_Heartbeat(): StoreAndForward_Heartbeat {
  return { period: 0, secondary: 0 };
}

export const StoreAndForward_Heartbeat = {
  encode(message: StoreAndForward_Heartbeat, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.period !== 0) {
      writer.uint32(8).uint32(message.period);
    }
    if (message.secondary !== 0) {
      writer.uint32(16).uint32(message.secondary);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StoreAndForward_Heartbeat {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoreAndForward_Heartbeat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.period = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.secondary = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoreAndForward_Heartbeat {
    return {
      period: isSet(object.period) ? globalThis.Number(object.period) : 0,
      secondary: isSet(object.secondary) ? globalThis.Number(object.secondary) : 0,
    };
  },

  toJSON(message: StoreAndForward_Heartbeat): unknown {
    const obj: any = {};
    if (message.period !== 0) {
      obj.period = Math.round(message.period);
    }
    if (message.secondary !== 0) {
      obj.secondary = Math.round(message.secondary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoreAndForward_Heartbeat>, I>>(base?: I): StoreAndForward_Heartbeat {
    return StoreAndForward_Heartbeat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoreAndForward_Heartbeat>, I>>(object: I): StoreAndForward_Heartbeat {
    const message = createBaseStoreAndForward_Heartbeat();
    message.period = object.period ?? 0;
    message.secondary = object.secondary ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
