// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: meshtastic/xmodem.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export interface XModem {
  control: XModem_Control;
  seq: number;
  crc16: number;
  buffer: Uint8Array;
}

export enum XModem_Control {
  NUL = 0,
  SOH = 1,
  STX = 2,
  EOT = 4,
  ACK = 6,
  NAK = 21,
  CAN = 24,
  CTRLZ = 26,
  UNRECOGNIZED = -1,
}

export function xModem_ControlFromJSON(object: any): XModem_Control {
  switch (object) {
    case 0:
    case "NUL":
      return XModem_Control.NUL;
    case 1:
    case "SOH":
      return XModem_Control.SOH;
    case 2:
    case "STX":
      return XModem_Control.STX;
    case 4:
    case "EOT":
      return XModem_Control.EOT;
    case 6:
    case "ACK":
      return XModem_Control.ACK;
    case 21:
    case "NAK":
      return XModem_Control.NAK;
    case 24:
    case "CAN":
      return XModem_Control.CAN;
    case 26:
    case "CTRLZ":
      return XModem_Control.CTRLZ;
    case -1:
    case "UNRECOGNIZED":
    default:
      return XModem_Control.UNRECOGNIZED;
  }
}

export function xModem_ControlToJSON(object: XModem_Control): string {
  switch (object) {
    case XModem_Control.NUL:
      return "NUL";
    case XModem_Control.SOH:
      return "SOH";
    case XModem_Control.STX:
      return "STX";
    case XModem_Control.EOT:
      return "EOT";
    case XModem_Control.ACK:
      return "ACK";
    case XModem_Control.NAK:
      return "NAK";
    case XModem_Control.CAN:
      return "CAN";
    case XModem_Control.CTRLZ:
      return "CTRLZ";
    case XModem_Control.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseXModem(): XModem {
  return { control: 0, seq: 0, crc16: 0, buffer: new Uint8Array(0) };
}

export const XModem = {
  encode(message: XModem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.control !== 0) {
      writer.uint32(8).int32(message.control);
    }
    if (message.seq !== 0) {
      writer.uint32(16).uint32(message.seq);
    }
    if (message.crc16 !== 0) {
      writer.uint32(24).uint32(message.crc16);
    }
    if (message.buffer.length !== 0) {
      writer.uint32(34).bytes(message.buffer);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): XModem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseXModem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.control = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.seq = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.crc16 = reader.uint32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.buffer = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): XModem {
    return {
      control: isSet(object.control) ? xModem_ControlFromJSON(object.control) : 0,
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      crc16: isSet(object.crc16) ? globalThis.Number(object.crc16) : 0,
      buffer: isSet(object.buffer) ? bytesFromBase64(object.buffer) : new Uint8Array(0),
    };
  },

  toJSON(message: XModem): unknown {
    const obj: any = {};
    if (message.control !== 0) {
      obj.control = xModem_ControlToJSON(message.control);
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.crc16 !== 0) {
      obj.crc16 = Math.round(message.crc16);
    }
    if (message.buffer.length !== 0) {
      obj.buffer = base64FromBytes(message.buffer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<XModem>, I>>(base?: I): XModem {
    return XModem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<XModem>, I>>(object: I): XModem {
    const message = createBaseXModem();
    message.control = object.control ?? 0;
    message.seq = object.seq ?? 0;
    message.crc16 = object.crc16 ?? 0;
    message.buffer = object.buffer ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
